### ISSUE TITLE
Create syntax specific settings

### ISSUE THREAD

**Issue by TheThirdOne** [thomaswilburn/Caret#184]
#158 
Having an ability to specify settings specific to say markdown files would be useful.

**Comment by mebrunet** [comment]
How can I add basic Arduino syntax support? I really just want to interpret .ino files as .cpp files (the syntax is almost identical). More generally, is there a way to chose chose how a file's syntax is displayed when the extension is not automatically recognized?

**Comment by thomaswilburn** [comment]
These are all set in the ace.json file. You can add a menu item to edit your own, and then I add them to the repo file to roll out to everyone when it makes sense (this probably does).

**Comment by victorel-petrovich** [comment]
Is this issue (Create syntax specific settings) about customizing a mode, i.e changing the syntax highlighting rules,for , say , asciidoc mode? 

If yes, then it's a great idea.

**Comment by thomaswilburn** [comment]
This is an issue for specifically setting Caret settings in response to the syntax mode. Changing the modes themselves is something we leave up to Ace.
