### ISSUE TITLE
Add JSLint support

### ISSUE THREAD

**Issue by EvgenyOrekhov** [thomaswilburn/Caret#321]
I'd like to be able to use JSLint instead of JSHint.
I tried to assign the JSLint library code to the `JSHINT` variable in `js/ace/worker-javascript.js` and it started working without any additional changes.
I wonder if you could add the JSLint library and a new option to user preferences, something like
```js
"jsLinter": "jshint" //jshint or jslint (warning: JSLint will hurt your feelings)
```

**Comment by thomaswilburn** [comment]
JSHint is built into Ace, and isn't something I can just swap out without taking on additional dependencies from upstream. Feel free to open an issue with them about it.
