### ISSUE TITLE
modeline

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#325]
Is it possible to add something like the `modeline` in vim?
Or a file extension which would turn on word wrap?

Normally, I am editing code so like `nowrap`.
I guess this is something to ask ace about.

**Comment by thomaswilburn** [comment]
I'm not going to add a modeline, no. I'm not interested in turning Caret into Vim. If the latter is what you want, I still think you're better off just using the real thing.

There is, I believe, an issue for per-syntax settings, and this could be used to trigger word wrap only on certain kinds of files. But I haven't had a chance to make any progress on it, and nobody else has submitted a pull request for it.

**Comment by broomdodger** [comment]
Caret is a **great** editor, I like it, and thank you for making it available.
I would not want Caret to be like vim, the ace vim keybindings are not useful to me.

The `issue for per-syntax settings`, is that on the ace git? or Caret?

**Comment by thomaswilburn** [comment]
It's on Caret. Ace doesn't have any concept of files.
