### ISSUE TITLE
Saving File

### ISSUE THREAD

**Issue by cbaldwinweb** [thomaswilburn/Caret#327]
When changing the language to say JavaScript and then clicking save it automatically saves it as an undefined file type. I think if the user changes the language in the editor that it should add the extension to the file name when saving.

**Comment by thomaswilburn** [comment]
It's not a bad idea, but at this time there's not a tight coupling between our File and Tab prototypes. Frankly, you're going to end up changing the filename anyway, so it's always seemed kind of gratuitous to me, especially since for many languages there are multiple file types available.

Anyway, I'll leave this open, but I wouldn't expect it to change any time soon unless you want to tackle it yourself.

**Comment by cbaldwinweb** [comment]
I understand the changing the file later, or whatever you were getting at though the problem is, every other software will automatically assign the file extension. This does not. I will tackle this for sure I understand the chrome filesystem and just need to know what JS you used for the syntax highlighter.

**Comment by thomaswilburn** [comment]
I wouldn't actually worry about the JS for the syntax highlighter. If I were you, I would pay attention to `tab.js` and `storage/file.js`, which actually implement this. The tab knows which syntaxMode it's in, and can look that up in the ace.json settings file to find an extension. You can then pass a proposed filename to the File object when the Tab calls its `save()` method.

No matter what, we will _not_ be able to add an extension if the user didn't provide one. Chrome doesn't give us the ability to alter a filename after it has been chosen by the user.

**Comment by cbaldwinweb** [comment]
We could use the `suggestedName` property of the save chrome to suggested the extension name. Such as 

`this.fileName = file.entry.name + self.syntaxMode` if that is what the `self.syntaxMode` returns is the extension type per se. I'm looking through all the code now.

**Comment by thomaswilburn** [comment]
Yes, we can suggest a name, but what we can't do is add the extension if someone takes that name and just writes the first part of the filename. I don't know if this is what you meant.

`self.syntaxMode` will not give you the extension, it will match the Ace syntax highlighting modes. However, the ace.json file can be loaded from settings, and used to look up the extensions that match that syntax mode.

**Comment by cbaldwinweb** [comment]
Alright yes while looking through I see some flaws with the Chrome FileSystem. A explicit type extension should be written, when I rewrite the filename the file then has no file extension. Just named "File" which is whatever. I'll look into a method of this.

**Comment by cbaldwinweb** [comment]
I'm going to clone the repo and see what I can add to this since this is my new favorite editor.
