### ISSUE TITLE
auto format or some way to do it with ace

### ISSUE THREAD

**Issue by mattlockyer** [thomaswilburn/Caret#329]
Currently to auto format or prettify code in ace you have to do one of the following tricks:

http://stackoverflow.com/questions/10753543/how-to-format-code-in-ace-editor

1)
var Mode = require('ace/mode/xml').Mode;
editor.getSession().setMode(new Mode());

2)
var code = ace.getSession().getValue();
// prettify
ace.getSession().setValue(code);

These are currently unavailable to set as user commands do to the way the commands are formatted.

Is there any way to accomplish auto format?

**Comment by thomaswilburn** [comment]
You mean apart from the format menu in the bottom right, or the "Set Syntax" commands in the palette?

Actually, they're not unavailable as commands anyway. "session:syntax" accepts a mode parameter that matches the mode name from Ace ("xml", "html", etc.)
