### ISSUE TITLE
How to search an entire folder?

### ISSUE THREAD

**Issue by henrywright** [thomaswilburn/Caret#336]
I recently found the Ctrl + F and Ctrl + H keyboard shortcuts which let me search through a single file. I can also do the same by clicking on the Edit menu then clicking Find or Find/Replace. 

Is it possible to search all files in a given folder? For example, I know there's some text "is_installed" in my project folder somewhere but I can't remember which file it's in.

**Comment by thomaswilburn** [comment]
No, there's no solution to do that with Caret at this time.

**Comment by henrywright** [comment]
OK, thanks for letting me know.
