### ISSUE TITLE
line height

### ISSUE THREAD

**Issue by isidrorg** [thomaswilburn/Caret#337]
I'm using Caret to learn some code because I'm allways using diferents computers between my house and university. Great text editor, really!!

My problem is that I need big fonts, I'm using `"fontFamily": "source code pro"` with `fontSize": 18` but the lines are vertically too near for my taste. Is it possible to add more line height?

**Comment by thomaswilburn** [comment]
That is a good bug to file against Ace--I don't think I have any way to set that right now.

**Comment by victorel-petrovich** [comment]
Hi @thomaswilburn ,

I filed such an issue at ace https://github.com/ajaxorg/ace/issues/2534#issuecomment-109708377 . Could you please advise how to use their solution  "You can use editor.container.style.lineHeight = 3" ?

**Comment by thomaswilburn** [comment]
You can probably set that in a custom theme, then. It's not something I'm planning on adding to the user preferences right now.

**Comment by victorel-petrovich** [comment]
So, in my caret (custom) theme, I modified the editor properties to read: 
``` 
"editor": {
    "background-color": "white",
    "color": "black",
     "line-height": "3"
  },
```
 But that line-height addition  takes no effect. What am I missing?

**Comment by thomaswilburn** [comment]
I don't know, honestly. We expose `editor` as a global, have you tried following the Ace team's advice on the console?

**Comment by victorel-petrovich** [comment]
" We expose editor as a global, have you tried following the Ace team's advice on the console?" -- I don't know how to do that  :/

**Comment by thomaswilburn** [comment]
Go to chrome://flags, set the option to be able to debug packaged apps, and then right-click on Caret and choose "Inspect element" to open the dev tools. From there you can run code at the console to test it.

**Comment by victorel-petrovich** [comment]
I set the new flag, opened the "insp. element", but I've no idea where I can run code at the console. I just don't have the needed knowledge. Maybe someone else will be able to do that. 

But thanks for trying to help
