### ISSUE TITLE
question "Ace handles keybindings a little differently now"

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#341]
A recent commit titled:
`Ace handles keybindings a little differently now`

Is there anything I need to be aware of about the change,
since I have custom keybindings?

**Comment by thomaswilburn** [comment]
I did some quick tests, and the code in that commit should adequately cover the new arrangement of Ace's commandKeyBinding object for custom bindings. That said, if you see any odd behavior, please bug it for me so I can investigate. The most likely problem would be Ace refusing to unbind its own keys in favor of your own, but so far I haven't seen this.
