### ISSUE TITLE
CFML syntax highlighting issue

### ISSUE THREAD

**Issue by thdoan** [thomaswilburn/Caret#343]
It's awesome that Caret supports syntax highlighting for ColdFusion, but it's not working when the CFML snippet is inside a JS script tag, e.g.:

```
<script>
<!--- ColdFusion comment --->
<cfif 1>
alert(1);
</cfif>
</script>
```

Both the CF comment and the `cfif` tag are not highlighted correctly.

**Comment by thomaswilburn** [comment]
This is a problem with Ace, and not something I can fix. Please file a bug upstream, and I'll pull when they fix.

**Comment by thdoan** [comment]
@thomaswilburn [Ace PR #2626](https://github.com/ajaxorg/ace/pull/2626) fixes this issue.
