### ISSUE TITLE
Add Custom Theme

### ISSUE THREAD

**Issue by wilcorrea** [thomaswilburn/Caret#347]
There any way of import a theme customized to extension installed in Chrome browser?

**Comment by thomaswilburn** [comment]
I don't understand the question. Do you have a specific theme in mind?

**Comment by wilcorrea** [comment]
Sorry, I'll explain better. The theme in question is to Ace. I have a project what use the Ace Editor what look like Netbeans sintax color to edit PHP files. I got the crx unzip and added the file into the folder, changed in config to show it in right bottom and use it as default. But I wanna know if I can do it with the app installed by store.

**Comment by thomaswilburn** [comment]
No, sorry. Because Chrome apps are not allowed to run arbitrary JS code, and Ace themes *are* arbitrary code, I can't load them. But if you can get it into Ace upstream, I'll pull it in.
