### ISSUE TITLE
`Ctrl-F` and `Ctrl-H` work similarly

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#350]
>acer c720 chromebook
>chromeos 41.0.2272.89
>Caret 1.4.40

`Ctrl-F` opens the `Find` dialog.
`Ctrl-H` opens the `Find` along with the `Replace` dialog.

Both `Ctrl-F` and `Ctrl-H` will *toggle* between `Find` and `Find/Replace`.

I would like `Ctrl-F` to open the `Find/Replace` dialog and remap `Ctrl-H` for something more useful.

This works to remap `Ctrl-F` to `Find/Replace`
```"Ctrl-F": { "command": "ace:command", "argument": "replace" },```

And this *example* will then successfully remap `Ctrl-H`
```"Ctrl-H": { "command": "session:revert-file" },```
Note: I used `Revert` as an *example* as it was the first unmapped item I found.

**BUT** the keyboard shortcuts next to `Find` and `Find/Replace` in the `Edit` menu are **NOT** changed.

Also... the following **fails** to disable `Ctrl-H` shortcut
```"Ctrl-H": { "ace": "null" },```

**Comment by thomaswilburn** [comment]
The fact that the keyboard shortcuts don't change in the menu is a bug. The disable is not--you need to set the whole property to `null` in order to disable it. An object containing a null is not a false-y property.

**Comment by broomdodger** [comment]
>you need to set the whole property to `null` in order to disable it.

Please explain and give an example.

**Comment by thomaswilburn** [comment]
`"Ctrl-H": null`

**Comment by broomdodger** [comment]
>`"Ctrl-H": null`
I tried that and it did not work.

**Comment by thomaswilburn** [comment]
I'm not sure that's as intended. I'll take a look when I get a chance.

**Comment by thomaswilburn** [comment]
Okay, the menu and the key bindings look in two different places for where they pull information, and as a result, the menu still sees commands even though they've been unbound. This is fixable, but it will take a little while. I'll also try to fix the behavior for unbinding keys, because they should accept a null value to unbind them completely. In the meantime, "null" does no harm.

**Comment by broomdodger** [comment]
A recent commit titled:
`Ace handles keybindings a little differently now`
Did that ace change have anything to do with either bug #350 or #351 ?

**Comment by thomaswilburn** [comment]
I don't think it actually changed it very much. I think it's more that it drew attention to the fact that Caret has never handled this particularly well.

Ace has keyboard handlers that actually parse and issue commands on input. We've gotten better at interfacing these, but they are missing some basic functionality. For example, you can bind a key, but there's no method to unbind a key, so Caret has always just deleted these from the hash manually (not great for performance, but that's not a huge issue here).

The menu system is older, and didn't necessarily keep up with the improvements that were made to Caret's keyboard code, both to handle Ace updates and also just to provide better key handling for our own events. As a result, it based its hint lookup on my older, inadequate understanding of how Ace tracked keys. That technical debt finally caught up with us when you noticed that remappings did not get visually applied (and some keys were shown with mappings that didn't exist).
