### ISSUE TITLE
Edit > Select Word shortcut fails

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#351]
>acer c720 chromebook
>chromeos 41.0.2272.89
>Caret 1.4.40

The `Edit` menu item `Select Word` works, but the keyboard shortcut does not:
```Select Word  Ctrl-Alt-Right```

I can *remap* it and it then works:
```"Ctrl-Alt-Right": { "command": "ace:command", "argument": "selectMoreAfter" },```

**Comment by thomaswilburn** [comment]
Doesn't Ctrl-Alt-Right mean something on Chrome OS? I don't have my Chromebook with me, but I think I remember that being end of line or something. Anyway, I'll take a look.

**Comment by broomdodger** [comment]
>Doesn't Ctrl-Alt-Right mean something on Chrome OS?

Not that I know, and I just checked the `Ctrl-Alt-?` keymap.
Hmmm, I just tried to use `Settings > Reset > Keyboard` and it did not work as expected. Should it reset all keymaps to the default?

These are keymaps I know that are specific to chromebook:
```
Ctrl-Alt-? = KEYMAP
Search-. = Insert (toggle insert/overwrite mode)
Search-Up = PageUp
Search-Down = PageDown
Search-Left = Home
Search-Right = End
Alt-Up = PageUp
Alt-Down = PageDown
Ctrl-Alt-Up = Home
Ctrl-Alt-Down = End
```
These keys remap in Caret on chromeos,
previously some did not,
but as chromeos updates they were fixed.
```
"Alt-Shift-Space": "null",
"Alt-Space": "null",
"Ctrl-Alt-Shift-Space": "null",
"Ctrl-Alt-Space": "null",
"Ctrl-Shift-Space": "null",
"Ctrl-Space": "null",
"Shift-Space": "null",
```
These do not remap in Caret on chromeos:
```
"Ctrl-Shift-U": "null", // chromeos NO unicode prefix
```

**Comment by thomaswilburn** [comment]
I think this was a bug caused by the old menu labeling system--there wasn't actually a bound shortcut for that item, it only showed up because we were adding hints based on an obsolete data structure. After the fix for #350, a shortcut no longer appears next to this item.

**Comment by broomdodger** [comment]
I have changed some items in `Settings > Menus`
Specifically, the `Edit` menu was getting very long,
I moved some items to the `Tools` menu
where they also seemed more appropriate.
 
Will I need to start from the defaults and re-edit the `Menus` and `Keyboard`

**Comment by thomaswilburn** [comment]
These changes should be transparent to users and will work with existing config files--they are all behind the scenes. I've uploaded 1.4.41 with these changes to the beta version, and you can test them there, if you want.
