### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by thomaswilburn** [thomaswilburn/Caret#352]
This came up again over the weekend, and I think it'd be a nice thing to have. Normally, Ace themes are written in JavaScript, which means we can't hot-load them in a Chrome App. However, behind the scenes, it's just a CSS file that's been wrapped in an AMD module, with a little bit of JS shim applied. There's no good reason why we can't develop that. My current plan is to add a CSS template, a shim module for Ace that registers itself on startup, and a new config JSON file that gets jammed into the template. Something like this:

```json
//theme.json
{
  "Constant": {
    "selector": ".ace_constant",
    "color": "red",
    "background": "black",
    "font-style": "italic"
  }
}
```

That's parsed into an array and passed to:

```css
{{#styles}}
.ace-caret {{selector}} {
  color: {{color}}; //nice thing about CSS, it'll get thrown away if invalid
  background: {{background}};
}
{{/styles}}
```

**Comment by victorel-petrovich** [comment]
Hi @thomaswilburn , I have edited the Custom Theme  (`theme.json`) but after I save it, some changes there also affect other themes (I think all). I suspect that's not intended, is it?

More specifically,  I modified the `//keywords` part (line 134 in default file) from:
```
 //keywords
    ".ace_storage, .ace_keyword, .ace_meta.ace_tag": {
      "color": "rgb(147, 15, 128)"
    },
```
to:
```
//keywords
    ".ace_storage, .ace_keyword, .ace_meta.ace_tag": {
      "color": "rgb(147, 15, 128)" , "font-weight":"bold" 
    },
``` 
But then this addition also make bold, for instance, all html tags in all other themes, and the behaviour is normal again when I delete that font weight addition. 

Do you get the same thing?

**Comment by thomaswilburn** [comment]
Interesting! I guess I'm not scoping that the way I wanted to. I'll admit I didn't test this very much, so I'll take a look.
