### ISSUE TITLE
Force syntax highlighting for certain file types

### ISSUE THREAD

**Issue by charukiewicz** [thomaswilburn/Caret#354]
I am using Caret for working on a CakePHP project.  I really like the editor as it has many of the features of Sublime and is also extremely fast.  The one issue I am coming across at the moment is syntax highlighting in CakePHP's front end files.  Instead of the typical .html or .php syntax one might expect, they use their own .ctp extension.  This results in no highlighting at all (in the Monokai theme all the text is just white).

If I rename one of these files to .html and reopen it, the syntax highlighing is 100% correct.  So to solve this issue, the only thing that needs to be possible is the ability to override a particular type of file and treat it as a different file type for syntax highlighting purposes.

I envision this feature best taking the form of a per file type global setting in `user.json`, as it would be annoying to have to set the syntax override for every new file that one opens.

**Comment by thomaswilburn** [comment]
I think the easier thing to do would just be to add .ctp to the HTML highlighting extensions, personally.

**Comment by charukiewicz** [comment]
That would work too.  Where does that get set right now?

**Comment by thomaswilburn** [comment]
It's in the ace.json file, which is not normally exposed to users, although I guess there's no reason why it shouldn't be. You can open it yourself from the app command line (Ctrl-.) via this command: `session:open-settings-file ace`.

**Comment by charukiewicz** [comment]
Awesome!  Thank you.
