### ISSUE TITLE
caret 1.5.0 no menus

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#355]
acer c720 chromebook
chromeos 41.0.2272.89
Caret 1.5.0

Caret updated and now there are no menus and the 3 buttons on the upper right are not functional.

I tried the emergency reset, uninstall, reinstall, more emergency reset and still the Caret window opens but no menus and buttons not functional.

Help :)

**Comment by thomaswilburn** [comment]
If you open the console, can you give me an error?

**Comment by broomdodger** [comment]
Is the right place: extensions > caret > main.html >console

Uncaught Error: Load timeout for modules: util/template!templates/theme.css_unnormalized16,util/template!templates/theme.css,util/text!templates/theme.css
http://requirejs.org/docs/errors.html#timeout

Also I disabled all extensions, well I do not have many.

**Comment by thomaswilburn** [comment]
Yep, that's the right place. Looks like I screwed something up in the build process, fixing now.

**Comment by thomaswilburn** [comment]
Fixed in ce955db5c2d6d9859448bede0212f2f1ef49ba23

**Comment by broomdodger** [comment]
ok I download the crx from your site
caret 1.5.1 menus are there and working

**Comment by broomdodger** [comment]
How long does it take to get to the chrome store?

**Comment by thomaswilburn** [comment]
It's still publishing now, but usually it makes its way out within 10 minutes or so. I've started listing it as an inline install, which it says may delay the process a little. I'd expect it to be done by midnight PDT.

**Comment by broomdodger** [comment]
Question
The settings menu has `check for updates`
Does it do anything?
I have clicked it in the past but nothing seems to happen.

**Comment by thomaswilburn** [comment]
It will trigger a notification if the current channel (store or beta) has an updated version. It doesn't currently show a notification if there is no update, but it probably should.

**Comment by broomdodger** [comment]
Thank you.

**Comment by thomaswilburn** [comment]
The update should be available in the Chrome store now. Thanks for your patience.

**Comment by broomdodger** [comment]
I got it and it seems to be working.
Thank you, very quick!

**Comment by broomdodger** [comment]
restored my user prefs, keyboard and menus
all seems good.
Great editor.
Superb support.

**Comment by broomdodger** [comment]
`Wildly eccentric`
funny :)

**Comment by broomdodger** [comment]
It looks like **both** are now ok
```
"Ctrl-H": "null",
"Ctrl-H": null,
```

**Comment by thomaswilburn** [comment]
I changed it to accept false-y values like null because that seemed cleaner to me. Using `"null"` sends a message out (but nothing listens for that message, so nothing happens), whereas `null` will actually decline to send any messages--it just wipes out any existing key bindings for that particular combo.
