### ISSUE TITLE
outline / ctags?

### ISSUE THREAD

**Issue by ipstone** [thomaswilburn/Caret#357]
is it possible to have outlines (like eclipse) or ctags (vim etc) in Caret? 
thanks!

**Comment by thomaswilburn** [comment]
It is probably possible, but I think this is the kind of thing you'd want to build using the plugin API. It's not a planned feature for Caret at this time.

**Comment by ipstone** [comment]
Thanks, sorry as a newbie here, where is the info for the plugin API - refers to component in ACE, or we have a plugin archetecture for Caret already? thanks

**Comment by thomaswilburn** [comment]
It's an infrastructure built into Caret, not into Ace (although it does allow you to talk to Ace in a limited way). Check out the [relevant section of the wiki](https://github.com/thomaswilburn/Caret/wiki/Commands) for more info. 

Note that the plugin API is largely untested and incomplete. That's part of why I keep encouraging people to use it: the only way I'm going to find out what it's missing is for people to try (and fail) to build something on top of it.

**Comment by ipstone** [comment]
Thanks! Caret is the most impressive editor I saw for years on chrome. Will play around with plugins API and configuration.
