### ISSUE TITLE
remove blank lines within a range

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#358]
remove blank lines within a range

I often get files with many lines that have 1 or more blank lines between.

Using the ace regex does not work:
```
Find "^$\n"
Replace ""
```
And I have not found a way to do it other than selecting each instance and delete.

Any suggestions?

**Comment by thomaswilburn** [comment]
Hm, no, I don't have any good advice for that right now. I think this would probably need to get folded into the long-standing find/replace enhancement (#194).
