### ISSUE TITLE
command listing

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#367]
acer c720 chromebook
ChromeOS 41.0.2272.102
Caret 1.5.1

\+ `chrome://extensions/`
\+ Caret `main.html`
\+ select `Console`
\+ type `editor.commands.commands`

Clicking each disclosure triangle I can see the Caret command and its key binding.
Is there a way to get the command listing in a flat file?

**Comment by thomaswilburn** [comment]
Those aren't Caret commands, they're built into Ace. Other than actually reading the Ace source ([starting here maybe](https://github.com/ajaxorg/ace/blob/master/lib/ace/commands/default_commands.js)), I don't think there's a listing.

**Comment by broomdodger** [comment]
Is there a list of all Caret commands?
Other than `Settings` > `Keyboard` and `Settings` > `Menus`

**Comment by thomaswilburn** [comment]
There's one in the wiki.

**Comment by broomdodger** [comment]
I like knowing things like:
In the find dialog:
Alt-B = bound (Whole Word)
Alt-C = Case Sensitive
Alt-R = RegExp
