### ISSUE TITLE
Select Paragraph weird

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#369]
> acer c720 chromebook
> ChromeOS 41.0.2272.102
> Caret 1.5.1

Caret > Edit > Select Line
Each use of `Select Line` adds a line to the selection (good)

Caret > Edit > Select Paragraph (aka sublime:expand-to-paragraph)
+ the first use of `Select Paragraph` selects the current paragraph (good)
+ the second use of `Select Paragraph` adds the next paragraph to the selection (good)
+ the third and subsequent use of `Select Paragraph` selects a moving set of 2 paragraphs (weird)
  rather than adding more paragraphs to the selection

**Comment by thomaswilburn** [comment]
This appears to be a bug higher upstream in Ace--we call getSelection() each time, but it only actually contains selection range objects correctly if there are multiple cursors or selections. You may want to take this up with them, and feel free to point them at Caret's code (js/acebindings.js) as a test case.
