### ISSUE TITLE
Go to Line bug

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#370]
`Tools` > `Go to Line` bug

Go To: [:5  ] will go to line 5
Go To: [:2  ] will go to line 2
Go To: [:1  ] does nothing
Go To: [:0  ] will go to line 1

Similarly...
`Tools` > `Go to Search`
will **not** find anything in line 1
but it does work for other lines

**Comment by thomaswilburn** [comment]
Bill, thanks for filing these bugs lately. Just a warning, the new quarter is about to start, and I'm going to be under a pretty heavy workload, so I don't know when I'll get around to fixing them. But I have seen them, and will work them in when I get a chance.

**Comment by broomdodger** [comment]
Thank you Thomas
I use Caret every day... it works great.
Only a few **minor** things to work around.
Caret makes the chromebook truly functional for me.
