### ISSUE TITLE
Javascript autocomplete in version: 1.7.103 (Google App Store)

### ISSUE THREAD

**Issue by postacik** [thomaswilburn/Caret#372]
Suppose I have file (a.js) with my functions in it.

In file b.js I write code which uses functions in a.js.

Can autocomplete give information about functions in a.js while working in b.js?

**Comment by thomaswilburn** [comment]
Nope. We don't support that.

**Comment by thomaswilburn** [comment]
(Also, that's not the current Caret version, so I don't know if you've got the right software.)

**Comment by postacik** [comment]
There is a project called Carret-T which is now on version 1.7.103 on Google App Store.

The about box points to you as the author but I've now noticed that it's been modified by user sevin7676.

Sorry for placing the question on the wrong project site.
