### ISSUE TITLE
Request "GitGutter" like functionality

### ISSUE THREAD

**Issue by craig552uk** [thomaswilburn/Caret#374]
The JsLint notifications in the gutter are really nice. 
It's be really useful to see git differences in the gutter too, similar to the GitGutter plugin for Sublime. https://github.com/jisaacks/GitGutter

**Comment by thomaswilburn** [comment]
Sounds like a great thing to do over the plugin API. But we can't get Git information from the command line, and we won't be building it directly into Caret.
