### ISSUE TITLE
Add asciidoc mode

### ISSUE THREAD

**Issue by victorel-petrovich** [thomaswilburn/Caret#375]

**Comment by thomaswilburn** [comment]
Sure, I'll turn that on. You can also add it yourself if you edit the ace.json file. I don't talk much about this, but it's easy to add a menu item that lets you edit the ace settings file (it's basically the same as the menu items that edit the other settings).

**Comment by thomaswilburn** [comment]
Fixed in f45c5e8

**Comment by victorel-petrovich** [comment]
Thanks for the fast answer and fix! 

But I have the app from Chrome webstore, thus I don't know how to make any modifications to the application source files. And if I could, won't such personal modification vanish at the next autoupdate of the app?

So, would be nice if you could provide that button to edit ace settings, provided they will stay there from update to update (or perhaps include them in User Preferences?).

**Comment by thomaswilburn** [comment]
Victorel,

Updates you make are never destroyed when I upgrade Caret in the store--the changes I make are to the defaults files, and your changes are merged in over them or replace them completely. 

So, for example, if you were to use the Settings->Menus menu item to open up that configuration, you can find the lines that enable configuration editing (including, of course, the menu you just used). They should look something like this:

```json
      { "label": "menuUserPrefs", "command": "session:open-settings-file", "argument": "user" },
      { "label": "menuKeyboard", "command": "session:open-settings-file", "argument": "keys" },
      { "label": "menuMenus", "command": "session:open-settings-file", "argument": "menus" },
      { "label": "menuAPI", "command": "session:open-settings-file", "argument": "api" },
      { "label": "menuTheme", "command": "session:open-settings-file", "argument": "theme" },
```

If you were to change these, you could easily add a line that opens the `ace.json` file just by altering the "argument" passed to the "session:open-settings-file" command (almost everything in Caret is just commands and arguments). So to open and edit the Ace configuration, just add this:

```
      { "label": "Ace settings (syntax/themes)", "command": "session:open-settings-file", "argument": "ace" },
```

Once you open that file, it's pretty easy to understand. You'll need to know the Ace syntax mode name, but you can look those up in its repo, or just ask and I'll happily help you out.

As I said, your changes will persist (in fact, they'll be synchronized across all connected Chrome accounts), but sometimes I'll make changes to `ace.json` from the upgrade side. So it's often a good idea after an upgrade to check the defaults file, and either re-copy your changes into it or copy the new default settings into your custom version.

**Comment by victorel-petrovich** [comment]
Oh, thank you very much ! It turns out, it's much simpler than I thought would be. I would have probably figured it out myself if I thought a few minutes more, but your answer came so fast.

So, it worked; it highlights nice. (the label does not appear in the menu at the bottom with all modes,  but that's irrelevant for me).

Now I don't have to use another editor just to be able to write asciidoc!
