### ISSUE TITLE
Overwriting file with zero-bytes

### ISSUE THREAD

**Issue by waxim** [thomaswilburn/Caret#377]
I'm still trying to narrow this down but I'm adding this viability. Intermittently I am getting caret sending a zero-byte file overwriting the original, it seems to unload the file from caret also (though it leave the tab open but empty) which means an undo wont work. __Essentially the file is lost.__

My hunch is that its chrome unloading the tab to preserve memory, so I'm thinking an internal swap (that isn't localstorage like current sessions) for caret keeping .tmp files of the last few open tabs with a way to recover from .tmp and an 'auto-save' interval. 

I'm not sure its possible but it might also be good to ensure caret can't write zero (maybe with a flag in settings to turn it on) so if the data passed is empty caret will reject the change.

**Comment by thomaswilburn** [comment]
Is this happening in any particular circumstances? For example, are you editing a file on a remote file system? Does this happen when you turn off auto-reload?

**Comment by waxim** [comment]
Yes, I am editing the file over SFTP mounted as a drive.

**Comment by thomaswilburn** [comment]
Okay. I have had a couple of similar bugs reported (such as #364), but I can't duplicate myself. If you can help me get a replication of this bug, I'm happy to fix, but it seems to crop up in particular when people are using unreliable remote filesystems, and I'm not sure it's actually in my purview.

I'm pretty sure the problem is _not_ Chrome freeing memory for the tab, because Caret doesn't work that way--it doesn't release inactive tabs the way the browser does, it always keeps them in memory.

**Comment by waxim** [comment]
I am on a Chromebook, so when I say 'Chrome' i mean ChromeOS, which may unload data from an application when a memory limit is reached, I see this happen in other apps too. 

It could be the remote FS. I am poking around in the app and will try and add some logs to better see whats happening. I can see that on window focus it 'checks' the file and reloads it, so if the SFTP connection did something funny to the file that would 'lose' the data loaded in the window, so I have disabled that for now. That way I'll be able to see if the file goes zero and Caret keeps the data then it would be the remote for sure.

I'll keep the ticket updated.

**Comment by thomaswilburn** [comment]
ChromeOS does not unload memory from Caret. It would break the JavaScript memory model if they did. They may page us out to swap, but that's true of every OS, and it would happen for all of Caret when it happens, not just an individual tab. After all, Chrome doesn't know anything about Caret tabs, they're just another variable to it.

I suspect it's the remote file system conflicting with auto-reloads. That's unfortunate, but if the SFTP system hands us an empty file, Caret is behaving properly, and it's a bug with the remote FS plugin or the way that Chrome interacts with it.

**Comment by waxim** [comment]
I've been using Caret for a week or so now with auto-reload off and I've had no problems so I think you're correct in your suspicion or it being the remote FS, maybe the app just needs a head up/warning for those using a mounted file system that they should disable auto-reload?

**Comment by thomaswilburn** [comment]
I'll add a note to the wiki.
