### ISSUE TITLE
cancel instead of save shows "object: Object" msgbox

### ISSUE THREAD

**Issue by markhu** [thomaswilburn/Caret#378]
to repro: (v.1.5.2)
1. open/create a file; add/change a few chars
2. get the file dialog, i.e. save or save-as or close or exit
3. cancel or ESC out of the file dialog
4. note odd msgbox

**Comment by thomaswilburn** [comment]
Good call, I'll take a look.

**Comment by thomaswilburn** [comment]
This should be fixed as of v1.5.3
