### ISSUE TITLE
double clicking to select words fails

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#380]
>acer c720 chromebook
>ChromeOS 42.0.2311.87
>Caret 1.5.3

double clicking to select words

I do not know how long it has been happening,
I think there was a time it worked correctly,
double clicking to select a word OFTEN fails.

Double clicking to select words does WORK in all other apps.

**Comment by thomaswilburn** [comment]
This still works for me, and nothing I've done would have changed it in the last few releases. I'll check on my Samsung Chromebook tonight, but I wonder if this is an Acer-specific bug.

**Comment by broomdodger** [comment]
>acer c720 chromebook
>ChromeOS 42.0.2311.134
>Caret 1.5.3

The  **ChromeOS 42.0.2311.134** update **MAY** have fixed the problem `double clicking to select words`.
I say **MAY** because there have also been updates to extensions.

**Comment by broomdodger** [comment]
>acer c720 chromebook
>ChromeOS 42.0.2311.153
>Caret 1.5.4

Another ChromeOS update today.
The problem has NOT returned.
Double clicking words or paragraphs WORKS.
