### ISSUE TITLE
Bug: "To Lowercase" keyboard shortcut deletes selection.

### ISSUE THREAD

**Issue by victorel-petrovich** [thomaswilburn/Caret#381]
Environment: Samsung Chromebook, Chrome OS

When I select a capitalized (uppercase): WORD, and press `ctrl-shift-u`, the WORD gets replaced with   
letter "u" underlined.  Then, if I press `spacebar`, it disappears completely, while if I press another letter, it continues as underlined.

**Comment by thomaswilburn** [comment]
It's not a bug, it's a result of how Chrome handles Unicode input.

**Comment by victorel-petrovich** [comment]
Ups, sorry for mislabeling :). So, nothing to be done about it?

**Comment by thomaswilburn** [comment]
Yeah, we should probably change the shortcut. But I think it's platform specific, so I've just never gotten around to it.
