### ISSUE TITLE
Shortcut to remove Line

### ISSUE THREAD

**Issue by anashashmi** [thomaswilburn/Caret#382]
I am trying to create a keyboard shortcut to remove an entire line, similar to Ace's native Ctrl-D.  I want to use Ctrl-T for removing a line because Ctrl-D is already occupied by another feature.

I tried finding a command for removeLines but could not find it in Command Palette.  If I could find it, maybe I could create my own shortcut in User Prefs. 

So I tried to find someplace where I could create my own custom function, and got lost.  My final request is this: Can you add a commandLine for ace:removeLines? If not, could you tell me how to adjust the API.json so that I may?

**Comment by thomaswilburn** [comment]
You don't need to add it to the API JSON. If it's an Ace command, you can just add it to the keyboard config like the other Ace commands.

-----Original Message-----

**Comment by anashashmi** [comment]
I gave it another try and succeeded.

Added lines to keys.json:
```
"Ctrl-T": {
        "ace": "removeline"
    },

```
