### ISSUE TITLE
Text cursor position bug on Samsung Chromebook

### ISSUE THREAD

**Issue by zohead** [thomaswilburn/Caret#384]
Hi:

I really love Caret text editor on Windows Chrome browser, but the text cursor position is incorrect on my Samsung ARM Chromebook, cursor always far from ending of the line, and if I enter more text, the cursor position keeps getting far from ending of the line.

So I can't select text on my Samsung Chromebook, if I search text, the selected text is always incorrect, while this never happens on Windows Chrome browser.

I have tested this on Samsung chromebook with lastest Chrome OS version 41 and 42.

Thanks

**Comment by thomaswilburn** [comment]
This sounds like a problem with a non-monospaced font, which is not supported by Ace.

**Comment by zohead** [comment]
I have thinked about this before, tried some fonts but doesn't work,
I'll try more fonts on my Samsung Chromebook.
Really thanks

**Comment by zohead** [comment]
Tried almost every monospace font on my Samsung Chromebook,
still no luck at all -_-#

**Comment by thomaswilburn** [comment]
I can't reproduce this on an ARM Chromebook, v.42. Can you reset your user preferences in Caret to make sure that nothing there is causing this issue?

**Comment by zohead** [comment]
The cursor position bug is gone after I install a custom "SimSun" font to my Samsung Chromebook (use SimSun font in Caret user preference).
Reset user preference doesn't help.

While there is another bug with Chrome OS IME:
If I enter some chinese words with Chrome OS built-in Chinese Pinyin Input Method, 
there is a great chance that the last character of setence I entered is eaten by Caret,
this is really weird, eg:

I enter chinese words "我们“ in Caret, there is a great chance that "我" is only showed in Caret, the last character ”们“ is eaten.

And this never happen if I use Chinese IME to enter english characters.
I can't use Ctrl+Space key to switch IME method in Caret, maybe this is related with "autocomplete" (already turned off in user preference)?

**Comment by thomaswilburn** [comment]
I don't know very much about how Ace handles Chinese input, unfortunately. This still sounds like a problem with Ace upstream, and they'll have to fix it there.
