### ISSUE TITLE
Project tree doesn't scroll

### ISSUE THREAD

**Issue by blitzrk** [thomaswilburn/Caret#386]
When I expand a large directory in the project sidebar, no (vertical) scroll bar appears and I can't scroll with the trackpad or touchscreen either. However, a horizontal scroll bar will show up and work if files have very long names.

Also, the bottom status bar (where the line/col #s and syntax reside) appears to move down out of view when the tree becomes too tall. I did my best to screenshot this behavior.
![screenshot 2015-04-27 at 10 49 02 pm - edited](https://cloud.githubusercontent.com/assets/4293921/7362987/cc772cdc-ed2f-11e4-85cc-b925016f3240.png)

This is using a clean build on ChromeOS with a Chromebook Pixel 2015 (dev channel).

**Comment by thomaswilburn** [comment]
Interesting, and shouldn't be something we'd see in a flexbox app like this. I haven't seen this on stable, do you have any idea what might cause it?

**Comment by thomaswilburn** [comment]
Okay, this definitely isn't happening on stable. If we can verify that it's a problem coming down the version pipeline, I'll re-open, but otherwise I'm assuming it's a temporary regression in 44.

**Comment by gregjor** [comment]
I'm seeing this in the latest version 1.5.6 from the Google web store, the same version is linked from the Caret page. Is building from source the fix?

**Comment by thomaswilburn** [comment]
No, the source is going to be identical. What's your Chrome version?

**Comment by gregjor** [comment]
Version 44.0.2403.52 beta (64-bit) on OSX. Using the beta version to get the new battery saving fixes.

**Comment by thomaswilburn** [comment]
Okay, I think this is still a bug on beta. It's not showing up for me on stable. I'll check it out.

-----Original Message-----

**Comment by thomaswilburn** [comment]
I still can't replicate this on Chrome Stable. If it shows up when Beta transitions down, I'll take a look, but right now I think it's likely that this'll get fixed before that happens.
