### ISSUE TITLE
When using Vim keybindings, Page down and page up keys dont work

### ISSUE THREAD

**Issue by ShashankaNataraj** [thomaswilburn/Caret#388]
Open vim, even without insert mode, you can still do a page up and page down. In caret when I switch on vim bindings, I see that page up and page down keys dont work unless I hit an "I" and move into insert mode.

**Comment by thomaswilburn** [comment]
Vim mode is supported only in so far as Ace makes it available. I don't know anything about it beyond that, and I don't test for it.

The only idea I have is that you might try unmapping the page up and page down keys in your keys.json file.

**Comment by ShashankaNataraj** [comment]
ok will raise this issue on the ace editor page and see if I get a response. Thanks!

**Comment by ShashankaNataraj** [comment]
Hi @thomaswilburn,

Please refer to https://github.com/ajaxorg/ace/issues/2487#issuecomment-100614943 to solve this. Are you planning to move to the newer versions of ace anytime soon?

**Comment by thomaswilburn** [comment]
I try to track it pretty closely. I'll see if I can push out an update this week.

**Comment by ShashankaNataraj** [comment]
Thanks Thomas! Also, any plans on allowing plugins into caret?

**Comment by thomaswilburn** [comment]
There's already a plugin API. Check the wiki for the messages Caret accepts.
