### ISSUE TITLE
Question regarding vim mode?

### ISSUE THREAD

**Issue by TetragrammatonHermit** [thomaswilburn/Caret#389]
Now I know that the developer of caret said that he will not fix any issues, but the problem is I don't even know how to make it work. The vi emulation mode, or plugin whatever it is. Even if it does not work in full, I would not use caret without it, as vim is a part of me I can't take out. Thanks. I have attempted to read the FAQ and other areas of the wiki, as far as I was able I did not find an answer either in google, or IRC. So I came here to raise the issue, if anyone else has a quick answer for this. Appreciate it.

**Comment by TheThirdOne** [comment]
In settings/user.json,
```
  //Crazy? You might like Vim keybindings.
  "emulateVim": trues,
```
