### ISSUE TITLE
Two-file view

### ISSUE THREAD

**Issue by tlewis3348** [thomaswilburn/Caret#390]
There are many times that I am either working in two files at once or working in two different parts of one large file simultaneously (or at least in a way that requires me to be able to reference both parts at the same time).  Therefore, I would greatly appreciate it if there were a "split-screen" view to allow viewing both files simultaneously.

**Comment by thomaswilburn** [comment]
This isn't really possible right now without a major refactor, but it is one of the things that I have in mind should I ever have time for Caret 2.0.
