### ISSUE TITLE
Julia syntax highlighting

### ISSUE THREAD

**Issue by keorn** [thomaswilburn/Caret#391]
Hi, thanks for the nice editor! Is it possible to add Julia syntax highlighting? It is present in Ace from what I can see here: http://ace.c9.io/build/kitchen-sink.html .

**Comment by thomaswilburn** [comment]
Yes, I can do that. What's the usual file extension for Julia files?

**Comment by keorn** [comment]
Great, I think only *.jl is needed.

**Comment by thomaswilburn** [comment]
Julia is already enabled, actually. I'm adding the extension now, but it should have been in the menu all along.
