### ISSUE TITLE
tabs in sidebar

### ISSUE THREAD

**Issue by nilswiersma** [thomaswilburn/Caret#392]
In sublime text, you can disable the tabs on the topbar tabs and enable tabs in the sidebar. Would it be possible to add this UI feature to Caret? Thanks for making this editor!

**Comment by thomaswilburn** [comment]
This would be feasible with a flexbox tweak (and some changes to the drag/drop code), but it's not something we're going to do right away. I'd be happy to take a pull request for it, though.
