### ISSUE TITLE
move past right parenthesis

### ISSUE THREAD

**Issue by prairiedock** [thomaswilburn/Caret#394]
Is there a way to move past the nearest matching right parenthesis? If not, is there any chance we're going to get one?

(To be explicit, the function I'm looking for: seeks left for the nearest left parenthesis-- could be under the cursor right now-- and moves just past the matching right parenthesis.)

It would be useful to have this for the other brackets ("[" and "{") too, but primarily it would be useful for parentheses.

**Comment by thomaswilburn** [comment]
I don't have any plans for one. There might be a command in Ace to do it, I don't know.
