### ISSUE TITLE
How can I add the ability to open a file with Caret to the right-click menu in Windows?

### ISSUE THREAD

**Issue by tlewis3348** [thomaswilburn/Caret#398]
I would like to be able to choose to open a file with Caret from the right-click menu in Windows.  I've done this with other text editors in the past, but since Caret is a Chrome extension, I don't know what I need to do differently.  Is this even possible?

**Comment by thomaswilburn** [comment]
Sadly, Chrome will not let us do this. They were working on it at one point, but I'm not sure if there's still effort going toward it.

**Comment by tlewis3348** [comment]
Okay.  Thanks for the information!
