### ISSUE TITLE
Word wrap on spaces only

### ISSUE THREAD

**Issue by ludoo** [thomaswilburn/Caret#402]
Current Caret behaviour is to wrap a line regardless of the character at the position when the wrap occurs, which gives weird results for text (see attached screenshot).

It would be better to wrap only on spaces, maybe as a user configurable option.

Thanks a lot for your great work on this fine editor!

![screenshot 2015-06-21 at 10 06 57](https://cloud.githubusercontent.com/assets/66007/8270955/8b17f3a8-17fe-11e5-8715-8f78604c4540.png)

**Comment by thomaswilburn** [comment]
That's an Ace bug, unfortunately, not something we can fix.
