### ISSUE TITLE
Caret or Chrome? (spellcheck only works in browser not app)

### ISSUE THREAD

**Issue by isAPartyDude** [thomaswilburn/Caret#403]
I've been 'looking for a text editor with spellcheck' but there is no relevant information online because the question seems absurd to most ("Chrome handles spellcheck"). If this is true why are mispelled words not underlined in Caret (or any other text editors for chromebook). Does this have to be handled by the application? If so... There is a spellcheck ext in the sources here. Is that suppose to work to make spelling checked? If so it's not working with my Chrome Store installation of Caret, and it's a bug.
If this is just Chrome madness...well... dammit (dammit if I could get any help on this topic to save my life).

**Comment by thomaswilburn** [comment]
There is no spellcheck extension, and unfortunately Chrome does not expose spellchecking in a form that Caret can use, so it doesn't exist.
