### ISSUE TITLE
Material light colours in dark theme

### ISSUE THREAD

**Issue by grit96** [thomaswilburn/Caret#406]
Lots of the UI elements (menus, dialogues, project panel) use a light colour even when the dark theme is enabled. I think the dark colours that were previously used look better.

**Comment by thomaswilburn** [comment]
Sorry, I don't really agree. The menus in particular are way more readable on white (dialogs have always been light-themed).

**Comment by Varpie** [comment]
Sorry to bump, but I figured my "issue" is related : the "find" and "find and replace" boxes are using the same color in both light and dark theme, which is quite odd and since it stays open, more disturbing than menus.

**Comment by thomaswilburn** [comment]
We don't control those, they come in through Ace. I don't have any intention of theming them right now (the eventual goal would be to replace them, since they're not great).
