### ISSUE TITLE
Cannot install Caret from Chrome's Web Store

### ISSUE THREAD

**Issue by beauchef** [thomaswilburn/Caret#408]
I don't know if this is the place to raise the issue, but I cannot install Caret from the Web Store. I get "Package is invalid. Details: 'Could not unzip extension'." I have Caret installed on my Chromebook, but I don't know if something has changed in the way you package the ZIP file (maybe there was a change in the Grunt compress plugin?), but I can't install it on my new Chromebox.

**Comment by thomaswilburn** [comment]
Well, you're not the only one. I'll try to upload a new .zip file, but I don't think I'm in control of that.

**Comment by thomaswilburn** [comment]
Weird, it seems to have gotten corrupted (I don't remember pushing on the 30th, but that's when it started.) Regardless, I've uploaded 1.5.12 as a new .zip, and it seems okay now.

**Comment by beauchef** [comment]
Yes, it works fine now, thank you!
