### ISSUE TITLE
cursor position issues

### ISSUE THREAD

**Issue by BrotherBloat** [thomaswilburn/Caret#409]
Hi,

It seems like the cursor is mis-aligned with the text in the current version. If I double click a word, it highlights another one and the further down the line I am, the more discrepancy there is between where the cursor shows that it is and where it actually is.

Below are two examples, with 'as' selected and 'desc' selected in the snippet of code. The theme seems to have no relation to this bug.

I read that this used to be a common issue in old versions of Chrome, but I'm running it on the most up to date v 43 of Chrome OS stable.

Cheers!
Mike

![as selected](https://cloud.githubusercontent.com/assets/4629734/8521997/791a9f2c-23e1-11e5-8437-9ffe7ce96b9c.png)
![desc selected](https://cloud.githubusercontent.com/assets/4629734/8521998/791e91cc-23e1-11e5-8a74-93787d5489d4.png)

**Comment by thomaswilburn** [comment]
You're using a variable width font. Caret is only compatible with monospaced fonts.

**Comment by BrotherBloat** [comment]
Thomas,
I'm an idiot - apologies!
Thanks for the solution!
M.
