### ISSUE TITLE
File encoding gets changed

### ISSUE THREAD

**Issue by trimzulu** [thomaswilburn/Caret#410]
I have a file I'm used to editing in Notepad++ that is encoded as "UCS-2 Little Endian". If I open the file in Caret and simply save the encoding changes to ANSI.

**Comment by thomaswilburn** [comment]
It shouldn't be ANSI, it should be UTF-8. Regardless, Chrome OS doesn't really give us much control over the encoding for string-based file writes. We'd have to create our own binary blob for the encoding, and I don't have any plans to do that right now.
