### ISSUE TITLE
Save As mouseover doesn't change

### ISSUE THREAD

**Issue by jimmypete** [thomaswilburn/Caret#412]
Howdy, when I do a "save as" the file name does not change in the mouseover.  That is the only way I know to actually see the file that is open once I do a "save as" because my file names are longer than the static display on the tab (I frequently only change the end of the file names).  So when I go to check the file that is open by doing a mouseover, the flyout shows the original file name, not the new one that I have done a "save as" on.  

Excellent app - thank you!

**Comment by thomaswilburn** [comment]
I'll take a look. Getting the full path for hover is an async operation, and parts of it may be buggy in edge cases like this.
