### ISSUE TITLE
ignoredFIles regex. How it works?

### ISSUE THREAD

**Issue by kresli** [thomaswilburn/Caret#415]
I tried following `"ignoreFiles": ["jspm_packages", "node_modules"],` but with no luck. In the comment yo u saying to use regex. But how? Thanks

**Comment by thomaswilburn** [comment]
It should be a single string, and it gets fed to the JS RegExp constructor directly. So, for example, your list above would be passed in as `"ignoreFiles": "jspm_packages|node_modules"`.

**Comment by kresli** [comment]
Thanks for so quick response. Works like charms. Thanks
