### ISSUE TITLE
Caret strips the BOM from some files

### ISSUE THREAD

**Issue by James-Ko** [thomaswilburn/Caret#416]
When I'm opening a file, Caret automatically appends a UTF-8 [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark), EF BB BF, to the beginning of the file. I'm contributing to a project and this is a problem, because every time that happens I have to revert the changes and switch to Mousepad on Linux most of the time. Can you add an option in user.json to not do this?

**Comment by James-Ko** [comment]
Update: it looks like it's stripping the BOM from the file, actually. This isn't as bad, but can there be an option to just not touch the BOM at all?

**Comment by thomaswilburn** [comment]
I don't have any control over the format that it creates when I call Chrome's file API, unless I were to manually construct the Unicode buffer from scratch (which I'm not going to do, but I'll happily take a pull request for it).
