### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by wiz** [thomaswilburn/Caret#417]
Is it possible to load a font file and make it stay between extension updates?

There's a `fontFamily` setting, but ChromeOS still doesn't have a straight way to add system fonts. I've succeeded in sideloading an [OTF font](https://github.com/tonsky/FiraCode/releases) with terminal and adding a CSS `@font-face` rule but wonder if there's a better way.

**Comment by thomaswilburn** [comment]
Not that I'm aware of, no.

**Comment by ydawei** [comment]
@wiz Is it possible for you to specify how to do that?

**Comment by wiz** [comment]
@ydawei I haven't did that in a while, but it goes like that: https://gist.github.com/wiz/1eb395712f1b00c689dc

**Comment by fastcat** [comment]
https://github.com/wernight/powerline-web-fonts shows how to do this -- if you provide a place to provide custom CSS, folks can use that to get their custom fonts loaded

Can this be reopened, or is it better to file a new issue?
