### ISSUE TITLE
No "delete line" command?

### ISSUE THREAD

**Issue by thdoan** [thomaswilburn/Caret#419]
I'm not sure whether this is an Ace limitation or an omission, but I was not able to find a command to delete the entire line.

**Comment by thomaswilburn** [comment]
I'm not sure what it is right now, but I guarantee that Ace has a `deleteline` or similar command.

**Comment by thomaswilburn** [comment]
Or not, I guess? Anyway, I'm not going to add it right now, but I'd be happy to take a pull request.

**Comment by thdoan** [comment]
OK I will submit a new issue on the Ace GitHub if they really don't have a `deleteline` command.

**Comment by tastyminerals** [comment]
When I looked up `keys.json` in search of line delete keys and didn't find them, I couldn't believe it. This is like a **must have** feature for just any editor.
