### ISSUE TITLE
Feature suggestion: show Go To when you click on 1:1 in status bar

### ISSUE THREAD

**Issue by thdoan** [thomaswilburn/Caret#420]
I like how you can click on the language and theme in the status bar to quickly change them. It would be cool if you could extend this to the position (e.g., 1:1) in the left corner as well. When you click on the position, the Go To Line dialog should pop up, or maybe you can show an input field above the position for the user to jump directly to another position within the document.

**Comment by thomaswilburn** [comment]
Pretty good idea, although I still think Ctrl-G is just way easier. I'll think about it.

**Comment by thdoan** [comment]
Ctrl-G is what a power user would probably do, but for beginners or "visual" mouse lovers, being able to click on 1:1 would be nice training wheels until they get hooked on keyboard combos :-)

**Comment by thomaswilburn** [comment]
I see what you're saying, but honestly I think most newbies just go to the menus. You wouldn't believe the number of bugs I get where people can't switch syntax because they don't even look at the bottom bar. It's invisible to them.
