### ISSUE TITLE
Feature suggestion: expose Ace API for custom commands

### ISSUE THREAD

**Issue by thdoan** [thomaswilburn/Caret#424]
If you can give users access to the underlying Ace API, then it will open up Caret to a whole new level of customization. For example, I would love to be able to do add a 'To Title Case' command to the menu by adding this to menus.json:

```
{
  "label": "To Title Case",
  "command": "custom:toTitleCase",
  "argument": function() {
    // Get selected text
    var sSelectedText = editor.getSelection();
    // Convert sSelectedText to title case
    ...
    // Replace selection with sSelectedText
    editor.session.replace(editor.selection.getRange(), sSelectedText);
  }
},

```

To bind a shortcut to this new custom command, I would add this to keys.json:

```
"Ctrl-Alt-T": { "command": "custom:toTitleCase" },
```

**Comment by thomaswilburn** [comment]
The API *is* exposed, though. You can send commands over the standard Chrome messaging bus all you want, and Caret will happily run commands for both itself and for Ace. We have a full plugin API that can be used for this, it's just nobody uses the damn thing, which is a shame because I spent a lot of time building it.

**Comment by thdoan** [comment]
Yes, I can tell you spent a lot of time on every aspect of Caret because it's super slick. Something that might help is if you write up a quick tutorial on http://thomaswilburn.net/caret/ to show people how to extend Caret by accessing the Ace API to do something very simple, like getting a selection, manipulating it, then outputting it back to the editor.

I looked in `api.json`, but from there I didn't know what to do next.

**Comment by thomaswilburn** [comment]
There's some information in the wiki, but it could probably be expanded a bit, yes.

**Comment by ishu3101** [comment]
If you want people to create plugins for Caret, you would want to update the documentation with some examples showing on how to create a plugin.

**Comment by thomaswilburn** [comment]
That sounds like a great task for someone to take on if they want to contribute to this project. Most of the documentation for commands is already in the wiki.

**Comment by ishu3101** [comment]
But how do you create your own command? Also, how do you run & test your plugin

**Comment by ishu3101** [comment]
@thdoan Did you manage to get the TitleCase command working?

**Comment by thomaswilburn** [comment]
The `api:execute` command sends messages to other extensions or apps. It is documented [here](https://github.com/thomaswilburn/Caret/wiki/Commands#apiplugin-commands-still-in-beta), and there is an example in the external commands settings file. You will need to understand how Caret's message bus works to write an effective plugin, but that's not hard.

**Comment by ishu3101** [comment]
When I write editor.session.replace(editor.selection.getRange(), sSelectedText); I get the editor command is not defined.

**Comment by thomaswilburn** [comment]
Do you have code I can see? Where are you writing this?

**Comment by ishu3101** [comment]
This is what my **background.js** file has so far.
```
chrome.runtime.onMessageExternal.addListener(function(message, sender, sendResponse) {
    var selected_text = message.context.selection;
    if (message.data === "titlecase") {
      var uppercase = selected_text.toUpperCase();
      console.log("Selected Text:\n", uppercase);
      editor.session.replace(editor.selection.getRange(), selected_text)
    }
});
```

**Comment by thomaswilburn** [comment]
Why are you editing background.js? It's used to perform non-UI tasks, it doesn't have access to the editor.

**Comment by ishu3101** [comment]
So where should I write the code. I am following your gh2caret example.

**Comment by thomaswilburn** [comment]
You need to spend some time figuring out how Chrome apps work, and how Caret is structured. You don't get a reference to the editor from an external process, you have to send it messages indirectly. The sendToCaret() function in gh2caret, for example, transfers a command containing some text to insert.

If you try to run code directly against the editor, you won't get very far. The Chrome security model prevents us from sharing objects that way. Think less like method calls, more like window.postMessage().

**Comment by ishu3101** [comment]
Do you use `chrome.runtime.sendMessage` to interact with the editor?

**Comment by thomaswilburn** [comment]
Yes, I believe so.

-----Original Message-----

**Comment by thdoan** [comment]
@ishu3101 No, I ended up going back to Notepad++, installed Python Script, and wrote a Title Case plugin in Python instead. Maybe I will revisit this when time permits, but right now my editor is able to do everything I want by extending with Python. Please let me know when you're able to implement Title Case :)

**Comment by ishu3101** [comment]
@thomaswilburn Could you please give me access right to the wiki, so I can make updates to the documentation?

**Comment by thomaswilburn** [comment]
No. Wiki access comes with push access to the repo, which I don't give out. You can clone the repo and file a PR.

-----Original Message-----

**Comment by ishu3101** [comment]
Do I clone the repo or the wiki?

**Comment by thomaswilburn** [comment]
The wiki. It's kind of a weird system.
