### ISSUE TITLE
Feature request: Right click actions on project sidepane

### ISSUE THREAD

**Issue by tomas** [thomaswilburn/Caret#426]
Hi, loving Caret so far. I was wondering if you might consider adding support for performing actions on right click on the sidepane, such as new file/directory and remove file/directory. I feel like having just those simple actions would _greatly_ increase my productivity using Caret.

Actually, I'm not sure if there _is_ a way to remove a file or a directory... or maybe I missed it? :)

**Comment by thomaswilburn** [comment]
Right click already removes directories. Removing files is not something we support yet, but I would take a pull request for it. New file/directory is also possible, but kind of painful given the way that ChromeOS handles file entries. I don't remember if the work in the `project-rewrite` makes that easier or harder.

**Comment by tomas** [comment]
How do I enable the right click menu to remove directories, then? I'm on 1.5.12 and right clicking anywhere on the sidepane does nothing.

**Comment by thomaswilburn** [comment]
It may only be enabled for project directory roots, to remove them from the project.

**Comment by tomas** [comment]
Oh, but that's not what I meant. I mean removing them off the filesystem (or moved to a Trash directory). Given that right-click menu is already implemented, this shouldn't be too hard, would it? 

I'd be happy to send a PR, by the way. Just point me in the right direction and I'll give it a shot.

**Comment by thomaswilburn** [comment]
Sure, take a crack at it. All this stuff is handled in `ui/projectManager.js`, which is (unfortunately) the most complicated module in Caret. You would need to write a new method for removing/adding items from the file system, and then bind it using the context menu helper like we do at the bottom of the file. You'll also probably want to trigger a re-render at that point, although hopefully you shouldn't need to walk the filesystem again to do it (I don't actually remember the data structure I'm using in this branch -- in the rewrite, I think it's a tree, which would make things easier).

**Comment by tomas** [comment]
How far off is the rewrite branch, then? I don't want to dive down and work on a branch that has a life sentence.

**Comment by thomaswilburn** [comment]
That's a fun question! It doesn't really have a good answer. Rewriting the project manager is really just for developer ergonomics, it can't have any real effect on user-visible features until Chrome adds things like file watches, and that's unlikely to happen anytime soon given the way resources have been allocated lately by Google. I don't have a lot of time or energy myself to work on Caret for large features these days, so it's probably safe to say that it's on indefinite hold.

The good news, if you were to diff the two branches, is that they're not wildly dissimilar, and work done in one is probably mostly portable to the other--`project-rewrite` primarily splits the current project manager into three parts: one for maintaining the tree, one for individual file nodes, and one for project config files. The file nodes become more powerful in this version, and are responsible for their own rendering. If you were to add deletion as a method on the FSNode objects, I believe we'd be able to port that over pretty quickly when (if) the new branch ships.

**Comment by tomas** [comment]
Yeah, makes sense. I'll give it a shot sometime this week.
