### ISSUE TITLE
"Destroys" files after PC shut down

### ISSUE THREAD

**Issue by Kitanga** [thomaswilburn/Caret#435]
I'm using a chromebook and for the 3rd time this year this app has destroyed my work. Look at the image to see what it did to my .js file. The computer run out of battery and turned off. When it opens this happened. If anyone knows how I can fix my .js file please help. Becausethis was supposed to be my work for js13k (Competition)
![screenshot 2015-09-10 at 19 31 49](https://cloud.githubusercontent.com/assets/14119482/9794326/2e702758-57f3-11e5-939f-69dbdb55ea17.png

**Comment by thomaswilburn** [comment]
Yes, I've seen this when Chrome crashes. There's nothing we can do about it--it's at a lower level than Caret, in the runtime. You should file a bug at crbugs.com, and hopefully they can take a look at it.

Although it will not help you right now, this is in part why I use Git even for small projects, since I can always restore from the latest commit.

**Comment by Kitanga** [comment]
I was using Caret-T and now I'm wondering if Caret will do the same thing to my files.

**Comment by thomaswilburn** [comment]
A) If you're using Caret-T, why are you filing bugs here? Go tell Morgan about it.

B) I don't know of any reason why any Chrome app wouldn't be vulnerable to this. Caret doesn't do anything weird as far as files go--we use the standard APIs in pretty unremarkable ways. I can't make any guarantees, but I'm still pretty sure this is a problem with Chrome's API layer, and not Caret (or any other software written on top of the Chrome app runtime).

**Comment by Kitanga** [comment]
Hold on, when I clicked help in Caret-T's settings tab it sent me here. Thanks for replying though. I'll just have to close Caret before PC shuts down.
