### ISSUE TITLE
Request: code formatter option

### ISSUE THREAD

**Issue by fvant** [thomaswilburn/Caret#437]
Is it forseen to have a code formatter included in the editor ?

For example like so https://cloud9-sdk.readme.io/docs/code-formatter

**Comment by thomaswilburn** [comment]
I don't have any plans for it right now. Generally, running a code formatter requires us to do a full AST parse and then rewrite the code based on the result, and that tends to be pretty heavyweight in terms of package size. It also has to be done for each language we want to support, and I don't really have time to hunt down and debug syntax handling for languages I don't use. 

If this is what you want, however, at least for JavaScript, I think it's the point of the Caret-T fork. You might have better luck convincing them to branch out.
