### ISSUE TITLE
Add a way to search the entire project

### ISSUE THREAD

**Issue by brismuth** [thomaswilburn/Caret#442]
I found issue #336 and issue #70, both of which are asking for this. In both you said that there was no way to handle project-wide search at that time.

I've been experimenting with different Chrome text editors and found this to be the best in many ways, but the lack of this feature makes it unusable for serious development. 

I found that the [Zed](https://github.com/zedapp/zed) editor is able to search entire projects, and very quickly at that. I believe it accomplishes this by indexing all files in advance. Would it be possible to do something similar in Caret? I'd be willing to help out with development.

**Comment by thomaswilburn** [comment]
I'd be happy to take a pull request. Right now I'm not really interested in writing it from scratch. I think I'd prefer we didn't index the whole project, though--that sounds like a lot of memory resident just in case someone searches. I'd rather stream in new results to the UI as we walk the tree.

**Comment by brismuth** [comment]
I've been digging into the source and getting to know the project layout, and I'm currently thinking about adding the functionality to either projectManager.js or palette.js. The functionality will be mapped through the command palette and it will cause a popup to appear similar to the Command/Go To palette. At first I was thinking I'd pipe the results into the dropdown that appears on the palette (in which case I'd add it it to palette.js), but now I'm thinking it would be better to put the results in a new tab similar to how Sublime does so that they can be persisted. 

What do you think? It would probably look better to have a dropdown like the command palette's but it would also be nice to have persisted search results with a few lines of context with each result.

**Comment by thomaswilburn** [comment]
If you're going to use a new tab for output, I don't think you should do it via the palette. Mimic the way that Sublime and Atom do it, with a new panel at the bottom, so that we also have a place to put things like option buttons.

**Comment by brismuth** [comment]
That makes sense, I'll do that. I think it would be confusing for the user to have a palette box appear and have a slower search like this one from it anyway. Thanks for the feedback.

**Comment by brismuth** [comment]
There are a couple features that I didn't add but I think would be nice, like search history and regex support. It should be too hard to add them later though.

By the way, I have to say, your code is very elegant and organized. It made it much easier to extend. :clap:

**Comment by thomaswilburn** [comment]
Awesome. Give me a couple of days to go through the code and make some notes, and then we'll work on merging it in if everything looks good.

**Comment by brismuth** [comment]
Great, sounds good.

**Comment by brismuth** [comment]
Thanks for merging.
