### ISSUE TITLE
How can you toggle a comment in Chromebook's Caret?

### ISSUE THREAD

**Issue by samilosoi** [thomaswilburn/Caret#444]
Dear Sir, 

I am trying to get most of Caret in Chromebook. 
I would like to toggle a comment in Caret, a thread about it here http://superuser.com/questions/981510/why-ctrl-not-toggle-comment-in-tex-file-of-caret

When do you estimate that Chromebook's Caret can toggle a comment? 

Best regards,

Sami

**Comment by thomaswilburn** [comment]
Yes Sami, I saw (and answered) your support thread as well. Please pick a contact method and stick with it.

Commenting depends on the syntax mode. If comments don't work when you press Ctrl-/, check to make sure that the syntax supports it. For example, plain text does not have comments, so the key combo does nothing there.

**Comment by engen0** [comment]
He's asking about the TeX syntax which does have a comment defined. However toggle comment doesn't work

**Comment by thomaswilburn** [comment]
That's unfortunate. Please file a bug against Ace for it--I can't do anything about their keybindings.

**Comment by samilosoi** [comment]
The same problem is also in Samsung Chromebook 1 model 2012, so not only Acer Chromebook 2.

**Comment by thomaswilburn** [comment]
If there's a problem with the syntax mode, it's an Ace bug, and you will need to file it with them.

**Comment by engen0** [comment]
I believe I fixed that bug but I can't test it. I cloned Caret.git to my chromebook made and installed it as unpacked extension and this is what I got:
![screenshot 2015-10-11 at 2 36 21 pm](https://cloud.githubusercontent.com/assets/13821581/10419216/87c0590a-7025-11e5-9595-a912c185a250.png)

**Comment by thomaswilburn** [comment]
You're seeing bad output because you didn't run the Grunt task to generate the CSS. I don't check in built files.

If you edited the mode-tex.js file, again, that is a bug in Ace. Please submit it to them. I won't accept it, because I just pull their built code.

**Comment by engen0** [comment]
I merged the bug fix with Ace. But can you provide more information on how to install Caret as an unpackaged extension on a Chromebook?

**Comment by thomaswilburn** [comment]
I think the instructions in the README are pretty clear. Is there something there that we should explain more? I did forget to say that you need to `npm install grunt-cli -g`, but I figured most people were pretty familiar with Grunt at the time.

**Comment by engen0** [comment]
I'm not in developer mode. Is there a way you could package the source so that developer mode wouldn't be necessary?

**Comment by thomaswilburn** [comment]
The Chromebook itself doesn't have to be in developer mode at the OS level. The checkbox in the extensions page can be enabled even if you are still in "secure boot" mode. They are separate developer modes.

**Comment by engen0** [comment]
Then I'm not sure how to access the terminal to run those commands.

**Comment by thomaswilburn** [comment]
Ah, that's an excellent point. Sorry, yes, without being able to run Node (so that you can build the CSS files) you are pretty much unable to load Caret from this source repo. You could build the CSS from another computer, and copy the files over, since there's nothing else that we do that requires Grunt (although it is handy for generating the manifest).

**Comment by thomaswilburn** [comment]
Just out of curiosity, how did you manage to clone the repo if you don't have command line access?

**Comment by engen0** [comment]
There's an app called Chrome Dev Editor provided by Google which has git capability.

**Comment by thomaswilburn** [comment]
Interesting. I wasn't aware it was that far along. Google makes a lot of noise about how scary dev mode is, but unless you have institutional reasons for not being able to bypass it, I actually think everyone should toggle it. A Chromebook makes a very nice Linux dev machine combined with Crouton.

Unfortunately, I don't have any plans to maintain a repo in which we check in the built files. In fact, I was just thinking the other day about how to actually exclude Ace from the repo, and grab it from Bower or NPM instead, and only the fact that I like to hand-exclude some of the wackier Ace extensions (like JSONIQ mode). So it could be even worse.

**Comment by TheThirdOne** [comment]
@thomaswilburn Being in dev mode is a huge security vulnerability. It ends up making Chrome OS equivalent to a linux distro (with a slightly smaller attack surface) versus its default very secure state (the worst that can happen would be fixed with a reset).

**Comment by thomaswilburn** [comment]
To each his/her own. I don't think I would classify "equivalent to a linux distro" as "a huge security vulnerability" in a developer context, personally. It's not something I would recommend to my parents, but I have to do my work somewhere. If the Chromebook isn't in dev mode, that just moves the security burden somewhere else (and since I work at a newspaper instead of some place with real resources, that "somewhere else" is probably just SSH into a VPS somewhere, which is hardly a security stronghold).
