### ISSUE TITLE
Add  syntax highlighting for Processing.

### ISSUE THREAD

**Issue by mikeheiser** [thomaswilburn/Caret#446]
I was wondering if you could add syntax highlighting for the Processing language (.pde).
Thanks.

**Comment by thomaswilburn** [comment]
That's just Java, right?

**Comment by mikeheiser** [comment]
Yes. I chose java but whenever i reopen a .pde file it defaults back to the txt highlighting.

**Comment by thomaswilburn** [comment]
That's fine, I'll add it to the list of extensions for Java.

**Comment by mikeheiser** [comment]
Thank you for the quick response.
 
Thanks
 
Michael Heiser
 
 
--------- Original Message --------- Subject: Re: [Caret] Add syntax highlighting for Processing. (#446)
