### ISSUE TITLE
How to Manage Save Better with Unstable Internet Access in Caret?

### ISSUE THREAD

**Issue by sami10007** [thomaswilburn/Caret#448]
Dear Sir, 

Assume your internet access is interrupted at some point. You think it is still on. You press Str+s to save but indicates the the document is saved, although it is not, since no internet connection. 
You close your document. You lose your edits. 

The lost of the edits has happened me now several times when I work with documents created in Google Drive and edited in Caret. The internet connection gets lost and you save the document in Google Drive. I think Caret should inform better when the saving is not successful in Google Drive, not just say that it is always successful, since it is not. 

I double copy documents to my Memory card at the moment. However, this requires some extra work, and cannot be a permanent solution, since the process is error-prone to human. I propose that the system should inform the user when the save is unsuccessful and/or save the unsuccessful save to Downloads where it should be in queue for Google Drive save. 

How can you manage save better with Unstable Internet Access in Caret?

**Comment by thomaswilburn** [comment]
As far as Caret is concerned, if the file system reports a successful save operation, the file was saved. We don't have any information about whether files are on a network-backed drive, and I don't even know how we would go about figuring that out. It's the responsibility of the network drive to accurately report back to us.

Google Drive should cache local changes until it reconnects, but if it doesn't, the answer is probably to stop using it when your connection is bad, not to alter Caret to work around its non-standard behavior.

**Comment by sami10007** [comment]
It would be nice to have a feature for a backup system. Let the user store things always to Google Drive but also a duplicate copy to some folder of Downloads. This feature would reduce the risk of losing your work.

**Comment by thomaswilburn** [comment]
It might be nice, but it's not something Caret should do. It's a text editor, not a file manager.

To be honest, Caret doesn't treat Google Drive any differently from any other file. It doesn't know where things are even located, really. It just reads and writes "files" that Chrome hands to it. So for your solution, Caret would have to maintain double copies if everything it edits, and you'd have to manually grant it access to the backup directory on a regular basis, and hope that we have enough information to not screw up your data (see the open bug where we mishandle project directories with the same name for evidence that we can't guarantee that).

Or you could just stop storing stuff in an unreliable place, which seems much simpler and easier.

**Comment by TheThirdOne** [comment]
@sami10007, you might be able to find (or make) an app to wrap the gdrive app and provide automatic backups. But you should file an issue for gdrive though.
