### ISSUE TITLE
Make the main UI customizable

### ISSUE THREAD

**Issue by brismuth** [thomaswilburn/Caret#452]
It would be nice to allow people to theme the UI of the app itself and not just the Ace editor. If we incorporate less.js, it would be trivial to change LESS variables on the fly (see `less.modifyvars` in [LESS docs](http://lesscss.org/usage/)).

An additional benefit to this is that people would no longer need node/npm or grunt in order to develop on Caret.

One downside is that there may be a performance hit in compiling LESS on the client instead of in the distributed package. I want to look into this though to see how much of a difference it would really be.

**Comment by thomaswilburn** [comment]
I don't honestly know how I feel about this change. I think the performance penalty is likely to be relatively small--after all, we load the JS modules asynchronously without a build process, and that has always been reasonably fast. But there aren't currently a ton of variables in the LESS for people to affect right now anyway. The more we add for people to change, the more opportunity for them to get the code into a state where it's too garbled for them to recover it. And while the light and dark themes aren't a tremendous amount of variety, they're reasonably attractive and there's some value in being a little bit opinionated about UI.

I'm actually leaning toward moving JS from Require into Browserify and pre-building _more_ of Caret than I am to move us to a situation where we dynamically process more of it at runtime. I already kind of regret the dynamic stylesheet that powers the custom Ace theme settings. We could also build additional themes besides just light and dark. But I'm open to being persuaded if a strong argument can be made.

**Comment by brismuth** [comment]
To be perfectly honest, the main reason I wanted to do this is that I'm not a huge fan of the accent colors, specifically the orange accent on the dark theme. After experimenting with some different colors, I found that `#6896BE` looks pretty good as `@accent` with the dark theme. It occurred to me that others may feel the same way about my color choice and that it may be worth allowing people to choose it themselves.

If you are against dynamic LESS compilation, but are willing to accept a pull request that just adds other theme options, I'd be okay with that.

**Comment by brismuth** [comment]
By the way, this is what that accent color looks like:

![screenshot 2015-10-23 at 11 09 50 pm](https://cloud.githubusercontent.com/assets/5679695/10709004/3ebb6802-79db-11e5-8d07-61aa38e290d8.png)

**Comment by thomaswilburn** [comment]
I can dig that. Yes, if you wanted to submit a PR with some alternate accents for both light and dark, I think that'd be better than adding live LESS compilation to the app.

**Comment by brismuth** [comment]
K, I'll do that instead.
