### ISSUE TITLE
Add the ability to sync the sidebar with the currently open file

### ISSUE THREAD

**Issue by brismuth** [thomaswilburn/Caret#453]
I've noticed that sometimes I have a file open and I'm editing it, and for some reason I want to know what directory it is in. From what I can tell, there is no easy way to accomplish this. My proposed solution is adding an option to User Preferences that when enabled will synchronize the side bar selection with the currently open tab. 

You can achieve this effect in Sublime with the [SyncedSideBar plugin](https://packagecontrol.io/packages/SyncedSideBar).

**Comment by thomaswilburn** [comment]
Before you get too far into something like this, which would impact the rendering code for the project, be sure to check out the `project-rewrite` branch, which does some necessary plumbing work on the directory tree and its underlying data structures. If we're going to hack into the project, we should do it on a better foundation than the current overwrought `project.js` file.

**Comment by brismuth** [comment]
Sounds good. I'll ping you before I start on this.

**Comment by alistairjcbrown** [comment]
Active file (#676) and reveal in sidebar (#678) are both in the codebase. Not sure if that either makes this request easier if there's further work required / means it can be closed off.

**Comment by thomaswilburn** [comment]
It's probably closable, thanks.
