### ISSUE TITLE
Add search in the current opened tabs

### ISSUE THREAD

**Issue by sami10007** [thomaswilburn/Caret#463]
I would be great to have a search in the currently opened files. CTRL+Shift+F searches project files. It would be great that this could be customized to current open tabs or if no project, then automatically to the current open tabs. What do you think?

**Comment by thomaswilburn** [comment]
This... is already a thing that exists? Use the palette, you can search for keywords if the first character is a `#`.

**Comment by sami10007** [comment]
That is not the same thing. Search by # is searching one document and showing matches there in a hover window. I want to search in the current opened documents in tabs.

**Comment by brismuth** [comment]
I understand what you mean. Sublime does this -- it searches both added directories and open files, even if they're not in the added directories. I didn't add it in my initial go for project search because it makes it a bit more complicated, but it should be doable.

**Comment by thomaswilburn** [comment]
`#search` will check all open tabs, if you have the `searchAllFiles` user preference set. We can roll this into the project search, if you want, but the feature does already exist.
