### ISSUE TITLE
OS locks up when saving edit to zipped file

### ISSUE THREAD

**Issue by clball** [thomaswilburn/Caret#465]
Steps to reproduce: In Chrome OS, double-click to open a .zip file from Files interface. Don't move the unzipped files from the mounted .zip file to the disk. Edit the file in Caret and attempt to save edits, OS freezes up and Chromebook needs to be powered down.

Tested on Chrome OS: 
Version 46.0.2490.71 (64-bit)
Platform 7390.59.0 (Official Build) stable-channel samus
Firmware Google_Samus.6300.152.0

Here's more system details if needed: https://gist.github.com/bf2593518cad01b2248a 
Please let me know if you need any additional details to reproduce this crash!

**Comment by thomaswilburn** [comment]
I don't think this is something we can fixed. Have you filed it with crbug.com?

**Comment by clball** [comment]
That makes sense! I'll file it with Chrome OS then. Sorry!
