### ISSUE TITLE
Add syntax highlighting for search results like Sublime does

### ISSUE THREAD

**Issue by brismuth** [thomaswilburn/Caret#467]
Add special syntax highlighting for search results like Sublime does:

![image](https://cloud.githubusercontent.com/assets/5679695/10826017/4b020aca-7e2d-11e5-9ff8-d54bf543d48f.png)

**Comment by grit96** [comment]
I'm interested in working on this. Would we need to get a new syntax mode into ace in order to use it for the search results, or is there another way of setting the syntax highlighting?

**Comment by brismuth** [comment]
One way of doing it would be to add markers the same way the file links are added (see searchbar.js line 271). Then you could add the corresponding css classes to color them.

The other option is to create a new syntax mode for Ace for it. I'm not sure how difficult that would be. It would probably be the cleaner, preferable option if it is feasible.

**Comment by thomaswilburn** [comment]
There's an existing mode in Ace for Cloud 9 search results. I have no idea what it looks like. But I'd probably start there, and either change it to match out result format, or change our results to match it.

**Comment by brismuth** [comment]
Thanks for adding that @grit96, looks great!

**Comment by grit96** [comment]
No problem :-)
