### ISSUE TITLE
Automated tests, finally

### ISSUE THREAD

**Issue by thomaswilburn** [thomaswilburn/Caret#468]
We have been at the point for a while now where the number of features in Caret actually far exceeds the amount of things that we can reliably verify by hand for any given change. Although for the most part Caret's architecture means that things are isolated and should not cause bugs when integrated, it has happened in the past.

As much as I hate writing UI test code, I think we should consider it (it's also a great opportunity for open-source contributions). I have some thoughts:
- Tests should not ship with production Caret, and shouldn't be loaded by default. We could run a command like `app:run-tests` from the command line input, and that could asynchronously load the testing library and tests from a directory that's in the base repo.
- I don't have a real preference for the framework. Jasmine and Mocha both look fine to me, although the native support for promises in the latter seems like a pleasant feature.
- One of the big barriers to running automated tests for Chrome apps (or indeed, for many browser APIs) is that there are a lot of operations that can't continue without user interaction. For example, opening a file or project requires the user, and things like file retention IDs cannot be carried across devices. So we'll need to think about how to do messaging for these tests, so that people know what they need to do for them to work.
- The other alternative is to stub out some of the Chrome packaged app APIs with a simple Node server, and shim those in when running tests. We have to assume that those APIs work, anyway, so it might be nice to run tests in an environment where things like file operations are completely under our control.

**Comment by brismuth** [comment]
Instead of running a separate node server or requiring user interaction, Mocha will actually let you just add a file to the root of your tests directory that can be run before each test. Inside there you could stub out the chrome APIs easily using Sinon. That would be the easiest approach imo.

**Comment by thomaswilburn** [comment]
Hm, that's probably a good idea, as long as we don't need any of the in-memory "files" to persist across restarts.

**Comment by brismuth** [comment]
Looks like someone already made https://github.com/vitalets/sinon-chrome for extensions. Not sure how well it would work with apps though. It probably wouldn't have any coverage of the file APIs if it's for extensions only.
