### ISSUE TITLE
Project Wide Search searches executable files

### ISSUE THREAD

**Issue by TheThirdOne** [thomaswilburn/Caret#470]
I have a few compiled executables in my project, and when I search using the project search I get a lot of extra search results from the executable files.

This might be solvable with a filetype filter or a blacklist for which files to search.

**Comment by brismuth** [comment]
Currently search uses the same blacklist that is applied to the sidebar. Do you want the executable to show up in the sidebar? If not you could blacklist it in your user preferences.

**Comment by TheThirdOne** [comment]
I didn't know that was a thing. How do I blacklist something from the sidebar?

**Comment by brismuth** [comment]
Under user preferences,

```
  //set a regex to ignore in project view/search
  "ignoreFiles": "node_modules",
```

**Comment by TheThirdOne** [comment]
1. That is slightly broken on its own (it removes anything with the string in the name rather than an exact match; I had to use the exact name + $ to get it to work)
  2. I would like to do this on a project based level.  
  3. How do I do multiple blacklists? An array of strings doesn't work.

**Comment by thomaswilburn** [comment]
It's a regex, you can just use the | metacharacter to exclude multiple results.

I don't remember if we really get enough stat() information on a file entry to tell if it is executable. We can make some guesses on Win32 and Mac based on extension, but on Linux/ChromeOS the only thing that makes a file "executable" is a flag bit on the file system. How would we know to exclude something?

-----Original Message-----

**Comment by brismuth** [comment]
You can read more about project specific settings in the [documentation](https://github.com/thomaswilburn/Caret/wiki/Projects). You can read more about javascript regular expressions [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions). 

@thomaswilburn even if we could do that, I doubt we'd want to. Many executables are text files that you'd want to be editable in Caret. I think the user and project settings are the right way to go on this.

**Comment by thomaswilburn** [comment]
True. I do think eventually we'd like to be able to include/exclude files from the search panel, but I don't think it should be a priority just yet.

**Comment by TheThirdOne** [comment]
I would expect the regex to have to match the entire filename to ignore it; instead if it has any match inside the filename it is ignored. Is this the intended behavior?

The following added in the project file doesn't ignore the file. Am I doing something wrong?
```
"settings": {
    "ignoreFiles": "filename"
 }
```

I think relying on regex for multiple blacklists is sub-optimal. I would think adding support for arrays should be very simple.

**Comment by thomaswilburn** [comment]
The whole reason we use regex is so as to not have to match entire filenames if we don't want to. I also don't see any functional difference between an array and a regex with multiple match groups, except that it would require us to rewrite the way projects are loaded (and it would probably be slower--V8 regex is ridiculously fast).

**Comment by thomaswilburn** [comment]
I can look into whether there's a bug for ignore files in project settings, but it should work.

**Comment by thomaswilburn** [comment]
So I've been looking into it, and the regex does in fact trigger on individual files, but you sometimes need to refresh the directory after saving the project file before the blacklist takes effect. I knew that it worked, because my Caret project file actually has a different regex compared to the default, but it looks like we may not be reading and re-initializing the blacklist in a predictable order. I'm going to close this issue, but spend a little time this weekend looking at the order and cleaning up the code to make sure it behaves as expected without the refresh.

**Comment by TheThirdOne** [comment]
When I refreshed after saving the project file, it still did not update.

**Comment by thomaswilburn** [comment]
What's the exact filename/regex combo you're using?

**Comment by TheThirdOne** [comment]
So, after a restart of caret the problem disappeared, but I had some buggy behavior trying to add new folders to the project.
