### ISSUE TITLE
Allow side-by-side editing

### ISSUE THREAD

**Issue by tlewis3348** [thomaswilburn/Caret#471]
I often find that I need to do quite a bit of moving between either two separate files or two locations of a large file.  In these situations, it would be very convenient if I could either divide the Caret window into two or more panes or open multiple instances of Caret.  I don't know if this functionality is possible, or if it has already been considered, but I would greatly appreciate it if you could find a means of adding it.

**Comment by thomaswilburn** [comment]
Unfortunately, I don't usually work in paneled editors, so the assumption through the entire code has been that there's a single editing panel that everything talks to. I don't think it's really feasible right now.

**Comment by tlewis3348** [comment]
Oh.  That's unfortunate.  Is there any way for me to at least open multiple instances of Caret?

**Comment by thomaswilburn** [comment]
No, unfortunately. In this case, you get what you pay for.

-----Original Message-----

**Comment by tlewis3348** [comment]
Hmmm....  Okay.  Thanks for an otherwise awesome text editor!

**Comment by brismuth** [comment]
How hard would it be to allow multiple instances to be open at the same time? Would the worry be that they'd both try to reopen the same project file? It seems like most of the code would support to Caret apps to be open at the same time. Actually, I had two Caret instances (the app store version and my development version) open the whole time I developed project search and they both seemed to work fine. 

It seems like that functionality would just require a change to where the app window is opened in background.js. Am I missing something?

**Comment by thomaswilburn** [comment]
I think the main concern I had was handling messages and OS-level events that come in, including triggering files from the file app: which window do they open in? Is it the first one, the topmost one, or some other algorithm? How do we make sure that process is intuitive?

Technically, having two instances open, like when we're doing development on Caret in Caret, doesn't count--they're separate apps with different IDs, background pages, and storage as far as the runtime is concerned.

Editing the config files is a tricky problem--we don't have any form of inter-window messaging to let other windows know that they need to re-pull settings--but I think that one's actually reasonably solvable (and people get what's coming to them if they try to edit settings from multiple windows at once).

**Comment by brismuth** [comment]
I agree that config files would mess things up, and that it's maybe not worth worrying about. As far as which window to open them in, I don't think users would complain as long as it opened in an existing one. If people want a file in a specific window they can open it from that window. 

If those are the only two issues, it sounds like running in two windows would be pretty doable. I think I'll take a look.
