### ISSUE TITLE
Edit syntax highlighting/file type associations

### ISSUE THREAD

**Issue by tlewis3348** [thomaswilburn/Caret#472]
This may be possible already, but I haven't been able to figure out how to do it.

I would like to modify and add to the syntax highlighting/file type associations.  Specifically, as it is now, when I open a JSON file, it highlights the syntax with the JSON theme, but I would rather it highlight it with the JavaScript theme.  Additionally, when I open a .VB file, it uses the Plain Text theme, but I would like to at the very lease use the VBScript theme (though ideally I'd be able to tweak that theme to highlight the syntax correctly).

Is this already possible, or can it be added?

**Comment by tlewis3348** [comment]
Just saw this: https://github.com/thomaswilburn/Caret/issues/184.

Not sure whether that's related to my request above.

**Comment by thomaswilburn** [comment]
You can edit the associations by editing ace.json. It's not exposed through the UI, normally, but it's easy to add a menu item that makes it available (look at the menu setup for editing the other config files).
