### ISSUE TITLE
new menus

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#473]
The 'Edit' menu is overloaded.
On my acer c720 chromebook the menu is long
and can not show all menu items.

So... I created a 'Search' menu between 'Edit' and 'Tools'.
Is the following correct? supported?

It seems to work, other menu labels are of the form:
```"label": "menuTools",```

If I use:
```"label": "menuSearch",```
I get a menu item named 'menuSearch'!
```
  {
    "label": "Search",
    "sub": [
      { "label": "menuFind", "command": "ace:command", "argument": "find" },
      { "label": "menuFindReplace", "command": "ace:command", "argument": "replace" },
      { "label": "menuFindNext", "command": "ace:command", "argument": "findnext" },
      { "label": "menuSearchProject", "command": "searchbar:show-project-search", "retainFocus": true },
      "divider",
      { "label": "menuGoToAnything", "command": "palette:open", "retainFocus": true },
      { "label": "menuGoToLine", "command": "palette:open", "argument": "line", "retainFocus": true },
      { "label": "menuGoToSearch", "command": "palette:open", "argument": "search", "retainFocus": true },
      { "label": "menuGoToRef", "command": "palette:open", "argument": "reference", "retainFocus": true }
    ]
  },
```

**Comment by thomaswilburn** [comment]
Strings like "menuFind" or "menuTools" aren't really for your consumption. They're used as lookup keys for the internationalization files located in the _locales folder. If you're just making menus for yourself, I assume you don't need them localized, and you can just write the label that you want to appear there. As you've noticed, lookups that don't exist in the i18n files are just passed through to the other side.

**Comment by broomdodger** [comment]
Thank you for the explanation.

Would you be willing to break out the 'Search' items
from the 'Edit' menu as I have done?
The 'Edit' menu is quite long.

**Comment by thomaswilburn** [comment]
It seems weird that it's going off screen for you. My Chromebook is the same resolution, and I don't have this problem. On the other hand, I almost always use the palette instead of the menus, so I may have just missed it.

I'd be fine with breaking out the menu, but I'm not sure search is the best place to do it. In the meantime, though, this is actually why the menus are editable--so that you can fix things when the defaults don't work for you.

**Comment by broomdodger** [comment]
I just now checked a Linux Mint machine (1280x800 the chromebook is 1366x768)
and the Edit menu is cut off, the `movelinesdown` item is not showing.

I rarely use menus... always keyboard shortcuts (customized).
For a while now I have been on the Linux Mint machine exclusively
for programming and scripting, yes... **real** vim not the *wacky* ace vim.
When I went back to the chromebook I had forgotten some keyboard shortcuts.
That is when I use menus, to refresh my memory of the shortcuts.

`"I almost always use the palette instead of the menus"`
Do you mean the Tools > Open Command Palette ?
Do you use that in preference to keyboard shortcuts? in addition?
How do you use it?

Scrolling menus are too much trouble!
I like more but shorter menus.
It is so great that I am able to customize Caret :)
Thank you.
