### ISSUE TITLE
CSS style sheet

### ISSUE THREAD

**Issue by famclean48** [thomaswilburn/Caret#475]
I was wondering if someone could help me.  I am trying to pick up intro.css style sheet using Caret and it is not working.  The styles work when I add styles it my .html page but not when using external .css .

code I am using

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>CSS with Text</title>
    <link rel="stylesheet" type="text/css" href="intro.css">

**Comment by thomaswilburn** [comment]
I'm sorry, but this isn't really an appropriate place to ask general coding questions. 

That said, if you're trying to make a CSS file, it shouldn't start with an XML declaration. CSS is just plain text.

**Comment by famclean48** [comment]
Hi sorry did not make myself clear.  The code was from the .html page where
I am trying to pick up my css page which is plain text

<link rel="stylesheet" type="text/css" href="intro.css">.  This works in
other text editors was just wondering if different in Caret.  This is the
first time I have used this.  Just got new Chrome book and taking course on
Developing.

Thank you

Fiona McLean

**Comment by thomaswilburn** [comment]
No, it should be the same in Caret as it is in any other editor. ChromeOS may have different security settings for local files, but I think that should still work. I would check the network tab in the developer tools and see if it's actually loading your CSS file, or if it's getting a 404 Not Found error.
