### ISSUE TITLE
:w doesn't seem to work with Vim emulation on

### ISSUE THREAD

**Issue by mshmoustafa** [thomaswilburn/Caret#476]
When I try to use :w to save a document, it doesn't seem to save.  After I save it the Vim way the close button on the tab is still a circle instead of an x, and when I try to close the tab it warns me that the file was not saved.  However Caret doesn't tell me that :w is not supported like it does with other unrecognized commands.  I can still save the document normally (File > Save).

**Comment by thomaswilburn** [comment]
Vim mode is not supported for anything other than editing--it doesn't hook into the UI at all, and doesn't provide any hooks (that I'm aware of) for us to do so. There aren't any future plans to make Vim mode better, on my part at least.

**Comment by mshmoustafa** [comment]
That's fine, but it would be nice if Caret warned us about it.  For example, if I try :q, Caret will tell me that's not a supported command.  However, when I try :w, Caret remains silent.  Is there a reason that :w does not elicit the same sort of response?

**Comment by thomaswilburn** [comment]
It's a bug in Ace, which handles all of that stuff. I didn't know it even had a warning on :q, to be honest.

**Comment by mshmoustafa** [comment]
After looking at the code in keybinding-vim.js, at line 959 a series of Vim commands are listed.  The write command, aka :w is listed as a command at line 966.  It seems that removing that line would fix the issue, but more work will be needed to know for sure I think.

**Comment by mshmoustafa** [comment]
Would this discussion be more appropriate on the ace Github repo?  I just realized that the file I was looking at was in the ace directory.

**Comment by thomaswilburn** [comment]
Yes, they'll be able to handle this more effectively than we can.
