### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by akash-vartak** [thomaswilburn/Caret#477]
I ran Caret for the first time yesterday and it ran flawlessly. Today when I tried starting it, it just wasn't.
I don't see the problem, please help.

**Comment by thomaswilburn** [comment]
If you visit `chrome://extensions` in your browser and then open the background page for Caret, are there any errors on the debugging console?

**Comment by akash-vartak** [comment]
It show nothing, that's my point. I cant send screenshots cause i cant click any, I cant uninstall it as it dosen't show up in the control panel, I can't put my finger on the problem. I'm trying again.

**Comment by thomaswilburn** [comment]
I think you've misunderstood: the background page for Caret is the process that handles opening and closing windows. It's not a visible page. If you visit `chrome://extensions`, you can open the developer tools to debug this page, which will help me solve your problem.

Another option is to right-click on the Caret icon in the Chrome app launcher and choose "emergency reset." If any of your settings have been saved in a way that Caret can't handle, that will clear them. However, I'd appreciate the information from the debug console first, so I can prevent this from happening again, as bad settings are not supposed to be able to hose Caret's startup process.

**Comment by akash-vartak** [comment]
<h1>Hey!! It opened.</h1> Forget everything, let's celebrate!!!

**Comment by akash-vartak** [comment]
<h3>Ohhh </h3><h1>yeah!!!</h1>

**Comment by akash-vartak** [comment]
Thanks all the same...@thomaswilburn
