### ISSUE TITLE
Adding support for extension-less shell scripts with shebangs

### ISSUE THREAD

**Issue by jamesqo** [thomaswilburn/Caret#478]
It would be so awesome if you could add support for scripts that have shebangs like `#!/bin/sh` at the beginning. I understand it would be somewhat complicated to implement since it doesn't really fit in with the file-extension based detection you already have going, but the code required to implement this is already available in [Linguist](https://github.com/github/linguist/blob/master/lib/linguist/shebang.rb#L20-L57).

Would it be practical to implement this in Caret?

**Comment by Kriskras99** [comment]
Your url was incorrect, you had githubcom and shebangrb ;)
This is the correct url: https://github.com/github/linguist/blob/master/lib/linguist/shebang.rb#L20-L57

**Comment by thomaswilburn** [comment]
Probably not going to do this. I don't really want to get into the business of pre-parsing files and having to guess what files are. I also can't use Linguist--Caret is written in JS, not Ruby.
