### ISSUE TITLE
Locale setting

### ISSUE THREAD

**Issue by mikajensen** [thomaswilburn/Caret#480]
Caret starts now in my local language of the computer and not anymore with English menus etc. I suspect that this is the case since the last or one of the last automatic updates. I am not sure about this because Caret has been used occasionally only for some notes during the last months. Anyway, I would like to get it back in English.

Is there an option to set the language of the GUI?

**Comment by thomaswilburn** [comment]
Caret uses the internationalization system built into Chrome for any UI strings. You may be able to set Chrome to English, and Caret will follow, but otherwise I don't actually think we can override it.
