### ISSUE TITLE
Make goto symbol fuzzy search

### ISSUE THREAD

**Issue by SullyJHF** [thomaswilburn/Caret#481]
Could you make the goto symbol search work the same way as ctrl+p does for opening files (i.e. make it use fuzzy searching as in sublime text).

You mentioned it in #57 but never actually got round to doing it.

Thanks!

**Comment by thomaswilburn** [comment]
It's probably doable. We don't currently do any scoring on the location-based search, in part because there's not really a great unified path for filtering results (probably due for a refactor). I'll look into feasability and add it to the backlog.

**Comment by SullyJHF** [comment]
Alright sweet cheers :)
