### ISSUE TITLE
How I use a custom theme?

### ISSUE THREAD

**Issue by JacobRocks12** [thomaswilburn/Caret#486]
I know this is a bad spot for posting this, but how do you use the custom theme? Here's mine (or part):
`{
  "dark": false,
  "editor": {
    "background-color": "#000",
    "color": "white"
  },`

**Comment by thomaswilburn** [comment]
Custom themes are available through the settings menu, and I think there's some documentation in the wiki. It's not well-supported, though, and I plan to deprecate it as soon as I have a mechanism for communicating deprecation to users.
