### ISSUE TITLE
Change log notification crashes tab

### ISSUE THREAD

**Issue by wesort** [thomaswilburn/Caret#489]
When Caret updates and there is a change log notification, visiting the Chrome Web Store page crashes the tab immediately once it has loaded. The URL is exactly the same as when I visit Caret in the Web Store via another route: [https://chrome.google.com/webstore/detail/caret/fljalecfjciodhpcledpamjachpmelml](https://chrome.google.com/webstore/detail/caret/fljalecfjciodhpcledpamjachpmelml)

I'm pretty sure this is a Chrome Web Store issue, but wanted to report it hear after having reported to to Google a few times already.

FYI: running on Chrome OS stable (up-to-date) on Pixel 2

**Comment by thomaswilburn** [comment]
I would report this to the Chrome maintainers at crbugs.com, I think it is a problem with the way they're handling `window.open()` from Chrome apps.

**Comment by wesort** [comment]
Very good - will do.

**Comment by LB--** [comment]
Has been happening to me for quite some time, this time the url was `https://github.com/thomaswilburn/Caret/blob/master/changelog.rst` and it still crashed. @wesort could you link to the issue you opened/found about this?

**Comment by thomaswilburn** [comment]
This happened to me too, actually, during testing. Doesn't seem to be Chrome OS-only, since I was on my Windows box for the deploy. 

I think the bug is this one here: https://bugs.chromium.org/p/chromium/issues/detail?id=583397&q=tab%20crash%20notification&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified The developers are asking for a crash ID, but I don't actually know what that means.

**Comment by LB--** [comment]
> Doesn't seem to be Chrome OS-only, since I was on my Windows box for the deploy.

Yeah, it happens on both my Chromebook and my Windows 10 machine, so it's definitely an issue with Chrome itself.

About the crash ID, I found info here:
https://www.chromium.org/for-testers/bug-reporting-guidelines/reporting-crash-bug

My Windows machine doesn't have anything listed in `chrome://crashes` (strange) but my Chromebook has 27 crashes. I don't know which ones are from when caret updated and I clicked the notification, though. I will watch out next time and check for a crash ID, unless you can still reproduce it and you can get a crash ID.

Strangely, my Chromebook could not reproduce the crash with the latest update notification just now! It crashed on my Windows 10 and not my Chromebook this time, super weird. It normally always crashes on my Chromebook (I don't remember a time when it didn't until now).

**Comment by LB--** [comment]
I can no longer reproduce the crash and the bug report has been archived, so I guess it got fixed.

**Comment by wesort** [comment]
Yup, issue resolved. I like the move of the change log to Within too.
