### ISSUE TITLE
Are there any tutorials on how to execute code?

### ISSUE THREAD

**Issue by Jarepinder** [thomaswilburn/Caret#490]
How Do I use external commands, Can there be a working example? Also, can caret create/run programs on CromeOs?

**Comment by thomaswilburn** [comment]
There should be information in the wiki on how to execute commands.

Chrome can be used to edit (but not compile) code in any language your machine supports. On Chrome OS, that means it can be used to write Chrome apps, and if the machine is in dev mode, it can edit code in other languages that's then compiled from Crouton.
