### ISSUE TITLE
Additional default file types

### ISSUE THREAD

**Issue by wesort** [thomaswilburn/Caret#492]
Is it possible (now or as a feature request) to add further file types that Caret will be the default app for? 

ie: Set which file types Caret opens. For example, I'd like Caret to directly open all `.md` files when I double click (or `ctrl+o`) them.

Workarounds:
- Open `Caret` > `File` > `Open File` > `navigate to file to be opened`
- `right-click` file > chose `Caret` from top of contextual menu

I believe this relates to the [manifest and file handlers](https://developer.chrome.com/apps/manifest/file_handlers).

**Comment by thomaswilburn** [comment]
So, fun story: Chrome's limit on file extensions that we can register for on any given file type is roughly 200. If you go over that, it'll refuse to read the manifest, and the app can't be loaded.

This isn't documented, and I suspect nobody ever figured an app would exceed that. But a recent pull request added a huge number of extensions to ace.json (which was awesome, don't get me wrong!) and took us over the 200 extension limit.

In Caret v1.6.7, I switched explicit extensions for wildcards--we register for "*" under the "text" and "any" mime types, as well as "application/*". In theory, this means we won't need to update the manifest constantly, or worry about the limit. It's possible that it will stop Caret from being the default handler for arbitrary extensions, unless you set it manually. But I think the advantages make up for that tradeoff. I don't really want to get into the habit of having to justify which file types are "privileged" in the manifest.

**Comment by wesort** [comment]
That all makes sense (as far as I understand it) and thanks for laying it out. 

You mention "set it manually" - do you mean there's a way on my device to register which apps should handle which files? I've looked through chrome://about and chrome://flags but couldn't find anything.

**Comment by thomaswilburn** [comment]
In the Files app, there's an "Open with" menu in the toolbar that will allow you to set a default handler for a given extension. It's strange, but it's not on the regular "open with" menu when you right-click.

**Comment by wesort** [comment]
Yeah, not intuitive.  But even more strangely the "Open with" option (down arrow to right of "Open" in the Files toolbar) is only shown on certain file types and I'm not sure of the pattern. `.html` and `.png` files have that option for example, but `.md` files do not.

**Comment by liltinkerer** [comment]
What about GO language files? Any possibility to add .go extension?

**Comment by thomaswilburn** [comment]
Probably. I'll look into it.

-----Original Message-----

**Comment by thomaswilburn** [comment]
Actually, we already support .go files. Is there something wrong with the way it's working for you?

**Comment by liltinkerer** [comment]
Doesn't open with double click (Chrome OS) and neither does it show up if the open with menu.
Have to open .go files from file -> open... long path search.

**Comment by thomaswilburn** [comment]
I don't know if there's anything we can do specifically about that, due to the wildcard requirement detailed above. If Chrome OS doesn't recognize a MIME type for .go files, we can't really add one as far as I know, but I'd be happy to take pull requests otherwise.

The other possibility is that we add selected types to the manifest to force them to open, but that's a whole can of worms that I don't particularly want to open.

**Comment by wesort** [comment]
I presume it's not an option to have user specific manifests??

**Comment by thomaswilburn** [comment]
I mean, people can run it from source with whatever manifest they want. But we can't offer options in the store manifest, because that would mean subverting the security model for packaged apps.
