### ISSUE TITLE
Add line height option

### ISSUE THREAD

**Issue by wallaxl** [thomaswilburn/Caret#494]
see title, i think it will show well

**Comment by thomaswilburn** [comment]
Does Ace support this?

**Comment by thomaswilburn** [comment]
It's not supported, as far as I can tell.

**Comment by wallaxl** [comment]
ok, thanks

在 2016-02-24 07:18:07，"Thomas Wilburn" <notifications@github.com> 写道：


It's not supported, as far as I can tell.
