### ISSUE TITLE
Syntax Highlighting - Add languages and settings

### ISSUE THREAD

**Issue by delmartechdude** [thomaswilburn/Caret#495]
Hello,
Please add syntax highlighting for Prolog and Haskell! Also, please add a way to change the current syntax highlighting currently being used (like in Sublime)...so I don't have to save it with a proper extension to get the syntax highlighting I want.

### Type of issue (choose one):
  - [ ] Bug
  - [X] Feature request
  - [ ] Question

### Test steps

Save a Prolog or Haskell file, syntax highlighting is not applied. No menu option to add it or change it.

### Description

1. Add Prolog Syntax Highlighting Support (.pl, .pro, .P)
2. Add Haskell Syntax Highlighting Support (.hs, .lsh)
3. Add Menu to choose which syntax highlighting is being applied to the current document.

### Additional notes

None that I can think of. Thanks for your hard work on this! :)

### System details

Google Chromebook - ChromeOS
Version 49.0.2623.54 beta (64-bit)
Platform 7834.38.0 (Official Build) beta-channel lumpy
Firmware Google_Lumpy.2.111.0

**Comment by thomaswilburn** [comment]
We already have these two syntax modes, and a way to switch to them (either use the select box in the bottom right, or use the control palette and type the languages name to find the "Syntax Mode" item).

**Comment by delmartechdude** [comment]
Oh, weird! I didn't notice that menu on the bottom...I guess I didn't realize it was clickable. However, the syntax mode doesn't change automatically when the file extension changes to .pl or .hs...

**Comment by thomaswilburn** [comment]
I just saved a file as test.hs and the syntax mode switched to "Haskell." For Prolog, sadly, the .pl extension is already used for Perl, and that one's going to trigger first (as it probably should).

**Comment by delmartechdude** [comment]
Ah! I see. Yeah, that makes sense. Luckily Prolog has several file extensions so .pl being associated with Perl isn't the end of the world. Thanks for your prompt support and investigation into this - much appreciated! :)
