### ISSUE TITLE
Create your own plugin for Caret 

### ISSUE THREAD

**Issue by ishu3101** [thomaswilburn/Caret#496]
How do you create a plugin for Caret? I would like to create a plugin which would take the selected text and convert it to titlecase? I could not find any documentation on how to create your own plugin?

**Comment by thomaswilburn** [comment]
There should be documentation in the wiki, but the best source will be to look at the code itself (api.js, I think) and at the gh2caret plugin I wrote.

-----Original Message-----

**Comment by ishu3101** [comment]
From what I understand is that to create plugins for Caret you have to create a chrome extension?
