### ISSUE TITLE
Crouton building wiki page

### ISSUE THREAD

**Issue by edeetee** [thomaswilburn/Caret#497]
--Wiki Feature Request--

Hey guys, you have created a really great editor here.

I've created a little system to allow automatic building triggering off a hotkey using your API through gcc in crouton on chromeos, was wondering if it would be helpful for me to write a little wiki doc about it, as I could not find any documentation about the sendEditorContext api option and it might be helpful for others trying to set up a similar development environment using chromeos and your app.

**Comment by thomaswilburn** [comment]
I think that could be very helpful! My only concern is that you're describing a pretty complicated-sounding process. If it's possible to write it up in a way that people can use it more generally, that would be great, since we have a lot of relative newbies using this editor.

**Comment by edeetee** [comment]
Here is the write up I just put up on the crouton wiki:
[](https://github.com/dnschneid/crouton/wiki/CLI-Development-Environment)

**Comment by thomaswilburn** [comment]
Looks great to me.

**Comment by edeetee** [comment]
Any way for me to edit it without having to clone, edit, then pull?

**Comment by thomaswilburn** [comment]
It looks like I would need to open up the wiki to public editing or grant you push access to the repo proper, both of which kind of wig me out. Sorry, but clone/PR is best for now.

-----Original Message-----

**Comment by edeetee** [comment]
Rad, I'll do it when I get time.

**Comment by thomaswilburn** [comment]
Note that I think you do have to specifically fork the wiki, and not the main code repo. It's a weird system they have here. The wikis are by far the thing on GitHub that most feels like they hacked something together and then collectively said "good enough, ship it" and forgot about it.
