### ISSUE TITLE
Swift syntax highlighting

### ISSUE THREAD

**Issue by cschambers2101** [thomaswilburn/Caret#498]
### Type of issue (choose one):
  - [X ] Feature request

### Description

Would like to see native support and syntax highlighting for the Swift programming language from Apple.

### Additional notes

swift.org

### System details

Version 48.0.2564.116 (64-bit)
Platform 7647.84.0 (Official Build) stable-channel samus
Firmware Google_Samus.6300.174.0

**Comment by thomaswilburn** [comment]
When it's in Ace, we'll roll it out. We can't do it before then.
