### ISSUE TITLE
Addition of Fountain Syntax Highlighting

### ISSUE THREAD

**Issue by peterjhaas** [thomaswilburn/Caret#499]
### Type of issue (choose one):
  - [ ] Bug
  - [X ] Feature request
  - [ ] Question

### Description

Would love to see the addition of Fountain (www.fountain.io) syntax highlighting added. 

### System details

Acer 201 Chromebook

**Comment by thomaswilburn** [comment]
I don't see Fountain in the list of supported syntax from Ace. When it's there, we'll support it.
