### ISSUE TITLE
ES6 updates

### ISSUE THREAD

**Issue by thomaswilburn** [thomaswilburn/Caret#503]
A lot of ES6 features are rolling out. We should be updating the code to match (and modules can't come soon enough).
- Default params (49)
- Destructuring (49)
- Rest params (47)
- Spread (46)
- Arrow functions (45)
- Object literals (42)
- Template strings (41)

In general, I'm comfortable using any features that are older than stable - 5 releases.

**Comment by thomaswilburn** [comment]
Async functions are a big one, they shipped in 55 and so we should be able to use them in 60.

**Comment by mattlockyer** [comment]
Hello, I've been having trouble with the linter using some features like this (don't know name):
```
class Foo {
  state = {
    open: true
  }
  ...
}
```

The linter goes crazy and red ticks everything in the class after that.

This is a really popular style for react components so it would be useful if we could control / overrride / update the linter. Thanks!

**Comment by mattlockyer** [comment]
Upon looking into it, ACE supports jshint and not eslint.

What would it take to use eslint instead? Is there a plugin available?

**Comment by thomaswilburn** [comment]
JSHint comes built into the editor, and we just piggyback off that. If you wanted to use ESLint, you'd probably need to file a bug with Ace. You could also try using the plugin API to implement it in Caret without having to edit the source--we are probably missing some necessary hooks, but it's a great chance to find holes in our plugin functionality.

**Comment by mattlockyer** [comment]
I would love to dig into the plugin stuff when I have time. Thanks so much it's a great editor!

**Comment by mattlockyer** [comment]
Update: if you'd like to use certain features not supported by jshint you can add:

  `// jshint ignore: start`

  `// jshint ignore: end`

To your file, but once added you have to reboot jshint by turning webworker off, and then on again.

Once those lines are in your file and you've rebooted, you can move them up and down and they will ignore errors as expected.
