### ISSUE TITLE
Deprecate custom themes

### ISSUE THREAD

**Issue by thomaswilburn** [thomaswilburn/Caret#504]
This has to go.

**Comment by thomaswilburn** [comment]
These are now marked in the changelog for deprecation. When the next version rolls out, people will get this notice. We should remove the feature 30 days from that point, unless there's a lot of feedback to the contrary.

**Comment by NoahVlncrt** [comment]
Custom themes? Does this mean the option for ace themes? I only ask because i'm using the monakai theme and i'm loving it.

What's your reasoning for deprecating them?

**Comment by thomaswilburn** [comment]
No, the themes that come from Ace will stay. The "custom theme", where users can specify a JSON array that gets turned into a stylesheet, will go away, because it's a pain in the ass. But any of the named themes that exist now will stick around.

**Comment by NoahVlncrt** [comment]
okay that's awesome too hear :)
