### ISSUE TITLE
Cursor position is show in wrong place

### ISSUE THREAD

**Issue by xmesaj2** [thomaswilburn/Caret#507]
### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

*What steps cause the problem to occur? Are there any particular settings or configurations that are required in order to reproduce it?*

Opened the editor some day and it bugged out, custom settings are just dark theme and nothing else. Affects any filetype.

### Description

*If this is a bug, what would you expect the correct behavior to be? If it's a feature request, what do you want Caret to do? Are there other examples of this feature that I could look at? Screenshots are always helpful.*

![Screenshot of cloud9](https://cdn-standard.discourse.org/uploads/trydiscourse4/original/1X/6005a544bc1e8ce55d879621b0ff049bf620b0fb.png)

The cursor is shown in wrong position than you are typing. Screenshot comes from cloud9 but that's exactly same issue with Caret and other Ace editors

### Additional notes

*If this is a bug, is there anything else I should know? If it's a feature request, any caveats I should keep in mind?*

There's a workaround which works with other Ace editors (codecademy, cloud9)

```
@charset "utf-8";

.ace_editor, .ace_editor *
{
    font-family: "Monaco", "Menlo", "Ubuntu Mono", "Droid Sans Mono", "Consolas", monospace !important;
    font-size: 12px !important;
    font-weight: 400 !important;
    letter-spacing: 0 !important;
}
```

### System details

*Please provide your Chrome version and operating system here.*
ChromeOS 50.0.2661.79 beta (64-bit)
Platform 7978.57.0 (Official Build) beta-channel quawks
Google_Quawks.5216.204.61

**Comment by thomaswilburn** [comment]
Proportional fonts are not supported. Change to a monospaced font.

**Comment by xmesaj2** [comment]
When I set in user.json 

"fontFamily":"monospace"

it's bugged, with a clean attribute it's the same

with

"fontFamily":"Droid Sans Mono"

it's fine, so I'll keep using this for now

**Comment by thomaswilburn** [comment]
Okay, that's weird. I'll keep an eye on it, but there shouldn't be any reason that "monospace" should trigger a proportional font.

**Comment by xmesaj2** [comment]
It worked few weeks ago, I think they changed something in chrome regarding fonts
