### ISSUE TITLE
undo doesn't clear the 'file not changed' flag

### ISSUE THREAD

**Issue by unic0rn** [thomaswilburn/Caret#511]
### Type of issue (choose one):
  - [X] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

enter some text. undo. active file tab still shows unsaved changes, when closing the file caret asks if it should save or discard.

### Description

obviously, it should recognize the undo. not sure if it's ace-related issue or a bug in caret.

### Additional notes

using vim mode, but same thing happens when choosing undo from the menu.

### System details

windows 7, latest chrome canary.

**Comment by thomaswilburn** [comment]
No, we don't do particularly deep tracking of the modified file flag, and that's not likely to change. A big part of the design goal for Caret is to run on very low-spec machines, so the less work we can do on any given key press, the better.

**Comment by unic0rn** [comment]
and i can live with that. i've switched from atom (editing was actually very fast, but the UI was often just sluggish) to caret and on my single core athlon 64, even under moderate load from other apps, caret just flies.
