### ISSUE TITLE
contents of user preferences aren't dynamically generated based on config/user.json?

### ISSUE THREAD

**Issue by unic0rn** [thomaswilburn/Caret#512]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [X] Question

### Test steps

install caret from github repo, add it to chrome in developer mode. launch it, customize your user.json via settings/user preferences. then add some changes to config/user.json, like adding new theme to the list. restart caret, open user preferences. changes aren't there.

### Description

this is probably a stupid question, but since i'm not familiar with chrome API and stuff, i've decided to ask instead of digging my way through the code. how is this supposed to work? what if you'll decide to change something in config/user.json and then push the new release to chrome webstore - existing users won't see the change in that file? if so, that's a problem.

### System details

windows 7, latest chrome canary.

**Comment by thomaswilburn** [comment]
When Caret loads preferences, it performs three steps:

1. Load the default configuration from the file.
2. Load the user configuration from sync storage (if it exists).
3. Perform a shallow merge of the two config objects and return that as the actual config used by various app modules.

There's no reliable way, I think, to track changes in the defaults and flawlessly merge them into the user's preferences (if Git can't do it, I certainly can't), so we don't try. That does mean that a user doesn't see their personal preferences change after I push a change to the store. But the underlying defaults are updated, if they want to check there, and most new settings do take effect thanks to the settings merge.

**Comment by unic0rn** [comment]
i understand, i was just wondering. still, it seems a bit weird. as i've mentioned, i've added a theme to the list of themes (the ones from ace - i'll be submitting it to the ace repo, but i'm developing it on my own branch of caret), and user preferences don't show it. of course, it shows on the list when i click the theme name in the corner, but not in the comment in user config. not a deal breaker, but inconvenient/a little bit weird.

**Comment by thomaswilburn** [comment]
If it helps, I strongly suspect that most people never actually open the preferences. Also, if someone hasn't made any changes or resets their config, it'll pull in the defaults with the changes you've made. It's not a perfect system, but it's largely the same as the way VS Code/Sublime handle their config files, so I'm willing to live with it.

**Comment by unic0rn** [comment]
good point about resetting the config, it's not a bad method to check what's new. and yeah, it's far from being a disaster - i've been through most things - jedit, scite, emacs, vim, atom - and caret does the job best for me.

the only thing that may be missing is an indicator of current encoding, clickable to change it. but i guess  that's more on the ace side of things.
