### ISSUE TITLE
Convert Wrap to CR/LFs command 

### ISSUE THREAD

**Issue by xdrwedc** [thomaswilburn/Caret#513]
### Type of issue (choose one):
  - [x ] Feature request

### Description

Hello Thomas, could you consider adding two convert commands: 1) Convert Wrap to CR/LFs command. 2) Convert CR/LFs to Wrap command. FYI: http://www.ultraedit.com/help/article/convert-wrap-to-cr-lfs-command-1427.html and http://www.ultraedit.com/help/article/convert-cr-lfs-to-wrap-command-1426.html

**Comment by thomaswilburn** [comment]
I'd be happy to take a pull request for the latter, although I always just use Ctrl-J to join lines together. For the former, we have the Alt-Q keyboard shortcut, which wraps text to margin.
