### ISSUE TITLE
folding behavior in markdown mode

### ISSUE THREAD

**Issue by academyofzhuang** [thomaswilburn/Caret#516]
Given this markdown snippet

```` markdown

# article 1
A Paragraph.
## level 2
A Paragraph.

# article 2
A Paragraph.
````

When I click the fold icon at the left of article one, I expect it to fold all lines till article 2.  Current behavior is to fold all lines till level 2.

My expectation is also in line with emacs markdown/org mode.

Besides, can we have an menu item or shortcut for foldAll÷

Would you please make a change?

**Comment by thomaswilburn** [comment]
You'll need to file this against Ace, I don't really control the folding behavior.

As for the foldall menu, that's something you should be able to do yourself--I'm pretty sure there's an Ace command for that, and you can just add it to whatever menu you want.

**Comment by academyofzhuang** [comment]
Thank you! Will report this to Ace repo.
