### ISSUE TITLE
Text uncollapsing

### ISSUE THREAD

**Issue by HoutarouOreki** [thomaswilburn/Caret#517]
### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

With an html file:
 0. Editing a file
 1. Collapse text (arrows on the left)
 2. Save the file
 3. Open page in browser
 4. Return to Caret
 5. All the text goes uncollapsed

https://youtu.be/M9RuQu8MtMU

### System details

 Windows 10 64-bit
 Chrome 50.0.2661.102 m

**Comment by thomaswilburn** [comment]
Interesting! I'll look into it. Thanks for the report.

**Comment by thomaswilburn** [comment]
I'm not able to duplicate this at all. Some questions:

* Does this only happen when you open the file, or does it happen every time that Caret regains focus?
* Does the cursor position change anything - if you interact with the file or move the cursor around, can you prevent this?
* Are there any messages that show up in the dev tools if you turn on app inspection in chrome://flags?

I think this may be an Ace issue, but I'd like to get more information before I file a bug against them.

**Comment by HoutarouOreki** [comment]
- It happens after saving the file and Caret regaining focus. I was wrong about having to open the file there.
- Just checked. I can prevent it by modifying it after saving. After regaining focus 
it asks to reload the file. After reloading the cursor position goes back to beginning and text gets uncollapsed. If I choose "Cancel" it stays collapsed and cursor stays in the same place.
- I'm not good at these things.. I can't find anything as app inspection chrome://flags and neither do I know where are dev tools (and probably how to use them). Sorry.

**Comment by thomaswilburn** [comment]
Okay, so this sounds like a problem with something on your system triggering the auto-reload functionality. If you're going to continue working this way directly from the filesystem, it may make sense to set `"disableReload": true` in your user preferences--there's no other way for us to prevent it, given that something is changing the modification time on that file when you open it. It may be better to use a local server, such as Node's `http-server` module, to get around this issue.

**Comment by HoutarouOreki** [comment]
Ok, it stopped happening after setting `"disableReload":true`.
