### ISSUE TITLE
Spell Check?

### ISSUE THREAD

**Issue by glynhudson** [thomaswilburn/Caret#518]
Sorry for raising this request again, I am aware of your response to an identical request one year ago #403. Have any Chrome API's changed in the last 12 months which make adding a spell checker a viable prospect? 

As a dyslexic developer I *really* need spell checking in my text editor and a love Caret and my Chromebook but end up pasting into open-office at work just to check selling, this is crazy!   Searching the repo there are [mentions to SpellChecker](https://github.com/thomaswilburn/Caret/blame/0d790c9da42f60011e83ba6ad81a05247ff9368c/js/ace/mode-praat.js#L92), are there any plans to work on such a feature? I would be happy to help where I can.

**Comment by thomaswilburn** [comment]
Sadly, no, the Chrome APIs actually haven't been touched (as far as I'm aware) during the last year or so. The references you've found are for keyword highlighting in one of the Ace syntax modes.

I will repeat what I say whenever this comes up, which is that a spellchecker would be a great test-case for improving the plugin API if someone wanted to tackle that. There are almost certainly APIs that we would need to add to support this task, and I'd be happy to take pull requests or bugs to add them once someone determines what they are.
