### ISSUE TITLE
ftp

### ISSUE THREAD

**Issue by bios-transspecies** [thomaswilburn/Caret#519]
please... ftp now :) i love this editor but i work most of the time with remote ftp connections

**Comment by grit96** [comment]
If you have the FTP connection mounted on your system you can open remote files like any local files.

**Comment by bios-transspecies** [comment]
its not so easy on windows to mount ftp :)


W dniu 2016-06-07 12:00, Geraint White napisał(a):
> If you have the FTP connection mounted on your system you can open
> remote files like any local files.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread 
> [2].
> 
> 	*
> 
> Links:
> ------
> [1] 
> https://github.com/thomaswilburn/Caret/issues/519#issuecomment-224235298
> [2]
> https://github.com/notifications/unsubscribe/AJP1VTVfKG2MzqvGNdK37fBk-ALO7GTxks5qJUFQgaJpZM4IvqNM

-- 

HTTP://MICHALBRZEZINSKI.ORG
MICHAL@MICHALBRZEZINSKI.ORG

+ 48 505 202 294

http://www.artysci-lodzkie.pl/pl/artysta/b/michal-brzezinski/
http://www.artysci-lodzkie.pl/en/artist/b/michal-brzezinski/
https://www.facebook.com/postvideoart
https://www.facebook.com/Biocultureartlab

**Comment by thomaswilburn** [comment]
I've always heard good things about Expandrive for mounting SFTP as a network share. Regardless, this will not be added to Caret.

**Comment by Mortuus-Medicus** [comment]
I too would love to see an ability to connect via FTP and then edit files that way!

**Comment by YemSalat** [comment]
@Mortuus-Medicus as noted above - you can just mount the remote drive on your OS and edit files on it like local ones.

**Comment by Mortuus-Medicus** [comment]
@YemSalat I guess you could do that, but it would be so much cleaner, easier and better if the program supported that, and it would mean that you don't need another program, just to achieve that.
What about the Google Drive support?

**Comment by grit96** [comment]
Use the desktop Google Drive application to sync one of your local folders.

**Comment by Mortuus-Medicus** [comment]
@grit96 But that's just another program to use...
Also, I don't think it's supported on all platforms (I don't know for Caret either), 
Wouldn't it be cool, to just have a simple solution?
And if it supported FTP it could actually be used in production!
Which would be grand ^^

**Comment by thomaswilburn** [comment]
It's not cleaner for Caret to absorb myriad file system protocols (Drive, FTP, etc) when there's a perfectly good extension system built into Chrome OS for mounting different storage systems so that all programs (including Caret) can access them just like normal files.

I believe Caret works best when it behaves according to the UNIX philosophy of small tools that do one task well. In this case, that task is file editing, not remote storage.
