### ISSUE TITLE
Context menu for project tree items

### ISSUE THREAD

**Issue by richiksc** [thomaswilburn/Caret#520]
### Type of issue (choose one):
- [ ] Bug
- [x] Feature request
- [ ] Question
### Test steps

Open a project. Right-click a directory or file in the project tree.
### Description

A context menu should pop up allowing you to create a new file in that directory, delete the file or directory (with confirmation dialog), or rename the file/directory. I've found this behavior in every proper code editor I've used and am missing it in Caret.
### System details

52.0.2743.32 (Official Build) beta (64-bit)

**Comment by thomaswilburn** [comment]
This is not a bug, it's a feature request.

The project panel has been perpetually under rewrite for a while now, and both of these would be impacted by that work (they both require us to update the directory tree to match new changes in the file system). We are hampered here a bit by the fact that the Chrome filesystem APIs have stalled, and do not include any watch functionality.

If you'd like to pick this up, feel free to clone on the `project-rewrite` branch and see if you can work it in.

**Comment by richiksc** [comment]
Thanks for the reply, I'll clone the 'project-rewrite' branch and see what I can do with it. So there is no watch functionality to update the directory tree from changes in the file system, but you _can_ update the file system from the directory tree, just that functionality is missing. I do Chrome App dev (sometimes) so I know the frustration with the APIs.
