### ISSUE TITLE
Showing Hidden Files

### ISSUE THREAD

**Issue by NoahVlncrt** [thomaswilburn/Caret#522]
Right now I work with MeteorJS and it is all fine and dandy the only problem is there is a specific folder I would like access to but It is not showing up in the directory tree. The folder begins with a . and i'm not sure how I can make files like that show up?

### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

### Test steps

Just open it up with a hidden folder in your directory

### System details

ChromeOS latest, HP Chromebook 14

**Comment by thomaswilburn** [comment]
We intentionally don't dive into dot folders, I think to avoid having to reverse through .git, which is a mess that almost no-one wants to manage manually. I can probably make that a toggle, for cases like yours.

**Comment by NoahVlncrt** [comment]
I would absolutely love it as a toggle that would be awesome. Thank you so much!

**Comment by NoahVlncrt** [comment]
thank you so much
