### ISSUE TITLE
Jade to PUG Js

### ISSUE THREAD

**Issue by Kelseer** [thomaswilburn/Caret#524]
### Type of issue (choose one):
- [ ] Bug
- Feature request
- [ ] Question
### Description

So Jade, a templating engine, has recently had to change its name to PugJS due to trademark issues, and this has included their filetype going from '.jade' to '.pug'  Right now while using Caret, I just rename the files ".jade" so that I can get the syntax highlighting, but it'd be nice if .pug was supported!

There is also apparently some syntax differences, which are documented here: https://github.com/pugjs/pug/issues/2305

Sorry if this is not a valid place to put this :)

**Comment by thomaswilburn** [comment]
Okay, I'll add it to the extension list when I get a chance. Any syntax changes will have to come from upstream.
