### ISSUE TITLE
jsHint/Ace options?

### ISSUE THREAD

**Issue by mattlgy** [thomaswilburn/Caret#525]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

Is there a config option for passing settings to jsHint or Ace?

I forgo the use of semicolons in my JavaScript code and thus have ___i___ icons on almost every line. I'm assuming these are bubbling up from Ace's built in jsHint. Ace has methods for configuring its instance of jsHint and I was wondering if there is a way to pass config options down to it via the json config files.

While not a huge issue, I feel that Caret is judging me for my life decisions. And legitimate linter issues get lost in the noise.

**Comment by thomaswilburn** [comment]
You can send options to the worker manually from the console, but there's no option exposed for doing it from Caret. Right now I think your only option would be to use one of the inline jshint configuration directives at the top of your file, like `/* jshint asi:true */`

**Comment by mattlgy** [comment]
Hey, thanks for the quick response!

Yeah, for now I am using comment method for settings. Would you be open to a PR to add something like:
```json
...
  "jsHint": {
    "asi": true,
    ...
  },
...
```
to the use prefs?

**Comment by thomaswilburn** [comment]
Sure, as long as it plays nice with people like me who turn the worker off, and as long as you can future-proof it somewhat (my understanding is that posting to the worker is kind of a private API, and isn't considered stable).
