### ISSUE TITLE
Automatically refresh project directories.

### ISSUE THREAD

**Issue by YemSalat** [thomaswilburn/Caret#531]
### Type of issue (choose one):
  - [x] Feature request

### Description

I think it would be great if Caret would automatically refresh the list of directories after you add / remove sidebar items, perhaps also do it regularly on some delay.

As a slightly separate thing, I think we could tweak the current implementation a bit.
I found this: https://developer.chrome.com/apps/fileSystem#type-ChildChangeType <- but the info is not very useful. Anyone has more details on watching filesystem changes in chromium by any chance?

**Comment by thomaswilburn** [comment]
My understanding is that filesystem watch is stalled out in Chromium (they've shifted focus to ServiceWorker instead, and probably rightfully so), and as a result we're unlikely to implement this, because I don't want to write our own watch from scratch.
