### ISSUE TITLE
[Enhancement] UI Reformation

### ISSUE THREAD

**Issue by Blue-EyesWhiteDragon** [thomaswilburn/Caret#533]
The top bar does not show any pointer-events or a "click event" cursor on hover.

Also the minimise, maximise and close icons are not very descriptive of their actions, maybe try changing them back to the default or use material icons to make a more obvious and interactive top bar?

Also consider following W3C HTML5 spec and change:
`<div class="titlebar">...</div>` to `<header class="titlebar">...</header>`
`<div class="central">...</div>` to `<main class="central">...</main>`
`<div class="bottom-bar">...</div>` to `<footer class="bottom-bar">...</footer>`

([HTML5 Semantics](https://www.w3.org/TR/html5) check Section 4)

**Comment by thomaswilburn** [comment]
The icons aren't changing. There's been other discussion about this, and I know they're a little obscure, but I've become attached to them and there's alt-text if people are confused.

Why should the top bar show a different cursor? There's no OS convention that non-link event targets should trigger a different mouse appearance. We could probably do a little better with hover state. I'd be happy to take pull requests to that effect.

**Comment by Blue-EyesWhiteDragon** [comment]
@thomaswilburn 
[1] I don't mean to offend but why would a personal attachment to a icon set be more important than the usability of the application that's in development?

[2] I personally think that a pointer-event or background-color change would be nice: it would show that the menu item can interacted with. Obviously, that being said, this is not a necessity.

**Comment by Blue-EyesWhiteDragon** [comment]
For the top bar it is a simple job of: 
`.toolbar > li:hover {
    background-color: rgba(0, 0, 0, .25);
    /* cursor: pointer; */
    transition: background-color .1s ease-in-out;
}`

**Comment by thomaswilburn** [comment]
Like I said, file a pull request and I'll take a look. You'd need to be able to handle the different light/dark themes, so it needs to be something you can do in LESS, not just CSS for a single theme. I don't think it's a huge deal, personally.

As far as the icons go, you're welcome to fork if you want to change it (other people have). But I don't get paid for this, so personal preference actually gets to count for a lot.

**Comment by Blue-EyesWhiteDragon** [comment]
@thomaswilburn
[1] I will do that.

[2] OK, I understand your position now.

**Comment by richiksc** [comment]
How about a config option for the icons?

**Comment by thomaswilburn** [comment]
Nope.
