### ISSUE TITLE
How to preview my code?

### ISSUE THREAD

**Issue by TK0805** [thomaswilburn/Caret#537]
I just got Caret, and am using it to program (and learn) C++. However, when I finished my first program, i didn't know how to run it. If it is not already a feature, would there be a way to make it one? I am programming on a Chromebook, so there isn't really any other good programs I could use to view it.

**Comment by thomaswilburn** [comment]
For C++, Caret can't help you run that code--we're not a compiler, and you can't deploy C++ code on Chrome OS. If you really want to do this on a Chromebook, I would recommend putting the machine in dev mode and installing Crouton, which would give you a full Linux environment where you can run GCC.

**Comment by swimjoshswim18** [comment]
I'm having the same problem, but I am programming in JavaScript
