### ISSUE TITLE
Add dark Chrome theme

### ISSUE THREAD

**Issue by metarmask** [thomaswilburn/Caret#538]
### Type of issue
Feature request

### Description
[A dark theme was added to DevTools](https://developers.google.com/web/updates/2016/02/devtools-digest-devtools-go-dark#a_dark_theme_for_devtools). I would like to see a theme like it added.

**Comment by thomaswilburn** [comment]
How would this be different from the two dark themes we already have?

**Comment by metarmask** [comment]
It would match the application I spend the most time in other than Caret just like the Chrome theme did before I started using the dark theme was added to DevTools.

**Comment by thomaswilburn** [comment]
Ah, you mean you want a syntax theme. That needs to be filed against Ace, and then we'll pull from upstream.

**Comment by metarmask** [comment]
Oh... Thanks!

**Comment by brismuth** [comment]
Caret also already has some dark themes, although they won't be identical. I like the builtin "chaos" theme quite a bit.

![image](https://cloud.githubusercontent.com/assets/5679695/19358706/18bbdee0-9134-11e6-9b37-f24a9d225d08.png)

**Comment by brismuth** [comment]
Try out "Clouds at Midnight", "Merbivore", "Monokai", "Terminal", and "Tomorrow Night"

**Comment by Blue-EyesWhiteDragon** [comment]
@brismuth Tomorrow Night Eighties is my favourite.
