### ISSUE TITLE
Unsual spacing of blinker while typing in linux mint sarah.

### ISSUE THREAD

**Issue by coolrohit** [thomaswilburn/Caret#539]
I have just installed Linux Mint sarah into my system. As I started working with caret, something unsual is happening. While I am typing , the blinker is going away from the letters. For example:
If I type "a" the blinker will be at "a |" and it goes on like this:
```
"ab  |"
"abc   |"
"abc    |"
"abcd    |"

```
Please tell if there is a known setting to tackle this issue or fix this issue immediately.

**Comment by richiksc** [comment]
Since you have Linux mint, I suggest using a full featured text editor. A
good one is the open source Atom text editor.

**Comment by thomaswilburn** [comment]
Chances are the distro you're using is setting a non-monospace font for some reason. Ace freaks out on proportional fonts. Try changing the font in the settings, and seeing if that fixes it, then let me know and I can add that font to our default stack.

**Comment by coolrohit** [comment]
Yes it worked after setting the font_family to its default value. I had changed it to consolas.
