### ISSUE TITLE
Treebrowser in Caret

### ISSUE THREAD

**Issue by coolrohit** [thomaswilburn/Caret#542]
I have a feature request for enabling treebrowsing in caret. It really helps a lot for any coder using caret to navigate to files quickly while working in a project and have a more seamless flow of operations.

**Comment by coolrohit** [comment]
Okay I figured this out by adding the project directory and it opened all the subfolders and files in the sidebar. But I was expecting to right click any folder in the sidebar and create a new folder , but this right-click option is not there. Can some more functionality be added to this in addition to displaying the files?

**Comment by thomaswilburn** [comment]
Save a project file. That's what Caret uses to retain the project panel file handles.

**Comment by KrazyKolsen78** [comment]
Yea and there is a a bunch of hikers here wanting to talk to you and you
buddies and they are not happy
