### ISSUE TITLE
File synchronisation in side bar

### ISSUE THREAD

**Issue by coolrohit** [thomaswilburn/Caret#543]
- [ ] Question

While working in my project directory I noticed that whenever I create a new file from outside caret, it does not get synchronised in the side bar. I have to close and reopen caret for the file to appear in the side bar. 
Please tell me if there is a way to do this or we do not have the functionality for it yet.

**Comment by thomaswilburn** [comment]
This is an old, known issue. Check out #165, #252, and probably a ton of closed issues for more information.

**Comment by TheThirdOne** [comment]
There is a Refresh command in the command palette (Project > Refresh directories). That command is the preferred way to reset the sidebar after adding, moving or deleting a file.

**Comment by thomaswilburn** [comment]
Ah, thanks, I should have added that. Yes, you can refresh the folder using the command above. We just can't do it for you automatically, because Chrome doesn't provide any file watch capabilities, and polling would be a huge performance issue on the main thread.

**Comment by coolrohit** [comment]
Oh thanks TheThirdOne. I should have reviewed my query thoroughly before posting. And thanks thomaswilburn for pointing out the same.
