### ISSUE TITLE
Ace to Monaco editor migration. 

### ISSUE THREAD

**Issue by fgblanch** [thomaswilburn/Caret#548]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

### Description

Does it make sense to migrate the caret editor to the Microsoft Monaco editor (the one behind VSCode)?

### Additional notes
As VSCode is getting more and more popular, and following this discussion 

https://github.com/Microsoft/monaco-editor/issues/19

It has many features that would be interesting in Caret, i was wondering if it would make sens to migrate the Caret editor from ace to Monaco. Thanks

### System details

ChromeOS 56

**Comment by thomaswilburn** [comment]
It probably doesn't make a lot of sense. It would be a lot of work, considering the integration into Ace that we're already using, and it's not clear to me what the benefit would be. Most of the things listed in that post are part of the "chrome" around Monaco, and not features of the editor itself.
