### ISSUE TITLE
How to add custom uiThemes?

### ISSUE THREAD

**Issue by lw1990** [thomaswilburn/Caret#549]
I use the chromeapp version of Caret, is it possible to add custom uiThemes or alter existing ones easily, or do I have to download the source and make my own instance of Caret to do this?
Are there more than the three uiThemes in the commented user preferences file? I only see //dark, twilight, or light but there seems to be at least four themes displayed on the gif at thomaswilburn.net/caret/

I'm mainly trying to get rid of the awful purple for the light theme, replace it with a grey, so that it plays nice with the dark Ace themes, purple is so hard to match

**Comment by thomaswilburn** [comment]
In order to change the theme, you do need to run Caret from source. There are only three of them. The seed.less file defines variables including the accent color, and you can use that to change the purple if you don't care for it.
