### ISSUE TITLE
immersivefullscreen = true doesn't appear to work for the chrome app

### ISSUE THREAD

**Issue by lw1990** [thomaswilburn/Caret#551]
Using Caret as a chromeapp, `"immersiveFullscreen": true, //hides menus/tabs in Chrome OS fullscreen mode` doesn't appear to do anything different when I maximize Caret, the titlebar is still shown

**Comment by thomaswilburn** [comment]
What platform are you on? That mode only works, as far as I know, when you use the fullscreen button on Chrome OS. I'm not sure if there's an equivalent button on other platforms.
