### ISSUE TITLE
JSHint options are not used in JS tabs

### ISSUE THREAD

**Issue by null-dynamic-exception** [thomaswilburn/Caret#553]
When using a tab with javascript syntax and the "jsHint" config option defined, JSHint does not appear to take into account the defined settings. For example, with the config option
```json
"jsHint": {
  "asi": true
}
```
and foo.js
```javascript
(function() {
  foo
  bar
})();
```
JSHint still marks `foo` and `bar` with `Missing semicolon.`

Stepping through the code in Dev Tools, it seems like the problem is that Caret doesn't call `Tab.prototype.detectSyntax` before calling `Tab.prototype.$startWorker`, leaving `Tab#syntaxMode` undefined when the check for the syntax mode is made.

Hopefully I'm not the only one with this problem. Thanks!

**Comment by thomaswilburn** [comment]
I don't actually use the jsHint stuff, so I have no opinion on this, but if you want to file a pull request for it, I'd happily accept.
