### ISSUE TITLE
Persistant scratchpad

### ISSUE THREAD

**Issue by Olivered** [thomaswilburn/Caret#555]
### Type of issue (choose one):
  - [X] Feature request

### Test steps
None

### Description
Could you implement a persistent scratch cache in ~/downloads?
Procedure : User activates caret via "create a new file".
User clicks a button in the file menu marked "save file as scratch".
Additionally, if user creates a new file and forgets to save it, and
doesn't have a scratch file, caret saves it as the scratch file.
Caret auto-saves every second or so any revisions to this file.
If the program is closed, the file is saved.
On subsequent open, caret checks for this file, and in addition
to whatever other file opens, caret opens the "scratch file".
The feature could be disabled by default and as an option.

### Additional notes
There are a lot of "notes" apps out there who retain a persistent
cache of text edited. However, only textedit on osx really does it properly.
Most powerusers want a simple ascii notepad that can remember some text.
It might be strings from the web, a set of clipboard entries, etc.
I would really enjoy this feature!

**Comment by thomaswilburn** [comment]
Why not just save a scratch file yourself and turn on auto-save? I don't really see why we would need to add a new feature just for this use case.
