### ISSUE TITLE
Only delete multiple spaces at once in indentation portion of line

### ISSUE THREAD

**Issue by anowlcalledjosh** [thomaswilburn/Caret#557]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

### Test steps

Set `useTabs` to `false` and `indentation` to `2`, then enter some text with two spaces in the middle:

```
ab  cd
```

Delete the text starting from the end, and observe that the two spaces are deleted with one keypress.

### Description

I would expect one space character to be deleted at a time when there are non-whitespace characters between the cursor and the start of the line.

### Additional notes

This only happens when the cursor is on a tabstop character; the following text works how you would expect:

```
abc  de
```

### System details

Chrome 57 on Chrome OS

**Comment by thomaswilburn** [comment]
Yeah, I've noticed this kind of thing. It's a bug in Ace, though, not in Caret. If you file it against them, and they fix it, we'll pull from upstream.

**Comment by anowlcalledjosh** [comment]
Ok, I've opened ajaxorg/ace#3247.
