### ISSUE TITLE
[Feature Request] Run Project

### ISSUE THREAD

**Issue by MauricioModelit** [thomaswilburn/Caret#560]
Just wanted to know if there's a plan to implement a "Run Project" or "Run File" tool that opens the current file (or the project's entry point) in the default web browser either by file or opening a port.

I'm using a Chromebook to work in some projects that don't need heavy back end running tools and Caret is my go-to text editor, since Chrome Dev Editor was left without maintenance and bugs are everywhere. So, in that context, opening a file via the search bar is not as trivial as in other OS's.

Thanks!

**Comment by thomaswilburn** [comment]
I haven't been able to find a reliable way to open a file from Caret, so this has not been something that we've added. I also generally am hesitant to tie Caret to "opening HTML files" as a default action--after all, you may open them directly, but I do so by navigating to a server on localhost, which is arguably a better habit to encourage. I highly recommend the Node `http-server` module as a quick way to spin up a file server: you'll have an easier time of working on pages when you're not subject to the security restrictions of the `file://` protocol.
