### ISSUE TITLE
Rights for wiki editing?

### ISSUE THREAD

**Issue by ipstone** [thomaswilburn/Caret#561]
Hi Thomas and everyone - I am trying to add an entry on the wiki page to indicate that keyboard setting (vim mode) can use "imap jk <Esc>"; but didn't find the right to edit the page. Is it purposely locked down?

Thanks, 
Isaac

**Comment by thomaswilburn** [comment]
Yes, only contributors can edit the wiki. You can fork and send a PR, if you want. I guess that means it's not a real wiki, but neither is Wikileaks, so what can you do?

**Comment by ipstone** [comment]
But I think the wik on github is not part of the code repository - even if I ask for the PR, it won't be merged in.

**Comment by thomaswilburn** [comment]
A GitHub wiki is just a repo of its own. You can clone it directly.

-----Original Message-----
