### ISSUE TITLE
Javascript Linter doesn't work in <script> element of html file

### ISSUE THREAD

**Issue by mutlucan96** [thomaswilburn/Caret#564]
### Type of issue (choose one):
  - [ *] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

*Problem occurs always.

### Description
Javascript Linter works on .js files. But it don't work embedded javascript on a .html file.

### System details
Chrome 57.0.2987.133 (64-bit)
Ubuntu 17.04

**Comment by thomaswilburn** [comment]
This is a bug with Ace, please file with them.
