### ISSUE TITLE
How to 'translate' vim command into Caret settings?

### ISSUE THREAD

**Issue by ipstone** [thomaswilburn/Caret#565]
Hello, I have a vim command works well in the vim mode: imap jk <Esc>
which correctly maps key sequence jk to Esc.  I am wondering how to save this into the Caret setting?
Thanks,
Isaac

**Comment by thomaswilburn** [comment]
I'm not sure. Vim mode is not something I support, personally--it's there, and I let users enable it, but I don't use it or test it at all. You may want to ask the Ace devs if they have any suggestions.
