### ISSUE TITLE
Caret autocomplete box and font is tiny

### ISSUE THREAD

**Issue by thelastprime** [thomaswilburn/Caret#566]
### Type of issue (choose one):
 Bug

### Test steps

Whenever I use Caret, I can zoom in and change the font, but the autocomplete box doesn't change. It shows up in weird places and the text is way too small.

### Description

The autocomplete font size should be the same as the rest of the document.

### System details

Version 57.0.2987.133 (64-bit)
OSX El Capitan 10.11

**Comment by thomaswilburn** [comment]
This is something Ace can handle, not us.

**Comment by thelastprime** [comment]
How do I contact Ace?

**Comment by thomaswilburn** [comment]
Their repo lives over at ajaxorg/ace, I believe.

**Comment by thelastprime** [comment]
Thanks! The editor is great!
