### ISSUE TITLE
Chrome update removes Caret App

### ISSUE THREAD

**Issue by SoftwUser** [thomaswilburn/Caret#567]
### Type of issue (choose one):

  - Bug

### Test steps

I installed Caret yesterday from the Chrome webstore for the very first time on Chrome 58.0.3029.96 which at that point had been the latest stable edition. Later this evening a Chrome Stable Channel update (to 58.0.3029.110) had been performed automatically. During this update the Caret App disappeared/has been removed. I had to re-install it from the Webstore.

### Description

I would have expected that the App had not been removed due to the Chrome update.

### Additional notes

./.

### System details

Windows 7 64bit, Chrome 58.0.3029.96 and 58.0.3029.110

Thank you!

**Comment by thomaswilburn** [comment]
I'm not in control of the Chrome store, and we didn't do anything to uninstall when Chrome updated. You'd have to file this bug with Chrome.
