### ISSUE TITLE
Latest release is missing

### ISSUE THREAD

**Issue by SoftwUser** [thomaswilburn/Caret#568]
### Type of issue (choose one):

  - Question

### Description

The App from the webstore is release 1.6.25.
However the latest release on 
https://github.com/thomaswilburn/Caret/releases
is 1.6.23.

Are the newest releases no longer provided (for local install purposes)?

Thank you!

**Comment by thomaswilburn** [comment]
I just forgot to tag the latest. But in general, I'd say that local installs should not rely on the release page. Instead, it's usually a better idea to just clone the repo, and use that for local installs. You can still check out based on a tag if you want to replicate a specific release.
