### ISSUE TITLE
Spell Checking

### ISSUE THREAD

**Issue by garygreeniwc** [thomaswilburn/Caret#571]
Love your app.  Would be great to have a spell checker, especially when writing markdown.

### Type of issue (choose one):
  - [ ] Bug
  - [X] Feature request
  - [ ] Question

### Test steps

- N/A

### Description

- While you type spell checking, especially for UK and US English

### Additional notes

- N/A

### System details

- Version 57.0.2987.133 (64-bit)

**Comment by thomaswilburn** [comment]
Unfortunately Chrome does not expose a spell check API for us to use.

**Comment by glynhudson** [comment]
Is there any way this could be achieved? I love Caret, but my spelling is terrible. Spell check would be very useful. 

Minimalist Markdown editor Chrome app supports spell checking: https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=en
