### ISSUE TITLE
Caret app in new tab

### ISSUE THREAD

**Issue by nri-pl** [thomaswilburn/Caret#573]
- [x] Feature request
  - [x] Question

Hi, I currently use the Caret App for Chrome on Linux.
The question seems to me to be trivial and probably someone has already asked, but I have not found an answer anywhere.
When I start the Caret App from "chrome://apps" it opens in a brand new window.

Is there any way to start Caret in a new tab?

**Comment by thomaswilburn** [comment]
Starting in v2 (circa 2014, I think) Chrome apps can't be launched in a typical browser tab. They have to have their own window, mostly for security reasons.

You wouldn't want Caret in a tab anyway, the menus would be all messed up because we keep those in the window frame.

**Comment by nri-pl** [comment]
It seems to me that it isn't true.
See, for example, Secure Shell app
"Terminal emulator and SSH client."
https://github.com/randunel/chrome-secure-shell
https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo

When I right click on it in "chrome://apps" I have option to open it in new window or new tab.

I have about 10 apps in my Chrome.
All have options to choose to open in a new custom window or in the new tab.
Except for Caret.

"the menus would be all messed up because we keep those in the window frame."
I do not understand what the difference is if the whole app will be packed in chrome decor.

**Comment by thomaswilburn** [comment]
Yeah, I looked at that. Secure Shell is leveraging an old API to launch that tab, one that was normally reserved for v1 "hosted apps." I suspect it's been grandfathered in, so that it can keep using that. None of the v2 apps on my Chromebook, like the Calculator or Camera, support being opened in a tab, and when I try to enable that option for Caret I get an error thrown saying that I'm not allowed to use it.

**Comment by nri-pl** [comment]
Thanks for the clarification.

So basically if I want to have a unified experience I should not use tabs in Chrome.
It's better to switch to system window managers with all web pages and applications.
