### ISSUE TITLE
Add common source file extensions

### ISSUE THREAD

**Issue by pascalschumann** [thomaswilburn/Caret#577]
### Type of issue (choose one):
  - [x] Bug

### Test steps

Have a .php file in a directory and you cannot open it with caret from Files (Chrome File Browser).

### Description

.txt and a lot of a other extensions are working, but for example .php isn't working.
Please register Caret for all the common source file extensions, you can take look at sublime and the extensions it can open.

### System details

Chrome OS

**Comment by thomaswilburn** [comment]
Caret registers for a wildcard MIME type in order to open any text file. If PHP isn't currently falling under that umbrella, it's a bug in Chrome OS, not in our code.
