### ISSUE TITLE
Support for multiple macros

### ISSUE THREAD

**Issue by coolrohit** [thomaswilburn/Caret#578]
Does caret support saving multiple macros? If not, how soon should we expect this feature to come out?
### Type of issue (choose one):

  - [ ] Feature request

### System details

Version 54.0.2840.100 (64-bit)

**Comment by thomaswilburn** [comment]
I don't have any plans to add it, and I don't think it's a fair question to ask "how soon should we expect this feature" when I didn't even know it was a feature people wanted. I think this is something that I would actually prefer people tried to implement using the plugin API, but I'm happy to entertain pull requests for something built-in as long as it doesn't violate the Chrome security model.
