### ISSUE TITLE
Question on how to send selected text to plug-in

### ISSUE THREAD

**Issue by DanShrader** [thomaswilburn/Caret#579]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [X] Question

### Description

I'm trying to build a plug-in that would look at the selected text or the editor contents, then do something and finally overwrite the selected text.  Thanks to those whom have posted their code in issues I've been able to build a simple plug in that inserts text into the editor, but picking up the current selection or whole file has eluded me.

Here's the gist of what I have

#### api.json
`
  "pluginName": {
    "id": "EtensionIDHere",
    "message": {
      "data": "date passed here.  Am I missing something here?"
    }
  }
`

#### push to Caret
`
var message = {
  command: 'editor:insert',
  argument: message.data,
  quiet: true
}
chrome.runtime.sendMessage("fljalecfjciodhpcledpamjachpmelml", message);
`

#### keys.json
`"Ctrl-Alt-U": { "command": "api:execute", "argument":"pluginName" }`

Any help would be appreciated.  If I can get this working I'll post a working example to help others

**Comment by thomaswilburn** [comment]
Your API config should also specify `sendEditorContext: true` to let Caret know that you want to include the current selection with the message. If you need additional context, feel free to file a pull request. Very excited to see someone using the message API.

https://github.com/thomaswilburn/Caret/blob/master/js/api.js#L28

**Comment by DanShrader** [comment]
Great, thanks that is what I needed!

Here's an complete example of a plugin if anyone else needs it.  Note it only takes the highlighted text and copies it to a new tab in Caret, but the general pattern is there.

#### api.json
` "pluginName": {
    "id": "extensionIdHere",
    "sendEditorContext": true
  }`

#### keys.json
`"Ctrl-Alt-U": { "command": "api:execute", "argument":"pluginName" }`

#### manifest.json
`{
  "manifest_version": 2,
  "name": "Caret Plugin: Copy to new tab",
  "description": "This plugin will take the selected text and copy it to a new window in Caret.",
  "version": "1.0.0",
  "background": {
    "scripts": ["background.js"]
  }
}`

#### background.js
`console.log("Extension loaded. Waiting on Caret...");
chrome.runtime.onMessageExternal.addListener(
  function(message, sender, sendResponse) {
    var alterMessage = message.context.selection;
    var sendMessage = {
      command: 'session:new-file',
      argument: alterMessage,
      quiet: true
    }
    chrome.runtime.sendMessage("fljalecfjciodhpcledpamjachpmelml", sendMessage);
  });`
