### ISSUE TITLE
Alt-Tabbing Sometimes Resets Undo and Redo

### ISSUE THREAD

**Issue by st3v1sh** [thomaswilburn/Caret#580]
- [x] Bug

**Description**
Sometimes, when I Alt-Tab, Undo and Redo resets so that I cannot undo any recent changes.

**System:**
Chrome version: 58.0.3029.110 (Official Build) (64-bit)
Windows version: 8.1

**Comment by thomaswilburn** [comment]
That's very odd. It may be tied to the auto reload behavior, depending on the way the filesystem reports back, so you might want to disable that and see if it fixes the problem.

**Comment by st3v1sh** [comment]
Thanks for the reply! I will try putting **disableReload** on true

**Comment by st3v1sh** [comment]
So far, everything has been fine! I think the problem has been solved.
