### ISSUE TITLE
Plug-in naming convention or listing?

### ISSUE THREAD

**Issue by DanShrader** [thomaswilburn/Caret#581]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

### Description

Hi @thomaswilburn ,

Thanks for your help earlier on #579 - I was able to get my plug-in working perfectly.  I'd like to share it with everyone, but didn't know if there was already a page that I may have missed with naming conventions, etc.  Also is there any page that I can add a link to so that others can find it?  I can do a pull request if so.

If there isn't a naming convention I'm thinking something like "Caret Plugin :: Pretty-JavaScript", so there is no confusion on what it is for. 

I'll create a repo for it shortly, but wanted to bounce the naming around before creating it.

**Comment by thomaswilburn** [comment]
There's a page in the wiki that lists commands supported by Caret for developers, and I would think that this information would probably go there. We could have a separate page for plugin development as well, but I just don't think it has enough material to justify that. It's not that complicated.

If you want to draft up some material here, or fork the wiki and then submit a patch/PR, I'd be happy to take a look.

**Comment by DanShrader** [comment]
I forked the repository but the wiki didn't seem to want to go with it, so I pulled the wiki and pushed it over to my fork.  It's located at this [link](https://github.com/DanShrader/Caret/wiki/Commands).  Let me know what you think.

**Comment by thomaswilburn** [comment]
Thanks, I'll take a look when I get a chance.
