### ISSUE TITLE
Setting syntax to markdown is not the same as opening a *.md file

### ISSUE THREAD

**Issue by Zaxim** [thomaswilburn/Caret#582]
### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

1. Open a file with a .txt extension
2. Open command palette
3. Choose, "Set Syntax: Markdown"

#### Expected Result
Syntax highlighting for Markdown elements and editor behavior should be set markdown, e.g. new lines automatically indent to the previous line.

#### Actual Result
Syntax highlighting for Markdown elements, however, new lines do not automatically indent to the previous line. This does not match the behavior of directly opening .md files using Caret.

### Additional notes

I expected that setting the syntax using the command palette to markdown as referenced in issue #310, would auto indent new lines. The workaround is to name my files with the .md extension which defaults the syntax to markdown.

### System details

Asus Flip
Version 60.0.3112.52 (Official Build) beta (64-bit)

**Comment by thomaswilburn** [comment]
I can duplicate this, but I'm not sure how to fix it, and it seems like a bug in Ace to me. I think you may want to file it there, and then if it turns out that I'm doing something wrong, they can refer it back to me.
