### ISSUE TITLE
Add Qlik (qlik.com) language (file .qvs)

### ISSUE THREAD

**Issue by bmenicucci** [thomaswilburn/Caret#583]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

### Description
It would be nice to have support for Qlik language like Inqlik package for Sublime Text
Thanks for your great work!

### System details

*Please provide your Chrome version and operating system here.*

**Comment by thomaswilburn** [comment]
Unfortunately, Ace does not have a syntax mode currently for Qlik.

**Comment by bmenicucci** [comment]
Ok, got it.
Thanks for taking care of that.
