### ISSUE TITLE
Add new ACE themes when upgrading

### ISSUE THREAD

**Issue by biell** [thomaswilburn/Caret#584]
Next time you upgrade ACE, please add the new themes to the menu.  Thank you.

As of ACE v1.2.8:

- [x] gob
- [x] gruvbox

**Comment by thomaswilburn** [comment]
Fair enough, I'll keep it in mind.

**Comment by thomaswilburn** [comment]
Fixed in e69537ff969d614c08119da6648a4eeb5650ec4f
