### ISSUE TITLE
Add ability to define custom font color schemes

### ISSUE THREAD

**Issue by Willt125** [thomaswilburn/Caret#586]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

I feel it would be nice if I could define a custom color set, separate from the pre-defined sets such as `eclipse` or `github`. Maybe having a separate color.json file that is read only when  `defaultTheme: "custom"`.

**Comment by thomaswilburn** [comment]
We used to have a custom theme, actually. However, the code required to make it work was cumbersome, and I ended up removing it in an effort to clear out a possible source of bugs. 

If you're really interested in defining custom colors, I suggest running Caret from source and defining a new `theme-whatever.js` file in the `js/ace` directory. It should be pretty easy to figure out what that looks like, based on the themes that are already in there.

**Comment by Willt125** [comment]
Thanks!
