### ISSUE TITLE
[Question/Feature Request] Custom autocomplete plugins?

### ISSUE THREAD

**Issue by lizenas** [thomaswilburn/Caret#588]
I would like to write a custom autocomplete plugin for the [Love2d API](love2d.org/wiki/love), which is a 2D game framework for Lua. If possible, how would I go about this?

**Comment by thomaswilburn** [comment]
You'd want to take a look at our plugin API, and see if it's sufficient (it's probably not, but I don't know). You'd probably have to write a pull request to patch those holes, and then you can work on the plugin. 

Alternatively, if you can specify it as a language mode and get it accepted by the upstream Ace project, that's probably easier in terms of code. Then we'll pull from upstream when they put out a release.
