### ISSUE TITLE
Switching the keyboard layout CTRL+SPACE in Caret. Google Chrome 60.0.3112.112 (64 bit)

### ISSUE THREAD

**Issue by ishutinov** [thomaswilburn/Caret#590]
Please forgive me for the quality of the translation.
Dear developers, Caret programs. Thank you for your efforts, for such a wonderful, stable, practical code editor for Chrome OS. Everything is done very well and well thought out. I read all the problems and wishes on GitHubs (https://github.com/thomaswilburn/Caret/issues) and did not find the answer to my mini problem. 
I'm using the Samsung Chromebook Pro this year. 
Version 60.0.3112.112 (Official build), (64 bit) 
I have 3 different languages ​​(US, UA, FR) for input in the system. CTRL + SPACE for Chrome OS to switch between them, I use the standard keyboard shortcut. 
Change these keys in the system Chrome OS - is not possible, because of the features of the operating system itself. When I use your Caret program, 
I need to switch these three languages ​​to each other. I can not switch languages ​​to the Caret program, namely "Ctrl-Space": {"ace": "startAutocomplete"} in the key.json file. I tried to remove this value (Ctrl-Space: {"ace": "startAutocomplete"}), delete these values, reassign these values ​​- the result is the same - switching languages ​​in the Caret program is impossible.
 Help solve this mini problem.

**Comment by YemSalat** [comment]
Did you try enabling `"autocompleteLive": true` in config/user.json?
I know its not really addressing your issue directly, but might work?

**Comment by thomaswilburn** [comment]
Set the value for Ctrl-space in your keyboard config to `false` (no quotes around it). This will tell Caret not to trap that event, and should let the IME switcher do its thing.

**Comment by ishutinov** [comment]
Thank you, Thomas. Installed in the file keys.json the value in the false, that's the way "Ctrl-Space": false - it all worked. Nice work.

**Comment by thomaswilburn** [comment]
No, thank you. I've been meaning to add this to some documentation somewhere, and this is a good reminder to do so.
