### ISSUE TITLE
How can I make Caret the default app to open text/markdown files in ChromeOS?

### ISSUE THREAD

**Issue by kleinbottle** [thomaswilburn/Caret#591]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question
I have tried to make Caret the default app to open text/markdown files in ChromeOS, following the guidelines [here](https://www.howtogeek.com/310576/how-to-change-the-default-apps-on-your-chromebook/) but did not see a dropdown menu let alone Caret. It appears that Text is the default editor.

Can you please put up a demo or a guide on how to make Caret the default please?

I am a Linux user helping a friend, who is a novice, with a ChromeBook to edit text files for a shared project and am deeply grateful yo you for making Caret available. Kudos!

**Comment by thomaswilburn** [comment]
It may be that because Markdown doesn't have a MIME type on ChromeOS, it doesn't show up when we register for the wildcard types. We no longer register for specific file types on ChromeOS, but a subset may make sense. I'll look into it. Thanks!
