### ISSUE TITLE
Caret is maximized on launch but leaves a  1 pixel misalignment on the right side of the screen. 

### ISSUE THREAD

**Issue by nashv** [thomaswilburn/Caret#592]
Unmaximizing and re-maximizing gets rid of the misalignment and the window occupies the full screen perfectly.

### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

Launch Caret maximized.

**Comment by thomaswilburn** [comment]
What OS is this on? We don't control positioning when maximized, so I need to know if it's a CSS issue or not. Are you sure it's not just the 1px white border being buggy?

-----Original Message-----

**Comment by nashv** [comment]
This is happening on ChromeOS. I now provide screenshots:

1. Launch maximized
![launchasmaximized_white border](https://user-images.githubusercontent.com/62116/30877652-a2b2b1ea-a2fa-11e7-9b54-037dea3e256e.png)

2. Minimze it, the white border remains
![minimize_whiteborder](https://user-images.githubusercontent.com/62116/30877663-ac088c24-a2fa-11e7-9643-d4afb5f50799.png)

3. Maximize it again
White border is gone.
![maximize_no_whiteborder](https://user-images.githubusercontent.com/62116/30877687-b8fbaa38-a2fa-11e7-916b-392ce34eaccd.png)

This occurs on Chrome OS versions 60-62 on all channels as well as on Windows 10 versions 60-61 all channels. Other versions not tested.

**Comment by thomaswilburn** [comment]
I see. The pixel on the right side is not a bug in windowed mode, but I don't think I expected that it would launch maximized. I can fix that. Thanks!

**Comment by nashv** [comment]
Thanks for Caret! 

Chrome OS already puts a bar in Windowed mode upon edge mouse-over. The pixel line is unnecessary there too.

**Comment by thomaswilburn** [comment]
It's not for ChromeOS, I added it in windowed mode because I found it necessary visually, particularly when using it with a dark theme against a dark background on Windows 10.
