### ISSUE TITLE
Adding new keyboard shortcut

### ISSUE THREAD

**Issue by wesort** [thomaswilburn/Caret#594]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [X] Question

### Description
I would like a keyboard shortcut refresh the directory tree and was think `ctrl-shift-R` would make sense. Refresh works fine when using the mouse and menu item: Project > Refresh directoris. However, I can't get it to work when editing the keys.json file with various versions of this:
`"Ctrl-Shift-R": { "command": "session:refresh-directories" }`

How should this be done? Thanks.

### System details
ChromeOS Version 61.0.3163.113 (Official Build) beta (64-bit)

**Comment by thomaswilburn** [comment]
Does it work with other shortcuts? I'm wondering if that particular combo is reserved by the OS for some reason, like Ctrl-Shift-U is.

**Comment by wesort** [comment]
I can't seem to get any custom key bindings to work. Is that the correct syntax for reaching `Project > Refresh Directories`? Have you got this working on your machine?

BTW, I have saved keys.json and restarted Caret.

**Comment by thomaswilburn** [comment]
Oh, no, that's the wrong command. Try `project:refresh-dir` instead.

**Comment by wesort** [comment]
Nope, still no joy. Tried each of the following separately:
```
"Ctrl-Shift-R": "session:refresh-dir"
"Ctrl-Shift-R": { "command": "session:refresh-dir" }
"Ctrl-Shift-Y": "session:refresh-dir"
"Ctrl-Shift-Y": { "command": "session:refresh-dir" }
```
_I used **Y** as it doesn't seem to be used for anything by ChromeOS_

Could I ask you to spell out precisely how one should be adding a custom key binding?

**Comment by wesort** [comment]
That's worked! For full clarity here's what I added to `keys.json` and after saving it is ready to use immediately (no restart required).
`"Ctrl-Shift-R": "project:refresh-dir"`

Thanks
