### ISSUE TITLE
Caret (1.7.2) becomes unresponsive when dialogues open

### ISSUE THREAD

**Issue by panther2** [thomaswilburn/Caret#595]
### Type of issue (choose one):
  - [x ] Bug

### Test steps
Execute  "settings - About Caret". When the dialogue opens you cannot close it hitting "OK", Caret is unresponsive.
You can experience this with other steps initiating dialogues, too.

### Description

Dialogues should close, you should be able to continue working.

### Additional notes

./.

### System details

Chrome latest stable on Windows 7.64 as well as Chromebooks (latest stable)

**Comment by thomaswilburn** [comment]
Great catch! Fixing now, will go out as 1.7.3 shortly.
