### ISSUE TITLE
text align issue 

### ISSUE THREAD

**Issue by willman604** [thomaswilburn/Caret#596]
### Type of issue
  - [x] Bug
### Test steps

not sure

### Description

I don't know if it's just for me but the text is not aligned with the text Cursor or Caret
### Additional notes

none known
### System details

Version 60.0.3112.114 (Official Build) (64-bit) 
not sure about operating system my guess ''HP Chromebook ?''

**Comment by thomaswilburn** [comment]
Usually this means you're using a non-monospace font in your settings, which aren't supported in Ace.
