### ISSUE TITLE
Interesting text editor bug

### ISSUE THREAD

**Issue by Agarian** [thomaswilburn/Caret#597]
Lately, I've been noticing an unusual bug where a good portion of the text editor gets cut off when you occasionally change themes. No specific themes, and it doesn't seem like it happens on specific Operating Systems either. I've seen this occur on both Windows, and Chrome OS. I'm unsure about other OS's, and unsure if other people have/had this issue. Refer to the below screenshot for a reference.
![capture1](https://user-images.githubusercontent.com/23372586/31565973-cb0f74b8-b036-11e7-97f5-a6de0a4ebd86.PNG)
**Side Note:** This has been occurring before the recent *1.7.2* update.

**Comment by thomaswilburn** [comment]
Huh, I've never seen that before. So it's cutting off the bottom? Is the text gone, or did the editor zone just get shorter?

**Comment by Agarian** [comment]
No text gets lost, the editor zone just gets much shorter.

**Comment by thomaswilburn** [comment]
Okay. I think that's an Ace bug, which means we can't address it here. But if you're able to check the dev tools when it happens, and see if we got any errors thrown (maybe I'm not calling the resize method properly?), that'd be great.

**Comment by Agarian** [comment]
Will do.

**Comment by ishutinov** [comment]
I have some problems. I am using Caret every day and seen this bug when switching opened tabs. I am using Ctrl+S for save .php files with 2k+ lines, and when i am switching tabs and lose focus from Caret, after, i am restoring focus (using ALT+TAB) to Caret and made change .php code in the first 100 lines and press Ctrl+S, but, sometimes my .php file not show last 25-40 lines = this lines is losed... Sorry for my bad English.  Thomas Wilburn, thank you for this Chrome OS code editor. Maybe you have any ideas to close this bug? I do not want change text editor for this bug, but sometime i am losed my info(code)...

**Comment by thomaswilburn** [comment]
I believe this can happen if you are working over SFTP. I do not recommend using Caret for editing remote files, as the file system APIs that we're given don't seem stable when doing so.
