### ISSUE TITLE
Plugin API no longer working

### ISSUE THREAD

**Issue by DanShrader** [thomaswilburn/Caret#598]
Hi, 

Since the latest update the Plugin API is no longer working on 'saved' files.  It does work on new files, which have not been saved.  Once the file is saved then the plugin reverts back to the not working state

### Type of issue (choose one):
  - [X] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

Plugins will not work on saved files, only 'new tabs'.  To confirm that it was not a particular plugin I tested on the three that I have on the Web store, and created a plugin that simply did a alert box.  All showed the same behavior.

### Description

*If this is a bug, what would you expect the correct behavior to be?*

The expected behavior is that the Plugin API would work on 'saved' files 

### Additional notes

*If this is a bug, is there anything else I should know?*
None that I can think of.

### System details

Tested on both a Chromebook on version 60.0.3112.114 and a Windows 7 machine

**Comment by thomaswilburn** [comment]
Awesome, a plugin issue! Can you send me the names of your plugins, so I can test and fix ASAP? Also, do you know offhand what's causing the issue? Are any errors being thrown in Caret's console?

**Comment by thomaswilburn** [comment]
Never mind, found it. The API wasn't calling the file's `getPath()` correctly now that we're all async functions internally.

**Comment by DanShrader** [comment]
Here are the three plugins:

* [Caret Plugin::Pretty-JavaScript](https://chrome.google.com/webstore/detail/caret-pluginpretty-javasc/nfkohdggkammeogcdpmiebnlbcgpdcii?utm_source=chrome-ntp-icon)
* [Caret Plugin::Table Tools](https://chrome.google.com/webstore/detail/caret-plugintable-tools/npkbhkdbgkoanfjllmookbonhfpckdel?utm_source=chrome-ntp-icon)
* [Caret Plugin::SQL and DAX Formatter](https://chrome.google.com/webstore/detail/caret-pluginsql-and-dax-f/dkjokfldmgepembohkgndcmjoggncdgn?utm_source=chrome-ntp-icon)

For the life of me I can't figure out how to open the Caret console command.

**Comment by thomaswilburn** [comment]
The console is Ctrl-. (period, like the > character but without shift). If you meant the dev tools, you have to set the Chrome flag that lets you inspect apps.

**Comment by thomaswilburn** [comment]
1.7.6 should fix this, but please let me know if you run into any other issues. Thrilled to see someone actually using the plugin system!

**Comment by DanShrader** [comment]
Thanks, tested 1.7.6 and it works perfect!
