### ISSUE TITLE
https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed

### ISSUE THREAD

**Issue by polardiver** [thomaswilburn/Caret#599]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

*What steps cause the problem to occur? Are there any particular settings or configurations that are required in order to reproduce it?*

### Description

*If this is a bug, what would you expect the correct behavior to be? If it's a feature request, what do you want Caret to do? Are there other examples of this feature that I could look at? Screenshots are always helpful.*

### Additional notes

*If this is a bug, is there anything else I should know? If it's a feature request, any caveats I should keep in mind?*

### System details

*Please provide your Chrome version and operating system here.*

**Comment by Agarian** [comment]
This isn't even remotely an issue.
