### ISSUE TITLE
File's opened outside of Caret's open or project menu cannot be saved

### ISSUE THREAD

**Issue by DanShrader** [thomaswilburn/Caret#600]
### Type of issue (choose one):
  - [X] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

* In Chrome OS right click open with Caret, edit and then attempt to save.  The file will not save.  
* In Windows or Chrome OS if a file is dragged and dropped into Caret, that file also cannot be saved.

### Description

If a file is opened outside of Caret's open or project menu it cannot be saved.

### Additional notes

Checked the Caret console (Ctrl-.) and it did not indicate any errors

### System details

Chrome OS and Windows 7

**Comment by thomaswilburn** [comment]
Sorry about that, failed to await for a writable check (drag/drop file entries are not initially given the same permissions as other entries).

**Comment by DanShrader** [comment]
No sweat, figured that no one else had reported it.  You should have seen me trying to figure out why my new jasmine tests were not showing up this morning - it was very comical.

Thanks for the fix.
