### ISSUE TITLE
Add always on top

### ISSUE THREAD

**Issue by The-Bob** [thomaswilburn/Caret#604]
### Description
Would add setting to keep Caret as the top window, even when not focused.  Just think that this is a cool feature.

### Additional notes
Definitely doable, because [Text](https://chrome.google.com/webstore/detail/text/mmfbcljfglbokpmkimbfghdkjmjhdgbg?utm_source=chrome-app-launcher-search) has this feature.

**Comment by thomaswilburn** [comment]
In general, I don't really like stuff that causes an app to ignore the z-order for a windowing system. If you file a pull request, though, I'll take a look at it.
