### ISSUE TITLE
How to enter commands?

### ISSUE THREAD

**Issue by alkopop79** [thomaswilburn/Caret#605]
It may seem a foolish question but where do I enter commands? Where is the interface?

**Comment by thomaswilburn** [comment]
Depending on what you mean, you can open the command palette by pressing Ctrl-Shift-P (or Cmd-Shift-P on a Mac). If you want to test the actual internal command system that Caret uses for inter-module communication, pressing Ctrl-. will open up a console line at the bottom where you can pass a command and argument to be fired.
