### ISSUE TITLE
Support for increase/decrease of quote level (">") for plain text docs

### ISSUE THREAD

**Issue by pmyers** [thomaswilburn/Caret#606]
Support for toggling line comment and block comment works in most of the coding languages. In plain-text mode, of course, these functions are not implemented.

What I wondered is if it would be acceptable to allow Toggle Comment while in plain-text mode to be used for editing mail. i.e. Adding ">" to the beginning of every line. That way it would be a handy way to take arbitrary text and quote it. It would be a slight deviation of the intent of the feature because it's quoting and not commenting.

Alternatively, there could be another function implemented entirely for increase and decrease of quoting levels in a given text selection (i.e. increase quote level adds another > to each line, decrease quote level removes a > from each line).

This feature would be useful for using Caret as a buffer to copy and paste text from various MUAs as well as working with tools like Trello that use Markdown syntax and > to indicate quote levels.

Would this be an acceptable feature to consider adding to Caret?

**Comment by thomaswilburn** [comment]
This bug would need to be filed against Ace, we don't implement text editing features in the Caret code directly.
