### ISSUE TITLE
Kill other processes with external commands

### ISSUE THREAD

**Issue by samrocks9** [thomaswilburn/Caret#609]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

### Description

Is there any way for me to use caret to kill a process on my chromebook, like another extension?

**Comment by thomaswilburn** [comment]
Not that I'm aware of. There are APIs to do that, but they're restricted (as far as I know) to manifests that are signed by Google, like the Chrome App Dev Tools.
