### ISSUE TITLE
Caret Update notification - button Show changelog

### ISSUE THREAD

**Issue by jise** [thomaswilburn/Caret#611]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

### Test steps

Click to the Show changelog button in the Caret Update notification after Caret update.

This page will be shown:
[chrome-extension://nlldbplhbaopldicmcoogopmkonpebjm/changelog.html#fljalecfjciodhpcledpamjachpmelml](chrome-extension://nlldbplhbaopldicmcoogopmkonpebjm/changelog.html#fljalecfjciodhpcledpamjachpmelml)
On this page the last version mentioned is 1.6.28.

### Description

But Caret was just updated from version 1.8.3 to 1.8.4.

### Additional notes

Why doesn't this page continue to be updated anymore?

### System details

Chrome 62.0.3202.94 Stable - Microsoft Windows [Version 6.1.7601]

**Comment by Sonickyle27** [comment]
On my end, it took me to https://github.com/thomaswilburn/Caret/blob/master/changelog.rst.

**Comment by jise** [comment]
Which OS?

**Comment by Sonickyle27** [comment]
Chrome OS 62.0.3202.97 Stable

**Comment by jise** [comment]
Oh, I forgot, that I am using [Extensions Update Notifier](https://chrome.google.com/webstore/detail/extensions-update-notifie/nlldbplhbaopldicmcoogopmkonpebjm). Maybe I have clicked to the Changelog button from Extensions Update Notifier notification, not from Caret own notification. But anyway, both changelogs are not up to date :)

**Comment by jise** [comment]
I noticed that just changelog in [Chrome Web Store](https://chrome.google.com/webstore/detail/caret/fljalecfjciodhpcledpamjachpmelml) is up to date.

**Comment by thomaswilburn** [comment]
There's only one canonical changelog, which is the repo. I wipe out the one in the store periodically, so it can't be trusted for history. I will update the RST now.
