### ISSUE TITLE
GameMakerLanguage?

### ISSUE THREAD

**Issue by CrashRocks1419** [thomaswilburn/Caret#616]
For people who use **GameMaker: Studio**, [GameMakerLanguage (GML)](https://docs.yoyogames.com/source/dadiospice/002_reference/001_gml%2520language%2520overview/) is something they all use. I was wondering if it could be added, and if it's possible to. It seems almost like C/C++, though I have never had experience with either of those. 

Just wondering.. Thanks!

**Comment by thomaswilburn** [comment]
Is it a language with support from Ace? If so, no problem. If not, get them to add it, and then I'll pull from upstream.
