### ISSUE TITLE
Css Grid property and token warnings

### ISSUE THREAD

**Issue by Wurby** [thomaswilburn/Caret#617]
### Type of issue (choose one):
  - [X] Bug
  - [ ] Feature request 
  - [ ] Question?

### Test steps

Create a css document and attempt any of the following styling tokens or properties. (this list isn't exhaustive, just what is marked as a warning in my stylesheet.)

grid-template-columns: 1fr 1fr 1fr;
grid-templates-rows: 1fr;
grid-gap: 5px;
grid-row-start: 1;
grid-row-end: 1;

### Description

Been learning CSS grid, and while editing the .css file with Caret, there are unexpected tokens and unknown property warnings on every line that a css grid property or token is used. 

### System details

Google Chrome OS Version 63.0.3239.70 (Official Build) beta channel (64-bit)

**Comment by thomaswilburn** [comment]
It's possible grid support isn't in Ace yet. I'll pull when they make a new release, and that should correct this.

**Comment by Wurby** [comment]
Good to know. Thanks for this project, I love it.
