### ISSUE TITLE
Right way to call ace:command in the user setting?

### ISSUE THREAD

**Issue by ipstone** [thomaswilburn/Caret#619]
In caret/ace editor, in the vim mode, we can call:
```
:imap jk <Esc>
```
to map jk to Esc.

As I searched in ace editor repository: lib/ace/keyboard/vim.js
https://github.com/ajaxorg/ace/blob/243cb467fce7ebee0dd98691bd9d472a861fda8e/lib/ace/keyboard/vim.js
```javascript
1017 | { name: 'colorscheme', shortName: 'colo' },
1018 | { name: 'map' },
1019 | { name: 'imap', shortName: 'im' },
… 
5028 | exCommandDispatcher.map(mapArgs[0], mapArgs[1], ctx);
5029 | },
5030 | imap: function(cm, params) { this.map(cm, params, 'insert'); }
```
It seems there is a function imap. Is it possible to call the function in the caret user setting such as the pseudo-codes below:
```
  // Try to add jk => Esc for vim mode
  "ace:command": "imap:jk <Esc>"
```

I must missed/skipped a lot of steps here, please point the direction/suggest how to call this imap function in caret setting. 

Thanks

**Comment by thomaswilburn** [comment]
I don't think that's actually supported in our command setup. But I don't know anything about the vim emulation, since I don't use it or test it. So if you can figure it out, feel free to submit a pull request for it.
