### ISSUE TITLE
Fold all top-level nodes

### ISSUE THREAD

**Issue by davidrthorn** [thomaswilburn/Caret#620]
Is there any way to fold all top level nodes (an option in Kate)?

**Comment by thomaswilburn** [comment]
I don't believe so, I think it's only fold-all.

**Comment by davidrthorn** [comment]
I can't even see how to fold all... maybe I'm missing someyhing

**Comment by thomaswilburn** [comment]
There's an Ace command you can bind, I don't remember if we surface it by default.

**Comment by davidrthorn** [comment]
@thomaswilburn cool, thanks. I'm not familiar with Ace. I'll look into it.
