### ISSUE TITLE
Edit hidden files (like .gitignore)

### ISSUE THREAD

**Issue by metbril** [thomaswilburn/Caret#621]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [x] Question

### Test steps

I am using Caret as coding editor on a chromebook. Specifically, I have connected to a SMB share in the Files app and can open regular files with Caret. I can't seem to open (and thus edit) the `.gitignore` file for the project. The hidden files do not show op in the file browser and the setting 'show hidden files' does not make a difference. I currently have to revert to ssh-ing into the host and use the nano editor.

### Description

Similar to #522 and if at all possible would like to be able to open and **edit hidden files** (as opposed to folders) from a **linux host** over a **SMB/CIFS** share from a **Chromebook** :grin:

### Additional notes

For the record, I have set my preferences to show folders, but these don´t show up in the file browser. Perhaps this is a Chrome OS limitation?

**user.json**

```json
  //by default, Caret doesn't show hidden folders (i.e., .git) in its project view
  "showHiddenDirectories": true,
```

### System details

Google Chrome OS 63.0.3239.140 (Officiële build) (64-bits)
Caret 1.8.7

**Comment by thomaswilburn** [comment]
Dot files should not be ignored in the project manager. I can't control if they show up in the file dialog. But we do not filter files that way.
