### ISSUE TITLE
Wiki: Working with Tabs

### ISSUE THREAD

**Issue by tumukei** [thomaswilburn/Caret#622]
The mention of using Ctrl-G to search open tab is not correct, correct way seems to be Ctrl-P. By default Ctrl-G is go to line.

**Comment by thomaswilburn** [comment]
Ctrl-P is the palette, and Ctrl-G has always been go to line. Where did we mention Ctrl-G as search?

**Comment by tumukei** [comment]
> It's easy to switch between tabs using the universal go-to palette. Press Ctrl-G to activate the palette, then start typing a filename and press Enter. This is just the first of many tricks available through the go-to palette.

There?

**Comment by thomaswilburn** [comment]
Fair enough, looks like I had a typo there. I'll fix.
