### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by johnntn** [thomaswilburn/Caret#623]
I am having a problem with the html program, every time I type a word/letter, there is a gap between the word/letter and my cursor. It only happens on Caret, could i get help please?

![screenshot 2018-03-08 at 8 59 09 am](https://user-images.githubusercontent.com/37188364/37164403-04ac570a-22af-11e8-9ec8-ecea2e807f05.png)

**Comment by thomaswilburn** [comment]
You're using a non-monospace font, which is not supported in Caret. Set the font to a fixed width typeface to fix it.
