### ISSUE TITLE
Option to disable directory scan

### ISSUE THREAD

**Issue by kasik96** [thomaswilburn/Caret#624]
I found a bug, when i connect SMB (ChromeOS) and after that i added that folder to Caret project it takes like 15 minutes to load. I think thats it becouse that Folder is huge, and it has things like node_modules and etc. and Caret scan all of it. A check how it works in other editors, and best is in VS Code i think, it scans only top section of folder and after you open an child folder, it only scans that top section. I think thats a nice feature, so adding to menus something like: directoryScanOnDemand:false/true will be nice.

### Type of issue (choose one):
  - [X] Bug
  - [X] Feature request
  - [ ] Question

### Test steps

Connect any bigger SMB/Samba Connection using any of two connector Chrome OS have in WebStore and try to add Directory from it that has lot of files.

### Description

Described at the top

### Additional notes

*If this is a bug, is there anything else I should know? If it's a feature request, any caveats I should keep in mind?*

### System details
Chrome OS, Latest stable on Samsung Chromebook Pro, SMB File System for Windows Files plugin

**Comment by thomaswilburn** [comment]
Lazy-loading of directory contents is something that technically can be done, but was part of the ill-fated project panel rewrite and was never merged into master. You're welcome to poke around in that branch and submit a PR, but in general you're better off teaching Caret to ignore folders (like node_modules) that it shouldn't scan.
