### ISSUE TITLE
Adding theme customization

### ISSUE THREAD

**Issue by yannick1124** [thomaswilburn/Caret#625]
### Type of issue
Feature request

### Description

Whenever I try a theme, I find a color or two at least that doesn't suit me. It's too light or too dark, or I simply think another color would do better. I have been searching through the application but I couldn't find any way to make custom themes. So could you think about adding it. Or am I just too blind to see it's actually already there.

### System details

Chrome OS 64.0.3282.190 (64-bits)

**Comment by thomaswilburn** [comment]
We had the ability to create custom themes from a JSON file, but nobody used it and it made the code much more complicated, so it was removed. If you really want to change something, I recommend running Caret from source and editing the theme files, that's probably the easiest way.

**Comment by yannick1124** [comment]
How do I do that?

**Comment by thomaswilburn** [comment]
There are instructions in the readme file of this repo.

**Comment by yannick1124** [comment]
ok thank you
