### ISSUE TITLE
Change Font/Font Size of Sidebar?

### ISSUE THREAD

**Issue by jeffmcneill** [thomaswilburn/Caret#630]
### Type of issue:
  - [ X ] Question

### Description

I've looked around and done a variety of searches on the wiki and issues, but have not found any similar Q or A. Is it possible to configure the sidebar for different Font/Font Size? The sidebar does not inheret the Font/Font Size of the main window when that is configured. 

Any ideas/clues?

**Comment by thomaswilburn** [comment]
No, there's currently no option to configure the size of any UI features.

**Comment by jeffmcneill** [comment]
It would be helpful to include this information, say, somewhere.
