### ISSUE TITLE
Open multiple windows

### ISSUE THREAD

**Issue by wesort** [thomaswilburn/Caret#631]
It would be useful to be able to have multiple files open and visible at the same time. Ideally, this would be implemented in two ways:
- Multiple **tabs** open in the same window with options to show side-by-side or vertically stack, and to adjust the size of the tab
- Multiple **windows** open at the same time. Probably through a right-click on the app icon in the "shelf".

context: ChromeOS beta on a Chromebook Pixel LS

**Comment by thomaswilburn** [comment]
Unfortunately, the way the code is written, almost all of it assumes that the editor and window instances are singletons. I think it's probably possible to create a multi-window mode, but someone would need to file a pull request to enable it, and you'd need to handle stuff like external messages to the plugin API gracefully.

**Comment by wesort** [comment]
Ok. Thanks for replying but unfortunately that pull request will have to come from someone else as it would be beyond my abilities.
