### ISSUE TITLE
Beautify?

### ISSUE THREAD

**Issue by UnknownEvil** [thomaswilburn/Caret#633]
### Description
I'd like to be able to be able to format my file with the press of a button (Ctrl + B, perhaps) like I can in Caret-T, it is the only reason I use Caret-T over Caret, and it would be lovely if it was in Caret (which is updated quite a bit more)

### Additional notes
I am aware this has been asked, but it has also been 4 years since

**Comment by thomaswilburn** [comment]
Unless the packages used to format JavaScript have gotten a lot smaller, my answer hasn't changed: this is what plugins are for.
