### ISSUE TITLE
Caret as default text editor?

### ISSUE THREAD

**Issue by lagerratrobe** [thomaswilburn/Caret#634]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [X] Question

### Description

Thanks for an amazing editor.  I've made it my defacto editor on both my Chromebook and Win 10 machines - it's great.  One question though, is it possible to make it the default application to open certain files?  I've tried in Windows to specify it and specifying Caret from the Start Menu makes it open the file in a Chrome window.  I'm guessing this is because it's a Chrome extension, but I figure I'd ask.

Thanks again for the great tool.

**Comment by thomaswilburn** [comment]
Yeah, unfortunately Chrome apps can't be set as default file handlers on Windows, and given that they're no longer officially supported outside of Chrome OS, they never will be.
