### ISSUE TITLE
I believe chrome.runtime.sendMessageExternal may be outdated

### ISSUE THREAD

**Issue by UnknownEvil** [thomaswilburn/Caret#635]
It doesn't exist within the [official chrome developer page for chrome.runtime](https://developer.chrome.com/extensions/runtime)

And I'm almost sure it is because of the [official chrome developer page for cross-extension messaging](https://developer.chrome.com/extensions/messaging#external) says ![image](https://user-images.githubusercontent.com/12143899/39666023-f872c890-506a-11e8-8e4c-66611c84db3f.png)

(Also the beautify plugin I downloaded doesn't appear to work so I thought this might be why)

**Comment by thomaswilburn** [comment]
Interesting! That's new. I'll fix when I get a chance, or I'm happy to take a pull request.
