### ISSUE TITLE
"Google Drive / Github" Integration

### ISSUE THREAD

**Issue by CryogenDev** [thomaswilburn/Caret#637]
# Feature Request

### Description

Google Drive/Github Integration, so you just hit a button to back up your code to the cloud.

### Additional notes

https://developers.google.com/drive/api/v3/savetodrive

**Comment by thomaswilburn** [comment]
https://github.com/thomaswilburn/Caret/wiki/Git-SFTP-Drive-support#drive-support

**Comment by CryogenDev** [comment]
I use this app on my desktop, which is why I made this suggestion. If you want, I can go through the trouble of doing the work for you and create a pull request once I've added it.

**Comment by thomaswilburn** [comment]
You can do the work in a fork if you want, but I'm not interested in bringing this into Caret. As far as I'm concerned, on desktop computers it makes sense to simply use the Drive application to sync a folder with the cloud directly, instead of integrating that into the editor.

**Comment by CryogenDev** [comment]
What about Github integration? I mean, if you were to integrate that, users would have the ability to backup their projects locally, and with the same module you can add support to back up to a github repo.

**Comment by thomaswilburn** [comment]
I don't really understand why it makes sense to add that to the editor instead of just letting people use the git client of their choice. Caret is very much about being a small utility that does one thing well. If you want an IDE, there are lots of better choices on the desktop.

**Comment by CryogenDev** [comment]
The reason I ask this is because I am the head of a Web Development class, and I don't allow my students to download things on the computer, so I resort to Chrome Apps as a low profile alternative, and I thought that this editor was so great. One of my students asked me if there was a way to back it up onto the cloud so they can work on it at home, and since I don't have the computer password, I can't install git or the google drive app even if I wanted. Thanks for responding.

Rowan

**Comment by thomaswilburn** [comment]
I see. Yes, that's a frustrating use case. It may make sense to talk to your department about getting some kind of networked per-user storage, through Google or otherwise. When I taught, and when I talk to many people who use Caret for education, it's often on Chromebooks which have Drive built-in, so it doesn't come up.

Another option you might want to look into would be glitch.com, which is a really great cloud-based environment for hosting web apps, including static pages but also Node servers and apps.

**Comment by CryogenDev** [comment]
Thanks, I'll look into that.
