### ISSUE TITLE
rfe: Enable Fortran syntax highlighting

### ISSUE THREAD

**Issue by HamishB** [thomaswilburn/Caret#639]
Hi,

mode-fortran.js exists in the js/ace/ subdirectory but is not available from the syntax highlighting menu at run time.

As per issue #354 I tried ctrl-. and typed "session:open-settings-file ace" to edit the ace.json file, and then added the line
`  { "name": "fortran", "label": "FORTRAN", "extensions": ["f", "f90"] },`
and saved & restarted.

To get it to work I had to edit the same into ~/Extensions/.../1.8.10_0/config/ace.json

Could fortran support be there automatically?

many thanks,
Hamish

**Comment by thomaswilburn** [comment]
Fixed in d738c2a34f1a10ebc807e2d1a6522ee92e6f194e

**Comment by HamishB** [comment]
Awesome, thanks.
