### ISSUE TITLE
App Hangs Then Crashes Opening Large XML Files

### ISSUE THREAD

**Issue by truenorf** [thomaswilburn/Caret#640]
### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps
1. Save a large (e.g. 60.8 MB) XML file locally (e.g. in Downloads folder)
2. Open the file with Caret
3. Attempt to scroll down in the document, or switch tabs or choose a menu item or close Caret

### Description
The app launches quickly but only displays a blank document for several seconds.  The interface is often responsive during this period.

Eventually (10 - 20 seconds later, depending on file size) the document displays in monochrome text only.  The interface is unresponsive.

Some seconds later (5 - 10?) the display updates to show the document with colourful code highlighting.  The interface is intermittently responsive to scrolling or other commands.

Some seconds later, often when attempting to scroll or search beyond a few pages into the document, the app crashes.

Expected behaviour: the app opens normally and it is possible to scroll around the document and manipulate the text as with smaller files.

![image](https://user-images.githubusercontent.com/7073906/40574927-41a31e20-60d3-11e8-9126-2eb73425ac5d.png)

### Additional notes
Only noticed this behaviour with large XML files, but have not tested with other file types or files with sizes below 60.8 MB.

### System details

![image](https://user-images.githubusercontent.com/7073906/40575061-d2f38930-60d5-11e8-93b9-507fe789e137.png)

Latest top spec Pixelbook.  16 GB RAM, 512 GB SSD

https://store.google.com/us/product/google_pixelbook_specs

![image](https://user-images.githubusercontent.com/7073906/40575044-75703862-60d5-11e8-9665-e677b659705d.png)

**Comment by thomaswilburn** [comment]
As I mentioned in the support forum, it sounds like files this big may be too big for the VM stack, or for Acs to handle. Regardless, it isn't something we can fix in Caret, it would need to be fixed upstream in either the OS or in Ace.

**Comment by truenorf** [comment]
Thanks Thomas,

Sorry I missed your comment in the support forum and thanks for a great app.  Really good job.

You mentioned that turning of syntax highlighting was worth a try, but I can't see where to do that.  Can you give me a pointer?

Many thanks,

Rich

**Comment by truenorf** [comment]
D'oh!  Found it.

![image](https://user-images.githubusercontent.com/7073906/40583919-d7650344-618f-11e8-9260-7d486c0b5bd9.png)

And it seems to do the trick: 173MB file now loading a scrolling/editing properly :-)

Is there a way to disable syntax highlighting by default?
