### ISSUE TITLE
Feature Request: Recommended line length guide

### ISSUE THREAD

**Issue by fahim-** [thomaswilburn/Caret#641]
Can we have a recommended line length guide? By this I mean a vertical line that goes down the editor at the recommend line length.  This doesn't force the user to stick to this length but is a guide.

Nice if you have a large/relatively high resolution screen and like to work full screen.

Thanks! and please do keep up the good work!

**Comment by thomaswilburn** [comment]
This exists, it's referred to in the options as "showMargin".
