### ISSUE TITLE
Integrated Crosh Terminal

### ISSUE THREAD

**Issue by jonpchin** [thomaswilburn/Caret#644]
Is it possible to integrate a crosh terminal like how Visual studio code has an integrated terminal? I was wondering if it was possible to launch chrome-extension://nkoccljplnhpfnfiajclkommnmllphnl/html/crosh.html in a new tab in Caret.

**Comment by thomaswilburn** [comment]
We're not really built to do that right now--tabs are an extension of Ace sessions, and we'd need to build out some infrastructure to support it. If you forked and it turned out to be pretty small, I'd be okay with looking at a pull request.

-----Original Message-----

**Comment by jonpchin** [comment]
I am planning to work on this early August to see how difficult it will be to implement this. Thanks for the info about the Ace sessions.

**Comment by jonpchin** [comment]
I did a little research and it seems for security reasons the chrome extension API does not allow reading a file by a specified path on the ChromeOS file system according to this post: https://stackoverflow.com/questions/14286197/reading-and-writing-files-in-chrome-extensions

This makes sense but it puts a stopper to my idea of getting this to work. I am open to other suggestions on how this could be implemented though.
