### ISSUE TITLE
caret html file opening in chrome text editor

### ISSUE THREAD

**Issue by guitarzanaz** [thomaswilburn/Caret#647]
after updating caret my html only open in chromebook text editor, not google chrome browser. Any fix for this? I'm code illiterate. Just started a course on Udemy and I'm on lecture 46. So quite the newbie. Thanks for any help

Gregg

### Type of issue (choose one):
  - [ X] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

*What steps cause the problem to occur? Are there any particular settings or configurations that are required in order to reproduce it?*

### Description

*If this is a bug, what would you expect the correct behavior to be? If it's a feature request, what do you want Caret to do? Are there other examples of this feature that I could look at? Screenshots are always helpful.*

### Additional notes

*If this is a bug, is there anything else I should know? If it's a feature request, any caveats I should keep in mind?*

### System details

*Please provide your Chrome version and operating system here.*

**Comment by thomaswilburn** [comment]
You should still be able to right click on the file to open it on Chrome, or drag it onto a new browser tab to open it there.
