### ISSUE TITLE
How to use Ace Themes?

### ISSUE THREAD

**Issue by ethamitc** [thomaswilburn/Caret#649]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [X] Question

### Description

I wan't to use an Ace theme but I don't know how.

**Comment by ethamitc** [comment]
Nevermind I figured it out.

**Comment by YahirAlejandro** [comment]
Hi, I've been spending an unreasonable amount of time figuring out how to change the themes in Caret. Unfortunately I can't move away from it so, would you be so kind to share how exactly change the theme exactly?

**Comment by thomaswilburn** [comment]
The theme name should match whatever comes after the `theme-` in the filename, and doesn't include the `.js`. So for example, you should see an immediate change if you save a user prefs file with `"defaultTheme": "tomorrow_night"`.

**Comment by YahirAlejandro** [comment]
Yes, now it's working.

Thanks for sharing that :)
