### ISSUE TITLE
Auto-Close brackets (Like Atom & VS:C)

### ISSUE THREAD

**Issue by ethamitc** [thomaswilburn/Caret#650]
### Type of issue (choose one):
  - [ ] Bug
  - [X] Feature request
  - [ ] Question

### Description

I would like a feature added that's in Atom and VIsual Studio: Code, which is when I open any type of brackets it would auto-close them. This is a very useful feature as it saves me a key to press.

### System details

66.0.3359.203 (Official Build) (32-bit)

**Comment by thomaswilburn** [comment]
This already exists, albeit maybe in a different style than VSC and Atom do, as long as `disableBehaviors: false` is set in your preferences. For example, in a JS file, if I type `function() {` and hit enter, it will add the closing brace. It will also close the parens in `if (` as I type.

It doesn't always trigger immediately the way that the other editors do, but Caret is not in control of that. If you'd like to request that, or have it added, you'll need to file a bug with Ace (https://github.com/ajaxorg/ace/), which is the component library Caret uses for its code editor functionality.

**Comment by ethamitc** [comment]
Alright, thanks.
