### ISSUE TITLE
multi touch gestures for touch screens and touch pad

### ISSUE THREAD

**Issue by 1LL1** [thomaswilburn/Caret#653]
### Type of issue (choose one):
  - [ ] Bug
  - [# ] Feature request
  - [ ] Question

### Additional notes
-zoom in and out gesture .
*If this is a bug, is there anything else I should know? If it's a feature request, any caveats I should keep in mind?*
-non related issue - can you prevent duplicate tabs .if file opened prevent open it more again with more tabs, .
### System details
lenovo n23 touch screen.
Version 71.0.3558.0 (Official Build) dev (64-bit),

**Comment by thomaswilburn** [comment]
We do not get access to multitouch gesture data, unfortunately.

Duplicate tabs are already prevented, but I think we only do that check if you open them from the project panel. I'll see if it's possible to move it over into the more general file code.
