### ISSUE TITLE
Non-monospace warning given for monospace "Roboto Mono" font family.

### ISSUE THREAD

**Issue by dharcourt** [thomaswilburn/Caret#654]
### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

1. In the user preferences, set the "fontFamily" to "Roboto Mono".
2. Save the user preferences.

### Description

Since Roboto Mono is by definition a monospace font (https://fonts.google.com/specimen/Roboto+Mono), Caret shouldn't generate a warning for it, but it does generate the standard "The custom font you've selected may cause problems with Caret's editing component.." one.

### System details

This was last tested with Chrome OS 70.0.3538.69 (currently Chrome OS Beta) but also occurs with previous versions of Chrome OS.

**Comment by dharcourt** [comment]
This may be an issue with using Web Fonts (https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts#Web_fonts) in Caret.

"Roboto Mono" is a web font and not installed in Chrome OS (and it can't be installed without removing some of the security features of Chrome OS).

Setting the Caret "fontFamily" to "Roboto Mono" has the same effect as setting it to "" or to "courier", so it seems Caret doesn't support web fonts. This suggests this bug should be split into one bug and one feature request:

1) Bug: when it's not able to use a font, Caret should display an error message to that effect, no the monospaced font warning.

2) Feature request: Caret should support web fonts (if it's possible for Chrome Apps to do that).

**Comment by thomaswilburn** [comment]
No, Caret doesn't (and won't) support web fonts, due to the content security policy of packaged apps on Chrome OS.

**Comment by dharcourt** [comment]
That makes sense, and I can use "Noto Sans Mono" for now.

It may be possible to access web fonts in spite of the CSP using XMLHttpRequest and blobs... one day, time willing, I may try this.

**Comment by thomaswilburn** [comment]
I should clarify: it's possible to loosen the CSP using the app manifest. However, it would require adding network permissions to Caret, and I'd prefer not to do that. The fact that the app cannot make any network requests is a real selling point for me--it means it's secure in a way most web-based apps aren't. But I absolutely understand if someone wanted to fork to change that.
