### ISSUE TITLE
I'm a newbie and am having trouble executing my code. I'm using a Chromebook. I wrote a simple html file using Caret, then I saved the file onto my Google Drive. My question is how would I execute my code? I can't find the HTML file on my Google Drive for some reason. I thought I'd be able to click on the HTML file and view it in the browser as if I was working with Sublime text on a Windows machine and executing html files from the file explorer.

### ISSUE THREAD

**Issue by tjzerrer** [thomaswilburn/Caret#656]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

### Test steps

*What steps cause the problem to occur? Are there any particular settings or configurations that are required in order to reproduce it?*

### Description

*If this is a bug, what would you expect the correct behavior to be? If it's a feature request, what do you want Caret to do? Are there other examples of this feature that I could look at? Screenshots are always helpful.*

### Additional notes

*If this is a bug, is there anything else I should know? If it's a feature request, any caveats I should keep in mind?*

### System details

*Please provide your Chrome version and operating system here.*

**Comment by thomaswilburn** [comment]
Hi there! Thanks for leaving a note. I would recommend, if you're new to coding, try saving your file to the local Downloads folder on your Chromebook and opening it from there. That may work better than using Drive, at least at first.

**Comment by tjzerrer** [comment]
Hi Mr. Wilburn,

Thank you for the quick response. I can use a little advice. I'm a middle
school math teacher who would like to start a computer programming elective
course, then have that course lead into more courses like React, Angular,
or Python courses as students gain skills. Each student has access to a
Chromebook, so I wanted to use Caret to build our programs and test our
work. I was hoping to create a Chromebook workflow that will allow students
to grow as programmers throughout their High School years. Do you have any
suggestions?

Thanks again,

Tony

**Comment by thomaswilburn** [comment]
Hey Tony, I'd be happy to help if I can!

Technically speaking, there shouldn't be any reason that the Drive folder on a Chromebook wouldn't work the way that you had originally described. In practice, however, I've found that it sometimes behaves differently from the way that you want when building web pages, such as if you have an HTML file that tries to include CSS and JS in other files. So it may make sense for your students to develop locally, in a subfolder of the Downloads folder, then copy that into their Drive when the project is done so they can have a long-term archive.

The other thing that might be good for them would be a tool like [Glitch](https://glitch.com), which provides a free live coding environment and the ability to "fork" from a previous project. So, for example, you could set up a demo with the basic skeleton you want on the page, then your students could build on that and fill in their own code and content.

Good luck, and if there are any other issues you see for your students, please feel free to file another issue! A lot of people are using Caret in schools, given how common Chromebooks are there, and I want to make sure it's as good as possible for them (without breaking features for more advanced developers).
