### ISSUE TITLE
Add support for Sublime's "file_exclude_patterns" in Project files

### ISSUE THREAD

**Issue by rossjrw** [thomaswilburn/Caret#657]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

### Description
Sublime's project files support a number of extra parameters within the Project file to give greater control over which files are visible in the menu. [Documentation](https://www.sublimetext.com/docs/3/projects.html)

Specifically I'm requesting `file_exclude_patterns`, as I feel it would be most useful to be able to blacklist certain types of file from the project (for example PNG/JPG, which aren't editable in Caret anyway).

(Of course it would be more sensible to move images to their own folder, but I'm working in a shoddy environment and don't have that option)

The documentation for Project parameters in Caret seems to be fairly lacking, so I'm unsure whether or not these features already exist.

Many thanks!

**Comment by thomaswilburn** [comment]
The "ignoreFiles" setting in the user preferences should do what you want. It's currently set to handle primarily directories, such as `node_modules` or `build`, but you can also set it to ignore file extensions ("\.jpg$" should ignore those files, I think).
