### ISSUE TITLE
Vim command ctrl-v selecting only selects two lines

### ISSUE THREAD

**Issue by tommyvanduyne** [thomaswilburn/Caret#660]
### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

Set "emulateVim" to true in user.json

### Description

With emulateVim true, the vim command ctrl-v only selects two lines maximum, which is annoying when you want to do block level editing.

### System details

I am on a Chromebook Pixel (2015) with Chrome Version 70.0.3538.76 (Official Build) (64-bit)

**Comment by thomaswilburn** [comment]
You should file this against Ace, unfortunately. We just enable the Vim option, but none of it is actually written in/for Caret.

**Comment by tommyvanduyne** [comment]
Thanks for the info! I will do that.
