### ISSUE TITLE
Javascript error in ProjectManager.js

### ISSUE THREAD

**Issue by dsouzae** [thomaswilburn/Caret#661]
I am constantly seeing "loading" with the line cycling below it in the "project view".   I noticed the following error

`projectManager.js:495 Uncaught (in promise) ReferenceError: c is not defined at projectManager.js:495` 

### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

No idea.  I open a project and it constantly gives loading.  Now it always shows up when I open the App.

### Description

Commit "dcfbbdb13988f155e145d47389db184dab5913f7" remove the "c" variable argument but did not fix the return statement here:[projectmanager.js](https://github.com/thomaswilburn/Caret/blob/89229993c0fa223bdd2073240255caa61627c44c/js/ui/projectManager.js#L495)

### System details

ChromeOS Version 70.0.3538.76 (Official Build) (64-bit)
Caret v. 1.18.4.

**Comment by thomaswilburn** [comment]
Thanks, this looks like a bug caused after I moved to async functions. I've fixed and will try to deploy to the store tonight.
