### ISSUE TITLE
Paste not working in MacOS with CTRL-V

### ISSUE THREAD

**Issue by ScriptMyJob** [thomaswilburn/Caret#662]
### Type of issue (choose one):
  - [X] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

Change paste key mapping to ctrl-v in MacOS.  Try to paste in Caret.

### Description

Thanks for taking the time to read this.  I have found that changing CTRL-V to paste has caused Caret to not recognize this keyboard shortcut.

### Additional notes

There were other web forums / Ace Editors where this was not working as well say for instance AWS Lambda, so I thought that this was a Chorme issue.  Many text fields have been fixed though, but unfortunatly Caret still does not have CTRL-V capability on MacOS. 

### System details

Version 70.0.3538.102 (Official Build) (64-bit)
MacOS 10.14 (18A391)

**Comment by thomaswilburn** [comment]
I'll look into it, but since Chrome Apps aren't technically supported on non-Chrome OS platforms anymore, it's not a super high priority.
