### ISSUE TITLE
Caret does not properly maximize on MacOS

### ISSUE THREAD

**Issue by ScriptMyJob** [thomaswilburn/Caret#663]
### Type of issue (choose one):
  - [ ] Bug
  - [X] Feature request
  - [ ] Question

### Test steps

Click plus on the Caret system menu.

### Description

Thanks for taking the time to read this.  In MacOS clicking plus will not cause the application to maximize, instead, it will only take up as much space as is available with the system bars still visible.  To work around this have been opening up a secondary window, going into side by side mode then closing the first window.

### Additional notes

After clicking plus:

<img width="1680" alt="screen shot 2018-11-20 at 9 07 46 am" src="https://user-images.githubusercontent.com/18185488/48782500-f213ac00-eca3-11e8-8cd6-904b86e1b4b4.png">
<img width="1677" alt="screen shot 2018-11-20 at 9 07 55 am" src="https://user-images.githubusercontent.com/18185488/48782501-f213ac00-eca3-11e8-84fa-dc650b341ea1.png">
<img width="1680" alt="screen shot 2018-11-20 at 9 08 45 am" src="https://user-images.githubusercontent.com/18185488/48782502-f213ac00-eca3-11e8-8b62-6a17759eb63a.png">

After closing side by side window:

<img width="1680" alt="screen shot 2018-11-20 at 9 08 56 am" src="https://user-images.githubusercontent.com/18185488/48782503-f213ac00-eca3-11e8-8f56-45d8ce037e6c.png">

### System details

Version 70.0.3538.102 (Official Build) (64-bit)
MacOS 10.14 (18A391)

**Comment by thomaswilburn** [comment]
This is a "feature" of the Mac window manager and the way that it interacts with Chrome, it's not something we can really control (as far as I know).
