### ISSUE TITLE
persistent "loading" status at top of left hand display

### ISSUE THREAD

**Issue by johnalexhebert** [thomaswilburn/Caret#665]
The "loading" status indicator never stops, as if it never finishes loading the current file and directory structure.

### Type of issue (choose one):
  - [ *] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

*What steps cause the problem to occur?
- Problem occurs when starting Caret.
- Problem started about 2(?) months ago.

Are there any particular settings or configurations that are required in order to reproduce it?*
- None that I can confirm.

### Description

*If this is a bug, what would you expect the correct behavior to be?
- The "loading" notification should stop when Caret is finished reading the file and directory structure for Caret's current directory.

### System details

Chromebook Samsung XE500C13
Chrome: Version 70.0.3538.76 (Official Build) (64-bit)
Crostini

**Comment by thomaswilburn** [comment]
If you turn on "inspect" for apps/extensions in chrome://flags, and then check the dev tools console for Caret when this happens, do you see any error? Usually this means that an exception was thrown that I didn't catch, and it never got around to removing the loading bar.
