### ISSUE TITLE
Isn't chrome ending support for desktop apps?

### ISSUE THREAD

**Issue by UnknownEvil** [thomaswilburn/Caret#666]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

### Description
Just wondering. I thought so? Doesn't even seem like Caret is on the store anymore.

**Comment by UnknownEvil** [comment]
Also this is a satanic post

**Comment by thomaswilburn** [comment]
It's discontinued on non-Chrome OS, but should be still available on Chromebooks.

Hail Satan.
