### ISSUE TITLE
Open file or directory from terminal

### ISSUE THREAD

**Issue by TheGrimSilence** [thomaswilburn/Caret#667]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

### Description

Applications like [Github Desktop](https://desktop.github.com) and [Visual Studio Code](code.visualstudio.com) have more than proven that Electron is capable of opening applications from the command line.  Personally, I use Caret for writing my markdown files since VSC doesn't look nearly as good. So being able to utilize `caret <file|folder>` would speed things up a little more since I always have my terminal open in VSC.

**Comment by thomaswilburn** [comment]
Unfortunately, this isn't possible from a Chrome app.
