### ISSUE TITLE
[Feature Request] User configurable default syntax settings

### ISSUE THREAD

**Issue by PTruscott** [thomaswilburn/Caret#669]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

### Description

Hi,  I tend to open and develop in only one language (SQLServer).  It would be super useful if I could just set the when creating new/opening unknown files with to SQLServer syntax highlighting.  

Many thanks.

**Comment by Justin-Maxwell** [comment]
My menus.js (Settings➝Menus) - is this approach sufficient?  

`  {
    "label": "menuFile",
    "sub": [
      { "label": "menuNewFile", "command": "session:new-file" },
      ፧
      { "label": "menuExit", "command": "app:exit" },
      { "label": "Syntax",
        "sub": [
          { "label": "JSON", "command": "session:syntax", "argument": "json" },
          { "label": "YAML", "command": "session:syntax", "argument": "yaml" }
        ]
      }
    ]
  },`

**Comment by PTruscott** [comment]
That sort of thing would be perfect.  Apologies if it's already in, I can't currently find it but if it was/is implemented like that it'd be great.

**Comment by Justin-Maxwell** [comment]
In Caret, go to: Settings⟶Menus.   This should open `menus.json` in a new tab.

Right near the top, you should have `"label": "menuFile",` followed by the definition for the File menu.  You should be able to just add another entry into the `sub: []` array for your syntax, similar to my example above or as below.  

`{ "label": "Syntax-SQL", "command": "session:syntax", "argument": "SQLServer" },`

Make sure you have commas etc in the right places, then save the file.  From memory, you don't even need to restart Caret, your new File⟶Syntax-SQL option should be there and working.
