### ISSUE TITLE
ChromeOS - Error: Use a shorter name when saving files

### ISSUE THREAD

**Issue by minegamer5570** [thomaswilburn/Caret#673]
After installing Caret on my Chromebook, I began to set it up to my needs. I turned the dark mode on but left the theme at "Chrome". After that, I was not able to save files without getting a "Use shorter name" error. I even tried a name that was as short as ChromeOS would allow and I still received the error. Doing the same on Windows 10 with Chrome 71.0 saves all files normally with no errors.

Any help would be greatly appreciated!

ChromeOS 71.0
  - [ X ] Bug

**Comment by thomaswilburn** [comment]
The theme doesn't have any interaction with the file system code, so there shouldn't be any way that has an effect. If you turn on extension debugging and check the debug console, what's the actual error and stack trace?
