### ISSUE TITLE
Word Count doesn't count non-latin words

### ISSUE THREAD

**Issue by nagornyi** [thomaswilburn/Caret#675]
### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

1. Type or insert `one two three один два три ένα δύο τρία` into the editor
2. Select **Tools/Word Count** menu item

### Description

Word Count says that we only have 3 words, counting only the words written with latin characters and ignoring the rest of the words (written in Cyrillic and Greek scripts). We should change the regexp to count the words written in those scripts as well (it should be 9 words in this case, not 3 words).

### System details

Caret v.1.8.16, Chrome 72.0.3626.109 (Official Build) (64-bit), Mac OS Mojave 10.14.2

**Comment by thomaswilburn** [comment]
Interesting! The regex I'm currently using is `/\b\S+\b/g`, so I didn't think it would be restricted to English-only characters. I'd welcome suggestions on what would work for other languages, it's a quick fix.

**Comment by nagornyi** [comment]
Yeah, it looks like that `\S` only includes Latin characters in JavaScript, unlike regex implementations in other languages, such as Ruby, this problem is better explained here https://mathiasbynens.be/notes/javascript-unicode. To solve the problem we must explicitly include all Unicode characters. My solution is to use this regular expression instead:
`/([\u0080-\uFFFF\w]\u0027?)+/g`

It covers the wide range of Unicode characters (from 0080 to FFFF) that includes all national alphabets + the Apostrophe symbol (0027) that is used in some English words.
I've tested this regex with the following text and it counts all 55 words accurately, ignoring all special characters and punctuation, you can double-check it here https://regexr.com/48gap:
```
One Jack's two "three" 'happy' Кав′ярня два три нав'язливо ένα δύο τρία âêîôû,O’Brien/ëïü,är en häst बर्ताव करना चाहिए।.!@#$%^&*()-+=<>?~`|\{}[],.?
Jess' pencils are sharp.
Direct speech in British English - 'That,' he said, 'is nonsense.'
Direct speech in American English - "What time will he arrive?" she asked.
What does 'integrated circuit' mean?
Rock 'n' Roll
```
