### ISSUE TITLE
Ctrl-X similar Sublime text functionality

### ISSUE THREAD

**Issue by Francommit** [thomaswilburn/Caret#680]
Question!

Using a Pixelbook, love your editor! One of the only things that I miss is when I type 'Ctrl + X' in Sublime Text 3, it usually clears and cuts the whole line. Or makes an empty line disappear.

I had a look through existing ace commands to see if a similar command existed that I could rebind but I couldn't.

I was wondering if there was a way to reproduce the same functionality of Ctrl-X in Caret. Thank you!

### System details

*Chrome version 74 and operating system - ChromeOS Dev channel.*

**Comment by thomaswilburn** [comment]
There's a pull request that was moved upstream, so hopefully it will show up in Ace at some point, and then we (and all other Ace users) will pull it in.
