### ISSUE TITLE
Editing a file from ChromeOS on an SMB share 

### ISSUE THREAD

**Issue by SteveDinn** [thomaswilburn/Caret#681]
This is a weird one. I can't imagine that other people wouldn't be reporting it if they saw it, but I've reproduced it on two separate chromebooks.

### Type of issue (choose one):
  - [ x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps
- In the ChromeOS "Files" app, ensure that a service is added for an "SMB File Share" 
- Open a text file located on the share. (Doesn't happen when editing a file on the chromebook's internal storage).
- Modify the file such that the modified version is a smaller size than the original
- Save the file

### Description
Note that when the test steps have been executed, the dirty-bit icon on the tab does not change from "unsaved" to "saved".

When you inspect the file, or re-load the file into Caret, note that the file has not been truncated to the smaller size, but it still the original size. The text has been changed, but the end of the file remains with the original content. It is as if the new shorter file was written into the original size buffer without zero-ing it out.

I expect the file to be written, and truncated to the new shorter length, and include no trailing information after the end of the text I can see in the editor window.

### Additional notes
Only weird condition here is that the SMB share is hosted by a linux machine using Samba, but I haven't noticed a difference in any app but Caret.

### System details
ChromeOS Version 72.0.3626.117 (Official Build) (64-bit)

**Comment by thomaswilburn** [comment]
I don't think that's a Caret issue, I think it's a problem with the SMB layer.

**Comment by SteveDinn** [comment]
Caret is the only editor I've seen it happen in. I've tried these text editors as well:
https://github.com/andrewbrg/codepad-chrome-app
https://github.com/GoogleChromeLabs/text-app

**Comment by thomaswilburn** [comment]
What do those applications do that we don't?

I don't typically test Caret on network shares, because it's a pretty uncommon use case, so I'm happy to merge a PR on this one but I'm probably not going to do much work myself to figure it out.

**Comment by SteveDinn** [comment]
Fair enough...My use case is that I'm editing YAML files for an instancew of Home Assistant on a Raspberry Pi, which I'm accessing via SMB share.
