### ISSUE TITLE
Not working in new Chrome OS 754 Dev

### ISSUE THREAD

**Issue by tickmc** [thomaswilburn/Caret#684]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [ x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

Try and type more than one line

### Description

I expect to be able to type more than one line

### Additional notes

No extensions used so clean install.

### System details

*Please provide your Chrome version and operating system here.*

**Comment by thomaswilburn** [comment]
If you're running ahead of the current version of Chrome, various aspects of the browser may be unstable, and it doesn't make sense to try to patch Caret for it. Please test on the stable version and let me know if the bug still persists.
