### ISSUE TITLE
Project not loading fie list

### ISSUE THREAD

**Issue by cmazabarsotti** [thomaswilburn/Caret#685]
- [ ] Bug
### Test steps
While editing my project files with the 'src' directory being displayed, I save the 'project' from the menu. I later opened the project file in Caret. It opened Caret and the project json file but isn't loading the file list. My project json looks like this:
{
  "folders": [
    {
      "retained": "4E7F1FF47D6F41A64AD75F9C76BEA581:src",
      "path": "/src"
    }
  ]
}
### Description
The files list just display empty with "loading..." animation at the top. I thought it would display the contents of the 'src' folder.

### Additional notes

I can't think of anything else to tell you, please feel free to ask

### System details

ASUS Chromebook Flip C302CA
Version 73.0.3683.79 (Official Build) beta (64-bit)

**Comment by thomaswilburn** [comment]
Sounds like the loader crashed for some reason. If you could turn on extension debugging and check for errors in the dev tools console, that would help with the process.

**Comment by cmazabarsotti** [comment]
How do I turn on extension debugging?

**Comment by thomaswilburn** [comment]
There's an option in chrome://flags

**Comment by cmazabarsotti** [comment]
Oh! I'm sorry, I thought you meant for me to do that in Caret. Ok, I'll do this when I get home tonight. Thanks.

**Comment by cmazabarsotti** [comment]
I don't seem to have anything called extension debugging in chrome://flags.
It's OK I don't really need this feature.
