### ISSUE TITLE
New line shortcut?

### ISSUE THREAD

**Issue by xxKeith20xx** [thomaswilburn/Caret#686]
### Question
Anyone know how to move to the next line and accept the formatting/syntax suggestion? 
Example: In python, defining a variable:
1 = 'cat'

Caret automatically populates the closing ' but the cursor stays on t . Is there a way to accept what proceeds the cursor and move to a new line? Like how in vim visual mode the 'o' key starts a new line. I know there is vim mode but was wondering if there is a way to just map it somehow.

### System details
ChromeOS 72
Samsung Chromebook Pro

**Comment by thomaswilburn** [comment]
As far as I know, that's not a typical way to work in Caret--you would type the closing quote to move out of the auto-completed section, then hit enter. However, you can probably write a macro to do that, if you want, using the `sequences.json` settings file.
