### ISSUE TITLE
Add terminal 

### ISSUE THREAD

**Issue by pred12** [thomaswilburn/Caret#687]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

### Test steps
Make a full terminal so we can use like node.js
### Description

Terminal 
### System details
I am in beta chromeOS

**Comment by thomaswilburn** [comment]
We will not be doing this, unfortunately. But there are existing terminal solutions (crosh + crouton) that you can use for Node.
