### ISSUE TITLE
the theme won't stay on:( 

### ISSUE THREAD

**Issue by pred12** [thomaswilburn/Caret#688]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

### Description

When I close caret and re-open the theme  is not the same, yes i put the name of it on the .json file it sill does not work:(

### System details
Beta ChromeOS

**Comment by thomaswilburn** [comment]
You're going to have to be more specific. What name are you putting in the JSON config?

**Comment by pred12** [comment]
Drancula (spelling Is probably wrong on at computer)

**Comment by thomaswilburn** [comment]
Try "dracula" all lower case. Theme files are loaded from [this folder](https://github.com/thomaswilburn/Caret/tree/master/js/ace) without the "theme-" prefix.
