### ISSUE TITLE
loading pane will not stop loading

### ISSUE THREAD

**Issue by tylerbrentondavis** [thomaswilburn/Caret#689]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [x ] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

*What steps cause the problem to occur? Are there any particular settings or configurations that are required in order to reproduce it?*

Simply opening Caret application produces the loading pane, and it never stops loading. It's very distracting when you're trying to concentrate on a project as the loading bar constantly moves.

### Description

The correct behavior ought to be that it would finish loading and stop the motion graphic. There is no way to stop it.

*If this is a bug, what would you expect the correct behavior to be? If it's a feature request, what do you want Caret to do? Are there other examples of this feature that I could look at? Screenshots are always helpful.*

### Additional notes

*If this is a bug, is there anything else I should know? If it's a feature request, any caveats I should keep in mind?*

### System details

*Please provide your Chrome version and operating system here.*

Version 73.0.3683.86 os windows 10

![image](https://user-images.githubusercontent.com/49407357/55737209-64362480-59ea-11e9-8695-f0d149a1dacb.png)

**Comment by thomaswilburn** [comment]
This generally happens when something goes wrong while loading a project file: maybe the folder or file no longer exists, for example. If it's possible for you to turn on extension inspection and then provide us with any errors that you see on application load, that would be hugely helpful. Otherwise, there are a lot of potential causes and it's hard to nail down.
