### ISSUE TITLE
Add Support for Salesforce file extenions

### ISSUE THREAD

**Issue by tccloudz** [thomaswilburn/Caret#693]
### Type of issue (choose one):
  - [ ] Bug
  - [ X] Feature request
  - [ ] Question

### Description

Would it be possible to add the following extensions for Salesforce development?

- Apex: ["apex|cls|trigger|tgr"]

- Visualforce: ["vfp|component|page"],

Thank you!

### System details

chrome version: Version 73.0.3683.103 (Official Build) (64-bit)
OS: Windows 10 Pro

**Comment by thomaswilburn** [comment]
What syntax modes should be activated for those extensions?

**Comment by tccloudz** [comment]
Syntax mode for apex,cls,trigger and tgr should be Apex (https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/apex.js).

Syntax mode for vfp,component, and page should be visualforce (https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/visualforce.js)

Please let me know if that clarifies your question. Thanks.
