### ISSUE TITLE
Update to ChromeOS 74.0.3729.125 causes line display bug

### ISSUE THREAD

**Issue by jessepav** [thomaswilburn/Caret#694]
### Type of issue (choose one):
  - [X] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

It was after an update of my Chromebooks to 74.0.3729.125 that I saw this issue. Reproducible every time Caret starts.

### Description

On the initial blank document, pressing Enter will cause the previous line to scroll off the top of the screen - if I scroll up manually, only 3 lines are visible at any time.

### Additional notes

Opening a second tab fixes the problem. So I just open and close a Caret tab and everything starts to work.

### System details

Acer Chromebook 64-bit version 74.0.3729.125

**Comment by thomaswilburn** [comment]
If you resize the window, does that also fix the bug? Sounds like it might be an Ace/flexbox thing.

**Comment by jessepav** [comment]
Yes, resizing the window fixes the bug as well!

**Comment by thomaswilburn** [comment]
Okay, should be a pretty easy fix then, I'll take a look this weekend.

**Comment by thomaswilburn** [comment]
Never mind, that was easy. Deploying a fix now.
