### ISSUE TITLE
Can I push code to Github with Caret?

### ISSUE THREAD

**Issue by pred12** [thomaswilburn/Caret#697]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

### Description

Hello I was wondering if their was a way to push code to Github with in Caret? thanks

### System details

Chrome OS beta

**Comment by thomaswilburn** [comment]
No, Caret is only for editing text.
