### ISSUE TITLE
When you close and reopen caret the "project" bar in the side is gone and you have to re open it 

### ISSUE THREAD

**Issue by pred12** [thomaswilburn/Caret#698]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [x ] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

Closing and re opening
### Description

So when I close out caret the project bar must close it self, when I turn on caret again, i have to go to the poject tab and add my project back

### System details
Chrome OS beta

**Comment by thomaswilburn** [comment]
This is the expected behavior if you add a folder but don't save a project config file.
