### ISSUE TITLE
Option to adjust line height/spacing

### ISSUE THREAD

**Issue by bakdar** [thomaswilburn/Caret#699]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

People who use a lot of non-Roman alphabets (CJK, etc.), as well as people with poor eye sight who use large fonts need more space between the lines for readability.
It would be great to have an option like in Atom that allows a user to adjust the line spacing.

I searched the Ace forum and it says to tweek the css, but I have no idea how to apply this to Caret.

**Comment by thomaswilburn** [comment]
This is a good idea, I'll see what I can do.

**Comment by bakdar** [comment]
Just tried the latest 1.8.20 update. It works!
Thank you!!
