### ISSUE TITLE
Syntax error reported when destructuring with the spread operator

### ISSUE THREAD

**Issue by tomsugden** [thomaswilburn/Caret#700]
Thanks for the great editor. I noticed that some ES6 features report as syntax errors when editing JavaScript files such as when using the spread operator to destructure an object. I did see an [old issue](https://github.com/thomaswilburn/Caret/issues/503) about adding support for ES6 that is marked as closed, so am assuming (perhaps wrongly) this is a bug rather than a feature request.

### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

1. Create a new file and set Caret to JavaScript mode
2. Type the following code:

```
let x = { a: 1, b: 2 };
let y = { ...x, c: 3 };
```

Line 2 will report as a syntax error.

### Description

The expected behaviour would be to recognise this form of destructuring as valid syntax.

### Additional notes

This is quite a useful guide to destructuring: https://codeburst.io/es6-destructuring-the-complete-guide-7f842d08b98f

### System details

Google Chrome | 75.0.3770.19 (Official Build) dev (64-bit)
Revision | a001f3b44e697dc5bdc61f99b7a11a3ff2c7764b-refs/branch-heads/3770@{#289}
Platform | 12105.25.0 (Official Build) dev-channel eve

**Comment by thomaswilburn** [comment]
The older ES6 bug is about the source code of the app itself, it doesn't apply to the syntax highlighting. 

We're largely at the mercy here of whatever Ace offers us for the editing component. If you can submit a PR for Ace to add these newer syntax features, or let me know when they're supported, I'll pull them in.

**Comment by tomsugden** [comment]
Thanks for the clarification. I followed the trail and found that Ace uses JSHint for the JavaScript syntax checking. It looks like proper support for the spread operator was [added in JSHint v2.10.0](https://jshint.com/blog/2019-02-05/release-2-10-0/) that was released in Feb 2019, but the JSHint version used in Ace [hasn't been updated since Sept 2015](https://github.com/ajaxorg/ace/tree/master/lib/ace/mode/javascript). Will let you know if I notice this being updated. In the meantime, `// jshint ignore:start` and `// jshint ignore:end` can be used to ignore the syntax.
