### ISSUE TITLE
Enchancement: Formatting

### ISSUE THREAD

**Issue by OoLunar** [thomaswilburn/Caret#701]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [x] Question

### Test steps
N/A
### Description
I noticed that on the Chrome Web Store, your extension had shown that it's supports formatting, syntax highlighting, themes, etc, etc.

![Chrome Web Store picture](https://user-images.githubusercontent.com/46751150/59063269-53305500-886d-11e9-836c-8beac00b1545.png)

However, I searched the app, the Github issues, the Chrome Web Store, only to find nothing about formatting.
### Additional notes
For formatting, try to add different styles. With PHP, you can format differently, take a look at this [site](http://www.phpformatter.com/).
Everything else is perfect though!
### System details
Chrome OS Minnie, Version 75.0.3770.61

**Comment by thomaswilburn** [comment]
If you mean prettifying or automated code formatting, that's not something that we offer, no. I'm sorry if that was misleading! Generally, Caret works well when paired with other tools like Prettier for that kind of thing.
