### ISSUE TITLE
Add specific syntax highlighting in vue js template

### ISSUE THREAD

**Issue by JulienAramino** [thomaswilburn/Caret#702]
Will it be possible to support syntax highlighting inside vue template for language such as pug ?
I notice that style and script sections are highlighted, html in template also, but if I defined:
`<template lang="pug">`
It do not highlight.
I will be great to support this.
Maybe my request is very specific to vue and pug, please do not hesitated to rewrite it properly.

**Comment by thomaswilburn** [comment]
It's not up to us, it's dependent on Ace.
