### ISSUE TITLE
Add support for newer js syntax

### ISSUE THREAD

**Issue by bahaaaldin214** [thomaswilburn/Caret#703]
I been using the editor for making web apps and its great and everything except when it comes to js, there are 2 specific problem im talking about.
 
One: there is no idle for js in html files. In html as you might know you can have js in the html file, when I do and I know I have an error, it doesn't say anything. 

Two: The js (idle I think its called) is outdated I cant use every time I use new script (EMCA6 I belive) it gives me error but runs perfectly fine  

### Type of issue:
  - [ ] Bug

### Test steps
You can put any of these code blocks in the editor, the first one in the html file won't say anything. The last 2 will say its an error however it runs fine in the browser.

in a html file
```html
<script>
function bar(){ woops!
</script>
```
in a js file
```js
async setUp(controller){
    this.playerData = await getData("players", this.name);
    this.volume = [this.playerData.Width, this.playerData.Height];
  }
```

```js
console.log(2**2)
```

**Comment by thomaswilburn** [comment]
This is not something we can fix, it is an issue with Ace and should be fixed there.
