### ISSUE TITLE
Better higlighting for search results in dark mode

### ISSUE THREAD

**Issue by eevleevs** [thomaswilburn/Caret#709]
Hi, I find that the colours used for highlighting search results in dark mode have poor contrast, and it is difficult to visualise the matches. I use Tomorrow Night (bright), but seems to be a common problem for most of the dark themes. Please consider brighter highlight colours in dark mode.

**Comment by thomaswilburn** [comment]
Please file this against Ace, which controls the editor theming, and we'll merge from upstream when the change is made.
