### ISSUE TITLE
FSharp syntax support

### ISSUE THREAD

**Issue by nikoudel** [thomaswilburn/Caret#711]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

### Description

Could you please add syntax highlighting for the F# language?
Currently .fs files are identified as Forth language but F# must be far more widespread these days so it might make sense to choose it instead...

**Comment by thomaswilburn** [comment]
Sure, I'll look into it. In the meantime, you can run `sessions:open-settings-file ace` to edit your local mode configuration.

**Comment by nikoudel** [comment]
Took some time to figure out what means to "run sessions:open..." but now it works as expected.

In case somebody else needs: in "Settings / Menus" I added this line:
`{ "label": "Open settings / ace", "command": "session:open-settings-file", "argument": "ace" },`
and then was able to open the ace.json file. There I changed the line for Forth to this:
`{ "name": "fsharp", "label": "FSharp", "extensions": ["fs", "fsi", "fsx"] },`
