### ISSUE TITLE
Python3 Color Formatting Missing

### ISSUE THREAD

**Issue by wjziv** [thomaswilburn/Caret#712]
Python3 text color formatting is not supported in the current (only) Python language choice.

As of yet, I've found format strings don't highlight correctly. Example:
```
adlib = {
    'noun' : 'test',
    'verb' : 'is'
}
f"this {adlib['verb']} a {adlib['noun']}"
```

**Comment by thomaswilburn** [comment]
Does this highlight correctly in the Ace kitchen sink? We don't build the syntax modes ourselves.

**Comment by wjziv** [comment]
Yep--same formatting persists.

There are numerous open tickets regarding what I'm referring to. I didn't realize it was a dependency here. Thanks for the info. I'll close this.

**Comment by wjziv** [comment]
#https://github.com/ajaxorg/ace/issues/2251
