### ISSUE TITLE
Allow closing without prompt to save, just continue where left off

### ISSUE THREAD

**Issue by erenoglu** [thomaswilburn/Caret#714]
This is a wish. I'm used to using notepad++, where you can just open it, write down some notes, maybe in multiple "new files", not save any of them and just close the app. It does not ask you to save or discard or cancel, just closes.

Next time notepad++ is launched, it starts from where it was left off, with exact same "unsaved" files and any other open files. 

This is useful when you're taking notes on something but dont want to spend time saving. (you can save later if you like)

**Comment by thomaswilburn** [comment]
There is a bug for this (search for indexdb-backed files) but it's not something I have time to build at this time. I'd take a PR for it though.
