### ISSUE TITLE
JS linter broken

### ISSUE THREAD

**Issue by bahaaaldin214** [thomaswilburn/Caret#715]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [ ] Bug

### Test steps
2 bugs

first bug:

open and html file
add a script tag
start coding js
type any invalid js syntax

it wouldn't give a error

second bug

this isnt really a bug, its more of a feature:

the linter only lints es5, and if I typed in es6 syntax such as
```js
let someVar = 5;

someVar = someVar**2 //error expected an identifier instead saw "*"
```
 
### Description

*If this is a bug, what would you expect the correct behavior to be? If it's a feature request, what do you want Caret to do? Are there other examples of this feature that I could look at? Screenshots are always helpful.*

I think you can just use the newest version of ESLINT, and enable inside script tag in html

### Additional notes

*If this is a bug, is there anything else I should know? If it's a feature request, any caveats I should keep in mind?*

I think I open this issue and it got closed without being resolved even after 18.21

### System details

*Please provide your Chrome version and operating system here.*

**Comment by thomaswilburn** [comment]
The linter is bundled with Ace, I don't package it as a separate dependency. Please file this with them, and then I'll pull from upstream.
