### ISSUE TITLE
Ducky Script in Caret

### ISSUE THREAD

**Issue by GunnerBasil** [thomaswilburn/Caret#718]
### Type of issue (choose one):
  - [ ] Bug
  - [ x] Feature request
  - [ ] Question

### Description

*Can you add Ducky Script as a language that we can use? I think it would be a cool small addition!*

**Comment by thomaswilburn** [comment]
Is this a language supported by Ace? We inherit our syntax support from the editing component.

**Comment by GunnerBasil** [comment]
What's Ace?

**Comment by GunnerBasil** [comment]
@thomaswilburn 
https://github.com/hak5darren/USB-Rubber-Ducky/wiki/Duckyscript

**Comment by GunnerBasil** [comment]
this is what it is

**Comment by GunnerBasil** [comment]
I don't think that Ace has it, but it's has a EXTREMELY simple syntax, so It would probably be easy to create.

**Comment by thomaswilburn** [comment]
If you'd like to have it, file a request or pull request with https://github.com/ajaxorg/ace and we can pull from there, but we don't add new languages to Carry directly.

**Comment by GunnerBasil** [comment]
compare what to what?

**Comment by GunnerBasil** [comment]
@thomaswilburn 
sorry to bother you again, but I don't want to mess this up.

**Comment by thomaswilburn** [comment]
Maybe just file an issue with them then.

**Comment by GunnerBasil** [comment]
???
I'm a noob, srry

**Comment by GunnerBasil** [comment]
OOOH I'm just dumb
