### ISSUE TITLE
Will Caret continue to work when Google shuts down Chrome Apps?

### ISSUE THREAD

**Issue by BurtThaMan** [thomaswilburn/Caret#724]
### Type of issue (choose one):
  - [x] Question

### Test steps
N/A

### Description

Will Caret continue to work when Google shuts down Chrome Apps this year?

### Additional notes

N/A

### System details

Windows and ChromeOS

**Comment by thomaswilburn** [comment]
Sadly, no. There are some efforts to make it work in-browser, but nothing official (the API support isn't there yet).

**Comment by BurtThaMan** [comment]
Ohh No! 😢

**Comment by scitronboy** [comment]
Isn't there the possibility that it would continue to work through
Chromium? Or using a custom download and then adding it on the extensions
page?

**Comment by thomaswilburn** [comment]
I haven't had any indication from Google that that would continue to be the case. It's possible that there could be a Pale Moon-style fork of the browser to retain the packaged app support code. But I suspect it will be removed from the mainline branch fairly soon after deprecation. I'm actually surprised it hasn't happened yet (it's still possible to test/debug apps on Windows, even though the store no longer supports them).

**Comment by YemSalat** [comment]
Any chance of moving to Electron? I realize it has different APIs for stuff like filesystem, but have you considered this at all? @thomaswilburn

**Comment by thomaswilburn** [comment]
I haven't really bothered. Caret's big advantage is that it is small and can run everywhere. Once Electron enters the picture, I don't know what this app offers that you can't get better from VS Code or Atom, or even Brackets.

**Comment by YemSalat** [comment]
I see, for me personally Caret was the only "modern" text editor which runs smoothly on Raspberry Pi. Not sure if this can be replicated on Electron platform though. 
Shame google is shutting down chrome apps..

**Comment by scitronboy** [comment]
@YemSalat Same. Unfortunately however, Electron apps run quite poorly on Raspberry Pi.
