### ISSUE TITLE
Can Caret be ported to a Progressive Web App?

### ISSUE THREAD

**Issue by nealey** [thomaswilburn/Caret#727]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

### Description

Based on [a bug comment](https://github.com/thomaswilburn/Caret/issues/723#issuecomment-607566273), the Caret author thinks Caret is a dead end, due to Google deprecating Chrome apps. The author isn't wrong, entirely.

It would be worth somebody's time to try got get Caret working as a Progressive Web App. I have tried several times to get the project to build, but failed every time, as I'm not well versed in npm or node or whatever this uses to build.

If someone is able to get it to build, the next step would be to try serving the built files as web pages. There are surely aspects of it which need work in order to function as a PWA: the "open directory tree as project" one strikes me immediately as a challenge, but there are likely others. But I expect it may be possible to get everything going properly.

**Comment by thomaswilburn** [comment]
The author would prefer you didn't use his issues as a message board, honestly.

**Comment by YemSalat** [comment]
@nealey PWAs dont have filesystem apis (at least not in a way that Caret would require) So the answer to your question is: no.

**Comment by nealey** [comment]
> The author would prefer you didn't use his issues as a message board, honestly.

Okay, I'm sorry. I'll fork and try to maybe drum up some interest on Reddit.

**Comment by dereckson** [comment]
> @nealey PWAs dont have filesystem apis (at least not in a way that Caret would require) So the answer to your question is: no.

https://web.dev/native-file-system/ < for Chrome, the target browser of Caret, there is an API available

**Comment by tapted** [comment]
A fork in https://github.com/PaulKinlan/Caret/commits/master has a few changes to adopt the "File System Access" API (as it's now called), and deploy Caret as a PWA. But the API has evolved since then as other browsers vendors have worked on standardising it.

There's also the https://googlechromelabs.github.io/text-editor/ demo app.

**Comment by sparklingwinepadre** [comment]
@tapted Thanks for this update! Was able to play around with the PWA demo and works well! Looking forward to new releases as Chrome Apps will be deprecating soon! Well done!
