### ISSUE TITLE
Text may be blurry after scrolling

### ISSUE THREAD

**Issue by lid** [thomaswilburn/Caret#729]
# Type of issue (choose one):
  - [X] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

*What steps cause the problem to occur? Are there any particular settings or configurations that are required in order to reproduce it?*

### Description

After scrolling in Caret, the text sometimes appears to be more blurry, depending on where the scroll is stopped. Other code editors (e.g. CodePad) and webviews do not exhibit this behavior. Could this be the result of an undesirable antialiasing behavior?

Before scrolling:
![not-blurry](https://user-images.githubusercontent.com/831121/82750122-63a74b80-9dae-11ea-821b-680382a1c42c.png)

After scrolling:
![blurry](https://user-images.githubusercontent.com/831121/82750126-643fe200-9dae-11ea-8e07-9bc1cae1e588.png)

### System details
ChromeOS | 83.0.4103.50 (Official Build) beta (64-bit)

**Comment by scitronboy** [comment]
My guess would be that the issue is occurring because of a css transform of
half a pixel, resulting in pixel blurring.

**Comment by thomaswilburn** [comment]
There's nothing as far as I know that we've changed that would cause this. Do you also see this on the Ace kitchen sink?

**Comment by lid** [comment]
I do see this same behavior on Ace Kitchen Sink, but not on [Code Pad](https://github.com/andrewbrg/codepad-chrome-app), or [Text](https://chrome.google.com/webstore/detail/text/mmfbcljfglbokpmkimbfghdkjmjhdgbg).

**Comment by thomaswilburn** [comment]
I think those other editors use CodeMirror. If you're also seeing it on the Kitchen Sink, you should file a bug with Ace, and we'll pull from upstream when it's fixed.
