### ISSUE TITLE
Quickly fold (or unfold) all code?

### ISSUE THREAD

**Issue by mknev** [thomaswilburn/Caret#731]
Hi, thanks for the great program! Just wondering if there's a way (possibly a keyboard shortcut) to quickly fold or unfold all functions (specifically in python code)? If not, this would make a great feature!

### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x] Question

**Comment by thomaswilburn** [comment]
You should be able to bind to the ace `foldall` command to make this work. See the Ctrl-Space autocomplete keyboard binding for an example of how to do it.
