### ISSUE TITLE
Adding rainbow brackets

### ISSUE THREAD

**Issue by wesort** [thomaswilburn/Caret#732]
Are there any ways for rainbow brackets to be added? I presume this would rely on an Ace theme having this included or having access to edit the themes files.

### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [x] Question

![image](https://user-images.githubusercontent.com/3920126/84356852-b0679080-abbc-11ea-9163-dd118f192e13.png)

**Comment by thomaswilburn** [comment]
This would be required at the level of Ace, we don't customize the editor component if possible.
