### ISSUE TITLE
Forcing menus to English

### ISSUE THREAD

**Issue by PatrickHonorez** [thomaswilburn/Caret#735]
### Type of issue (choose one):
  - [ ] Bug
  - [ ] Feature request
  - [x ] Question

### Description

Hi, with the new version 1.8.25, Caret now has french menus on my machines.
However I prefer keeping the ENglish menus. Is there a way to force English menus ?

Thanks !
### System details
This happens on my Windows 10 laptop and on my Chromebook with 83.0.4103.112

**Comment by thomaswilburn** [comment]
Sorry, Caret just uses the localization method built into Chrome, and we don't exercise manual control over it. If your browser is set to use a specific language, it will also use that language. However, if you can set Chrome in the settings to use English for its UI (search for "language" to find it) you should be able to override that.

**Comment by PatrickHonorez** [comment]
Tanks for the reply.
I would suggest adding a flag to force english.

Patrick

Le mar. 23 juin 2020 à 20:41, Thomas Wilburn <notifications@github.com> a
écrit :
