### ISSUE TITLE
Interface Improvement

### ISSUE THREAD

**Issue by waliomer** [thomaswilburn/Caret#736]
### Feature requests (improvements)
1. No need for the tab to show if only one is open.
2. The tab is too thick (reduce height).
3. The first line is very close to the upper border.
4. The purple line below the active tab is too thick.

### Type of issue (choose one):
  - [x] Feature request

### System details
Version 85.0.4176.0 (Official Build) dev (64-bit) on Chromebook.

**Comment by thomaswilburn** [comment]
Happy to look at a pull request with these changes.
