### ISSUE TITLE
Deletes space after save

### ISSUE THREAD

**Issue by JustADudeWhoLikesCode** [thomaswilburn/Caret#738]
### Type of issue (choose one):
  - [ X] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

Have auto save on a rapid speed

### Description

It deletes a space during save

### Additional notes

I think the auto delete space is intended to happen, but it should have a setting to turn it off.

### System details

Chrome latest on chromebook

**Comment by thomaswilburn** [comment]
There is a trim whitespace setting you can check.
