### ISSUE TITLE
Remembering File Position on Reopen

### ISSUE THREAD

**Issue by LilMisSierra** [thomaswilburn/Caret#739]
### Type of issue (choose one):
  - [ ] Bug
  - [x] Feature request
  - [ ] Question

### Description

I love Caret, and it does pretty much everything that I need. The only real annoyance I have with it is that, while it does re-open the files I've been working on when relaunching it, it just puts them all at the top of the file, rather than remembering where I was. For most things, that isn't too bad, but for longer projects, it would be nice if there was some way for it to open back to where I was last working. Not sure if that's a possibility or not, or if there's some setting for it I haven't been able to find, but thanks either way for the otherwise great program!

**Comment by thomaswilburn** [comment]
Right now, we don't store information about re-opened files to be able to do this, unfortunately. I'd be happy to take a pull request for it, though packaged apps like Caret are being shut down by Google fairly soon, so it may not be worthwhile effort for a lot of people.
