### ISSUE TITLE
error detector brakes when setting variables with static

### ISSUE THREAD

**Issue by qqqwwweeerrrtttt12123** [thomaswilburn/Caret#743]
### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps
code to reproduce
```
class t {
  static num = 3;
}

```
### Description
When using the static keyword in a class to set a variable, the error detector brakes. this is valid javascript code
### Additional notes
error: "Class properties must be methods. Expected '(' but instead saw '='."
later when closing the class: "Expected '(' but instead saw '}'. Expected an identifierand instead saw ''. Unrecoverable syntax error. (100% scanned)"
### System details

86.0.4240.197 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)

**Comment by thomaswilburn** [comment]
This bug should be filed against ajaxorg/ace, since we're using their JSLint from Ace itself. I don't know when the last time they updated it was, but if they support ES2017+ syntax now, I'm happy to pull and update from there.
