### ISSUE TITLE
error detector breaks when using spread syntax in object literal

### ISSUE THREAD

**Issue by qqqwwweeerrrtttt12123** [thomaswilburn/Caret#744]
### Type of issue (choose one):
  - [X] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps
this code:
```
a = {a: 1, b: 2};
b = {b: 1, c: 2};
c = {...a, ...b};
```
### Description
when using spread syntax in an object literal, the error detector breaks.
### Additional notes
error: "Expected '}' to match '{' fro line 3 and instead saw '...'.
Missing semicolon.
Unrecoverable syntax error. (100% scanned)." 
*If this is a bug, is there anything else I should know? If it's a feature request, any caveats I should keep in mind?*

### System details
86.0.4240.197 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)

**Comment by thomaswilburn** [comment]
See also: the last bug you filed. These are issues with Ace, we can't fix them here, they have to be patched upstream.
