### ISSUE TITLE
Text cursor jumping ahead or behind text

### ISSUE THREAD

**Issue by CodingCodre** [thomaswilburn/Caret#745]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [x] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

*What steps cause the problem to occur? Are there any particular settings or configurations that are required in order to reproduce it?*
The problem started occurring suddenly after reinstalling Caret.

### Description

*If this is a bug, what would you expect the correct behaviour to be? If it's a feature request, what do you want Caret to do? Are there other examples of this feature that I could look at? Screenshots are always helpful.*
I would expect Caret to have the text cursor stay in front of the words like normal.

### Additional notes

*If this is a bug, is there anything else I should know? If it's a feature request, any caveats I should keep in mind?*

### System details

*Please provide your Chrome version and operating system here.*
Chrome OS, version 87.0.4280.109

**Comment by thomaswilburn** [comment]
Do you have Caret set to use a non-monospace font?

**Comment by Foonicular** [comment]
How do I check?

**Comment by thomaswilburn** [comment]
There's supposed to be an automated check. You can take a look in your settings and see if "fontFamily" is set to anything odd, or set it to "monospace" to be sure.

**Comment by Foonicular** [comment]
i did it but it still isnt working as expected

**Comment by thomaswilburn** [comment]
Well, I'm happy to leave this open if someone wants to tackle it. I don't really have enough information to solve this from the report, though.

**Comment by hsbizwhiz** [comment]
I have a student of mine using caret on a Lenovo Chromebook with the same problem. I've tried changing the font family to "monospace" and left it blank with no improvement...

**Comment by Foonicular** [comment]
I believe what’s happening is that each letters “box” if you will is the same/wrong size, and is therefore causing the cursor to jump around…

**Comment by thomaswilburn** [comment]
If they're actually the same size, it would work: Ace only supports monospaced fonts.

**Comment by Foonicular** [comment]
I have an hp laptop..

**Comment by CodingCodre** [comment]
@thomaswilburn I reset Caret with no luck, although I have found that when I highlight things, the highlight (blue thing you can use to select text) highlights even the empty space... Maybe the text isn't being displayed properly?

**Comment by CodingCodre** [comment]
@thomaswilburn Have some screenshots, maybe these will help. It's really annoying that this isn't working. [https://imgur.com/a/kT5c2He](url)

**Comment by thomaswilburn** [comment]
That's definitely a proportional font, which causes problems. Are you able to switch to a monospaced font? It may depend on your system, but good options are listed in this blog post: https://www.client9.com/css-system-font-stack-monospace-v2/

**Comment by CodingCodre** [comment]
@thomaswilburn How do I change the font?

**Comment by CodingCodre** [comment]
@thomaswilburn Nevermind, I fixed it! I found that "Liberation Mono" worked for me!
