### ISSUE TITLE
Opera Browser Compatibility issue.

### ISSUE THREAD

**Issue by Geofirm** [thomaswilburn/Caret#755]
### Type of issue (choose one):
  - [x] Feature request

### Test steps

(Simple installation steps)

### Description

Hello, despite not well-versed in HTML or anything too technological, I'd like to request that the application developer allow the application to be installed onto The Opera Browser. An addon called "Install Chrome Extensions" allows us to install Google Chrome extensions, and I was hoping you could either introduce yourselves to our application page or simply add support for the extension. Thanks!

### Additional notes

Install Chrome Extensions:
Here's their extension page - https://addons.opera.com/en/extensions/details/install-chrome-extensions/

### System details

Opera Ver. 76.0.4017.107 \ Windows 10

**Comment by thomaswilburn** [comment]
This isn't technically possible.
