### ISSUE TITLE
Switch tabs with ctrl+tab in visual order?

### ISSUE THREAD

**Issue by TheHarmonicRealm** [thomaswilburn/Caret#758]
Hi! I would love to have a configuration option like in other editors to make tabs switch with ctrl+tab in the order they're shown on the top of the screen, rather than recently used order, like they used to be in browsers.
Thanks

**Comment by thomaswilburn** [comment]
This already exists. Change the keymapping for Ctrl-Tab to "session:change-tab-linear" in your keys.json file.
