### ISSUE TITLE
Typing in a different spot than cursor location

### ISSUE THREAD

**Issue by ddubczak** [thomaswilburn/Caret#760]
Thanks for filing an issue! Please feel free to delete this paragraph and adapt the template below to fit your needs. Before filing an issue, it may make sense to search through [closed issues](https://github.com/thomaswilburn/Caret/issues?q=is%3Aissue+is%3Aclosed) to see if your question has already been addressed. If you have questions, you can also check the [wiki](https://github.com/thomaswilburn/Caret/wiki) for answers.

### Type of issue (choose one):
  - [x ] Bug
  - [ ] Feature request
  - [ ] Question

### Test steps

I have two different machines, identical chromebooks but different accounts. One one account, Caret works fine. On the other, when in an HTML document, the text types in a different location than the cursor position. It ranges from about 5-20 spaces behind the cursor on the line. 

### Description

Unable to replicate the issue with the account that works correctly. Have tried uninstalling and resetting Caret app.

### Additional notes

*If this is a bug, is there anything else I should know? If it's a feature request, any caveats I should keep in mind?*

### System details

Working OS: Version 85.0.4183.133
Non-working OS: V 87.0.4280.152

**Comment by thomaswilburn** [comment]
Check to make sure the affected machine is not using a variable-width font. Caret only supports monospaced fonts.
