### ISSUE TITLE
Please add: Sublime's "quick elements" feature

### ISSUE THREAD

**Issue by tloner** [thomaswilburn/Caret#766]
# Feature request
##### (In HTML and similar) 
Can you add sublime's trick of just typing the element name and attributes, like:
`div.container#demo[contexteditable]`
Then when you press space (or tab) it makes an element with those details:
`<div class="container" id="demo" contexteditable></div>`
#### ALSO:
put the cursor inside of beginning and ending tags on creating.

**Comment by thomaswilburn** [comment]
Caret is essentially in maintenance mode, so I'm not planning any larger features like this. I believe it is provided by Ace's Emmet plugin, and you might see if one of the other Caret forks supports that.

**Comment by tloner** [comment]
Thanks!
